--BD: DC09
--EXPORTAR O PEDIDO PARA O JDE
DECLARE
  VRETORNO1 VARCHAR2(100);
  VRETORNO2 VARCHAR2(100);
BEGIN
  mercanet_qa.MERCP_CONCORRENTE_EXPORT(VRETORNO1, VRETORNO2);
  COMMIT;
END;

------------------------------------------------------------------------------

--BD: DC09
--ATUALIZACAO INTERFACE PARA OFICIAIS DE PEDIDO

DECLARE
  VRETORNO VARCHAR2(100);
BEGIN
  mercanet_qa.MERCP_APIS_INTERFACE.MERCP_API_START (NULL, 30, VRETORNO);
  DBMS_OUTPUT.PUT_LINE('RETORNO: '||VRETORNO);
  COMMIT;
END;


--TIPO_TABELA = 20 - INTEGRAÇÃO DE CLIENTES
--TIPO_TABELA = 21 - INTEGRAÇÃO DE ATRIBUTOS DE CLIENTES
--TIPO_TABELA = 29 - INTEGRAÇÃO DE CLIENTES E REPRESENTANTES
--TIPO_TABELA = 30 - INTEGRAÇÃO DE PEDIDOS
--TIPO_TABELA = 35 - INTEGRAÇÃO DE NOTAS_FISCAIS
--TIPO_TABELA = 40 - INTEGRAÇÃO DE PRODUTOS
--TIPO_TABELA = 41 - INTEGRAÇÃO DE PRODUTOS POR EMBALAGEM
--TIPO_TABELA = 42 - INTEGRAÇÃO DE PREÇOS
--TIPO_TABELA = 43 - INTEGRAÇÃO DE IMAGEM
--TIPO_TABELA = 48 - INTEGRAÇÃO DE MARCAS
--TIPO_TABELA = 49 - INTEGRAÇÃO DE TIPOS DE PRODUTOS
--TIPO_TABELA = 53 - INTEGRAÇÃO DE ESTOQUE
--TIPO_TABELA = 54 - INTEGRAÇÃO DE ESTOQUE POR CD
--TIPO_TABELA = 87 - INTEGRAÇÃO DE REDES
--TIPO_TABELA = 8003 - INTEGRAÇÃO DE GRUPOS
--TIPO_TABELA = 8004 - INTEGRAÇÃO DE FAMÍLIAS
--TIPO_TABELA = 8005 - INTEGRAÇÃO DE REPRESENTANTES
--TIPO_TABELA = 8007 - INTEGRAÇÃO DE OPERAÇÕES FISCAIS (TIPO VENDA)
--TIPO_TABELA = 8012 - INTEGRAÇÃO DE CONDIÇÕES DE PAGAMENTO
--TIPO_TABELA = 8017 - INTEGRAÇÃO DE OPERAÇÕES FISCAIS POR ESTADO
--TIPO_TABELA = 80106 - INTEGRAÇÃO DE MARGEM PRESUMIDA
--TIPO_TABELA = 80107 - INTEGRAÇÃO DE ITENS DE MARGEM PRESUMIDA 
--TIPO_TABELA = 80133 - INTEGRAÇÃO DE TÍTULOS
--TIPO_TABELA = 80134 - INTEGRAÇÃO DE MOVIMENTAÇÃO DE TÍTULOS
--TIPO_TABELA = 90000 - INTEGRAÇÃO DE ALIQUOTAS DE ICMS
--TIPO_TABELA = 90001 - INTEGRAÇÃO DE ATRIBUTOS DE PRODUTOS
--TIPO_TABELA = 90002 - INTEGRAÇÃO DE REGRAS DE EXCEÇÃO DE ICMS
--TIPO_TABELA = 90003 - INTEGRAÇÃO DE REGRAS DE ITENS DE EXCEÇÃO DE ICMS
--TIPO_TABELA = 90004 - INTEGRAÇÃO DE OBSERVAÇÕES DO CLIENTE
--TIPO_TABELA = 90005 - INTEGRAÇÃO DE MIX DE PRODUTOS
--TIPO_TABELA = 90006 - INTEGRAÇÃO DE CADASTROS DE ATRIBUTOS
--TIPO_TABELA = 90007 - INTEGRAÇÃO DE LOTES DOS ITENS DA NOTA FISCAL
--TIPO_TABELA = 90008 - INTEGRAÇÃO DE CLIENTES DROGACENTER
