WITH TAB1 AS 
(SELECT /*+ MATERIALIZE */ PV05_CONTROLE,
      rtrim(xmlagg(xmlelement(e,
      trim(pv05_tagfiltro) || '#') ORDER BY
 PV05_SEQ) .extract('//text()'),
      ',')
      filtros 
FROM MERCANET_PRD.MPV05 TB_FILTROS GROUP BY
 PV05_CONTROLE),
      TAB2 AS 
(SELECT /*+ MATERIALIZE */ 
      DISTINCT PV06_POLITICA,
      PV06_CONTROLE,
      PV06_TIPO,
      PV06_IDENT,
      PV06_IDREGRA,
      PV06_DATA_ALTER,
      PV06_PRAZOMIN,
      PV06_PRAZOMAX,
      PV06_QTDEMIN,
      PV06_QTDEMAX,
      PV06_VALMIN,
      PV06_VALMAX,
      PV06_DESCTOMIN,
      PV06_DESCTOMAX
FROM MERCANET_PRD.MPV06 
WHERE PV06_TIPO = 'A') 
SELECT * FROM 
(SELECT TAB3.DB_ORDP_SEQUENCIA AS "ORDEM DE BUSCA",
      TAB2.PV06_POLITICA AS "POLITICA",
      TAB5.DB_RES_DESC AS "DESCRICAO",
      REPLACE(SUBSTR(TAB1.FILTROS,
      1,
      LENGTH(TAB1.FILTROS) - 1),
      '#',
      ' | ') AS "FILTROS UTILIZADOS",
      REPLACE(TAB2.PV06_IDENT,
      '#',
      ' | ') AS "VALORES FILTRADOS",
      TAB4.DB_CPO_TAGATRIB AS "CAMPO ATRIBUIDO",
      TAB4.DB_CPO_VALORINF AS "VALOR ATRIBUIDO",
      length(REPLACE(SUBSTR(TAB1.FILTROS,
      1,
      LENGTH(TAB1.FILTROS) - 1),
      '#',
      ' | ')) - length(replace(REPLACE(SUBSTR(TAB1.FILTROS,
      1,
      LENGTH(TAB1.FILTROS) - 1),
      '#',
      ' | '),
      '|',
      null)) + 1 AS "TOTAL DE FILTROS",
      length(REPLACE(TAB2.PV06_IDENT,
      '#',
      ' | ')) - length(replace(REPLACE(TAB2.PV06_IDENT,
      '#',
      ' | '),
      '|',
      null)) + 1 AS "TOTAL DE VALORES FILTRADOS",
      pv06_data_alter AS "DATA ULTIMA ALTERACAO NA REGRA",
      
CASE WHEN TAB5.DB_RES_DTINI < SYSDATE AND TAB5.DB_RES_DTFIM > SYSDATE THEN 'VIGENTE' ELSE 'INATIVA' END AS "STATUS DA REGRA",
'PROBLEMA COM VIRGULAS' AS "TIPO DO PROBLEMA",
'\\SRVDC40\Mercanet\solucoes_regras\solucao1.txt'
AS "SOLUCAO DO PROBLEMA"
FROM TAB1,
     TAB2,
     MERCANET_PRD.DB_ORDEM_POLITICAS TAB3,
     MERCANET_PRD.DB_CPO_ATRIB TAB4,  
     MERCANET_PRD.DB_RESTRICAO TAB5
WHERE TAB2.PV06_POLITICA = TAB5.DB_RES_CODIGO
AND TAB2.PV06_TIPO = 'A' 
AND TAB2.PV06_CONTROLE = TAB1.PV05_CONTROLE 
AND TAB2.PV06_POLITICA = TAB3.DB_ORDP_POLITICA 
AND TAB2.PV06_POLITICA = TAB4.DB_CPO_CODIGO 
AND TAB2.PV06_IDREGRA = TAB4.DB_CPO_RES_PAI 
ORDER BY
 TAB3.DB_ORDP_SEQUENCIA,
 TAB2.PV06_POLITICA,
 TAB2.PV06_CONTROLE,
 TAB2.PV06_IDENT
)
WHERE "TOTAL DE VALORES FILTRADOS" <> "TOTAL DE FILTROS" 
UNION ALL
SELECT * FROM 
(SELECT TAB3.DB_ORDP_SEQUENCIA AS "ORDEM DE BUSCA",
      TAB2.PV06_POLITICA AS "POLITICA",
      TAB5.DB_RES_DESC AS "DESCRICAO",
      REPLACE(SUBSTR(TAB1.FILTROS,
      1,
      LENGTH(TAB1.FILTROS) - 1),
      '#',
      ' | ') AS "FILTROS UTILIZADOS",
      REPLACE(TAB2.PV06_IDENT,
      '#',
      ' | ') AS "VALORES FILTRADOS",
      TAB4.DB_CPO_TAGATRIB AS "CAMPO ATRIBUIDO",
      TAB4.DB_CPO_VALORINF AS "VALOR ATRIBUIDO",
      length(REPLACE(SUBSTR(TAB1.FILTROS,
      1,
      LENGTH(TAB1.FILTROS) - 1),
      '#',
      ' | ')) - length(replace(REPLACE(SUBSTR(TAB1.FILTROS,
      1,
      LENGTH(TAB1.FILTROS) - 1),
      '#',
      ' | '),
      '|',
      null)) + 1 AS "TOTAL DE FILTROS",
      length(REPLACE(TAB2.PV06_IDENT,
      '#',
      ' | ')) - length(replace(REPLACE(TAB2.PV06_IDENT,
      '#',
      ' | '),
      '|',
      null)) + 1 AS "TOTAL DE VALORES FILTRADOS",
      pv06_data_alter AS "DATA ULTIMA ALTERACAO NA REGRA",
      
CASE WHEN TAB5.DB_RES_DTINI < SYSDATE AND TAB5.DB_RES_DTFIM > SYSDATE THEN 'VIGENTE' ELSE 'INATIVA' END AS "STATUS DA REGRA",
'PROBLEMA COM ENTER NAS LINHAS' AS "TIPO DO PROBLEMA",
 '\\SRVDC40\Mercanet\solucoes_regras\solucao2.txt'
       AS "SOLUCAO DO PROBLEMA"
FROM TAB1,
      TAB2,
      MERCANET_PRD.DB_ORDEM_POLITICAS TAB3,
      MERCANET_PRD.DB_CPO_ATRIB TAB4,  
      MERCANET_PRD.DB_RESTRICAO TAB5
WHERE TAB2.PV06_POLITICA = TAB5.DB_RES_CODIGO
AND TAB2.PV06_TIPO = 'A' 
AND TAB2.PV06_CONTROLE = TAB1.PV05_CONTROLE 
AND TAB2.PV06_POLITICA = TAB3.DB_ORDP_POLITICA 
AND TAB2.PV06_POLITICA = TAB4.DB_CPO_CODIGO 
AND TAB2.PV06_IDREGRA = TAB4.DB_CPO_RES_PAI 
AND TAB2.PV06_IDENT LIKE '%
%'
ORDER BY
 TAB3.DB_ORDP_SEQUENCIA,
 TAB2.PV06_POLITICA,
 TAB2.PV06_CONTROLE,
 TAB2.PV06_IDENT
)
UNION ALL
SELECT * FROM 
(SELECT TAB3.DB_ORDP_SEQUENCIA AS "ORDEM DE BUSCA",
      TAB2.PV06_POLITICA AS "POLITICA",
      TAB5.DB_RES_DESC AS "DESCRICAO",
      REPLACE(SUBSTR(TAB1.FILTROS,
      1,
      LENGTH(TAB1.FILTROS) - 1),
      '#',
      ' | ') AS "FILTROS UTILIZADOS",
      REPLACE(TAB2.PV06_IDENT,
      '#',
      ' | ') AS "VALORES FILTRADOS",
      TAB4.DB_CPO_TAGATRIB AS "CAMPO ATRIBUIDO",
      TAB4.DB_CPO_VALORINF AS "VALOR ATRIBUIDO",
      length(REPLACE(SUBSTR(TAB1.FILTROS,
      1,
      LENGTH(TAB1.FILTROS) - 1),
      '#',
      ' | ')) - length(replace(REPLACE(SUBSTR(TAB1.FILTROS,
      1,
      LENGTH(TAB1.FILTROS) - 1),
      '#',
      ' | '),
      '|',
      null)) + 1 AS "TOTAL DE FILTROS",
      length(REPLACE(TAB2.PV06_IDENT,
      '#',
      ' | ')) - length(replace(REPLACE(TAB2.PV06_IDENT,
      '#',
      ' | '),
      '|',
      null)) + 1 AS "TOTAL DE VALORES FILTRADOS",
      pv06_data_alter AS "DATA ULTIMA ALTERACAO NA REGRA",
      
CASE WHEN TAB5.DB_RES_DTINI < SYSDATE AND TAB5.DB_RES_DTFIM > SYSDATE THEN 'VIGENTE' ELSE 'INATIVA' END AS "STATUS DA REGRA",
'LINHA COM CAMPO DE ATRIBUIÇÃO SEM VALOR' AS "TIPO DO PROBLEMA",
 '\\SRVDC40\Mercanet\solucoes_regras\solucao3.txt'
       AS "SOLUCAO DO PROBLEMA"
FROM TAB1,
     TAB2,
     MERCANET_PRD.DB_ORDEM_POLITICAS TAB3,
     MERCANET_PRD.DB_CPO_ATRIB TAB4,  
     MERCANET_PRD.DB_RESTRICAO TAB5,
     (SELECT db_resr_seqpai, rtrim(xmlagg(xmlelement(e,
      trim(db_resr_valor)) ORDER BY
 db_resr_seq) .extract('//text()'),
      ',')
      valores 
 FROM MERCANET_PRD.DB_RESTR_REGRAS 
 GROUP BY db_resr_seqpai) TAB6
WHERE TAB2.PV06_POLITICA = TAB5.DB_RES_CODIGO
AND TAB2.PV06_TIPO = 'A' 
AND TAB2.PV06_CONTROLE = TAB1.PV05_CONTROLE 
AND TAB2.PV06_POLITICA = TAB3.DB_ORDP_POLITICA 
AND TAB2.PV06_POLITICA = TAB4.DB_CPO_CODIGO 
AND TAB6.VALORES = REPLACE(TAB2.PV06_IDENT,'#',NULL)
AND TAB6.DB_RESR_SEQPAI = TAB4.DB_CPO_RES_PAI
AND TAB4.DB_CPO_VALORINF IS NULL 
ORDER BY
 TAB3.DB_ORDP_SEQUENCIA,
 TAB2.PV06_POLITICA,
 TAB2.PV06_CONTROLE,
 TAB2.PV06_IDENT
)
--------------
UNION ALL

SELECT *
 FROM 
(SELECT TAB3.DB_ORDP_SEQUENCIA AS "ORDEM DE BUSCA",
      TAB2.PV06_POLITICA AS "POLITICA",
      TAB5.DB_RES_DESC AS "DESCRICAO",
      REPLACE(SUBSTR(TAB1.FILTROS,
      1,
      LENGTH(TAB1.FILTROS) - 1),
      '#',
      ' | ') AS "FILTROS UTILIZADOS",
      REPLACE(TAB2.PV06_IDENT,
      '#',
      ' | ') AS "VALORES FILTRADOS",
      TAB4.DB_CPO_TAGATRIB AS "CAMPO ATRIBUIDO",
      TAB4.DB_CPO_VALORINF AS "VALOR ATRIBUIDO",
      length(REPLACE(SUBSTR(TAB1.FILTROS,
      1,
      LENGTH(TAB1.FILTROS) - 1),
      '#',
      ' | ')) - length(replace(REPLACE(SUBSTR(TAB1.FILTROS,
      1,
      LENGTH(TAB1.FILTROS) - 1),
      '#',
      ' | '),
      '|',
      null)) + 1 AS "TOTAL DE FILTROS",
      length(REPLACE(TAB2.PV06_IDENT,
      '#',
      ' | ')) - length(replace(REPLACE(TAB2.PV06_IDENT,
      '#',
      ' | '),
      '|',
      null)) + 1 AS "TOTAL DE VALORES FILTRADOS",
      pv06_data_alter AS "DATA ULTIMA ALTERACAO NA REGRA",
      
CASE WHEN TAB5.DB_RES_DTINI < SYSDATE AND TAB5.DB_RES_DTFIM > SYSDATE THEN 'VIGENTE' ELSE 'INATIVA' END AS "STATUS DA REGRA",
'REGRA DUPLICADA' AS "TIPO DO PROBLEMA",
 '\\SRVDC40\Mercanet\solucoes_regras\solucao4.txt'
       AS "SOLUCAO DO PROBLEMA"
FROM TAB1,
     TAB2,
     MERCANET_PRD.DB_ORDEM_POLITICAS TAB3,
     MERCANET_PRD.DB_CPO_ATRIB TAB4,  
     MERCANET_PRD.DB_RESTRICAO TAB5
WHERE TAB2.PV06_POLITICA = TAB5.DB_RES_CODIGO
AND TAB2.PV06_TIPO = 'A' 
AND TAB2.PV06_CONTROLE = TAB1.PV05_CONTROLE 
AND TAB2.PV06_POLITICA = TAB3.DB_ORDP_POLITICA 
AND TAB2.PV06_POLITICA = TAB4.DB_CPO_CODIGO 
AND TAB2.PV06_IDREGRA = TAB4.DB_CPO_RES_PAI
AND TAB2.PV06_IDENT||CASE WHEN TAB2.PV06_PRAZOMAX  > 0 THEN '#'||TAB2.PV06_PRAZOMIN ||'#'||TAB2.PV06_PRAZOMAX
                          WHEN TAB2.PV06_QTDEMAX   > 0 THEN '#'||TAB2.PV06_QTDEMIN  ||'#'||TAB2.PV06_QTDEMAX
                          WHEN TAB2.PV06_VALMAX    > 0 THEN '#'||TAB2.PV06_VALMIN   ||'#'||TAB2.PV06_VALMAX  
                          WHEN TAB2.PV06_DESCTOMAX > 0 THEN '#'||TAB2.PV06_DESCTOMIN||'#'||TAB2.PV06_DESCTOMAX END IN 
(SELECT T1.PV06_IDENT||CASE WHEN T1.PV06_PRAZOMAX  > 0 THEN '#'||T1.PV06_PRAZOMIN  ||'#'||T1.PV06_PRAZOMAX
                            WHEN T1.PV06_QTDEMAX   > 0 THEN '#'||T1.PV06_QTDEMIN   ||'#'||T1.PV06_QTDEMAX
                            WHEN T1.PV06_VALMAX    > 0 THEN '#'||T1.PV06_VALMIN    ||'#'||T1.PV06_VALMAX  
                            WHEN T1.PV06_DESCTOMAX > 0 THEN '#'||T1.PV06_DESCTOMIN ||'#'||T1.PV06_DESCTOMAX END 
  FROM MERCANET_PRD.MPV06 T1,
       MERCANET_PRD.DB_CPO_ATRIB T2
WHERE T1.PV06_TIPO = 'A'
  AND T1.PV06_POLITICA = T2.DB_CPO_CODIGO
  AND T1.PV06_IDREGRA = T2.DB_CPO_RES_PAI
GROUP BY T1.PV06_IDENT||CASE WHEN T1.PV06_PRAZOMAX > 0 THEN '#'||T1.PV06_PRAZOMIN||'#'||T1.PV06_PRAZOMAX
                        WHEN T1.PV06_QTDEMAX > 0 THEN  '#'||T1.PV06_QTDEMIN||'#'||T1.PV06_QTDEMAX
                        WHEN T1.PV06_VALMAX > 0 THEN '#'||T1.PV06_VALMIN||'#'||T1.PV06_VALMAX  
                        WHEN T1.PV06_DESCTOMAX > 0 THEN '#'||T1.PV06_DESCTOMIN||'#'||T1.PV06_DESCTOMAX END 
 HAVING COUNT(1) > 1 
    AND COUNT(DISTINCT T2.DB_CPO_TAGATRIB) = 1 -- +1 --> MAIS DE UM CAMPO ATRIBUICAO / = 1 MESMO CAMPO ATRIBUICAO 
    AND COUNT(DISTINCT T1.PV06_POLITICA)   > 1 -- +1 --> POLITICAS / =1 SOMENTE 1 POLITICA
    AND COUNT(DISTINCT T2.DB_CPO_VALORINF) = 1)-- +1 --> VALOR ATRIBUICAO DIFERENTES / =1 MESMO VALOR ATRIBUICAO                     
ORDER BY
 TAB2.PV06_IDENT||CASE WHEN TAB2.PV06_PRAZOMAX  > 0 THEN '#'||TAB2.PV06_PRAZOMIN ||'#'||TAB2.PV06_PRAZOMAX
                          WHEN TAB2.PV06_QTDEMAX   > 0 THEN '#'||TAB2.PV06_QTDEMIN  ||'#'||TAB2.PV06_QTDEMAX
                          WHEN TAB2.PV06_VALMAX    > 0 THEN '#'||TAB2.PV06_VALMIN   ||'#'||TAB2.PV06_VALMAX  
                          WHEN TAB2.PV06_DESCTOMAX > 0 THEN '#'||TAB2.PV06_DESCTOMIN||'#'||TAB2.PV06_DESCTOMAX END,
 TAB3.DB_ORDP_SEQUENCIA,
 TAB2.PV06_POLITICA,
 TAB2.PV06_CONTROLE
)


/*
SELECT T1.PV06_IDENT||CASE WHEN T1.PV06_PRAZOMAX > 0 THEN '#'||T1.PV06_PRAZOMIN||'#'||T1.PV06_PRAZOMAX
                           WHEN T1.PV06_QTDEMAX > 0 THEN  '#'||T1.PV06_QTDEMIN||'#'||T1.PV06_QTDEMAX
                           WHEN T1.PV06_VALMAX > 0 THEN '#'||PV06_VALMIN||'#'||T1.PV06_VALMAX  
                           WHEN T1.PV06_DESCTOMAX > 0 THEN '#'||T1.PV06_DESCTOMIN||'#'||T1.PV06_DESCTOMAX 
                       END ,
                        COUNT(1) AS N_OCORRENCIAS, 
       COUNT(DISTINCT T1.PV06_POLITICA) AS N_POLITICAS
  FROM MERCANET_PRD.MPV06 T1,
       MERCANET_PRD.DB_CPO_ATRIB T2
WHERE T1.PV06_TIPO = 'A'
  AND T1.PV06_POLITICA = T2.DB_CPO_CODIGO
  AND T1.PV06_IDREGRA = T2.DB_CPO_RES_PAI
GROUP BY T1.PV06_IDENT||CASE WHEN T1.PV06_PRAZOMAX > 0 THEN '#'||T1.PV06_PRAZOMIN||'#'||T1.PV06_PRAZOMAX
                        WHEN T1.PV06_QTDEMAX > 0 THEN  '#'||T1.PV06_QTDEMIN||'#'||T1.PV06_QTDEMAX
                        WHEN T1.PV06_VALMAX > 0 THEN '#'||T1.PV06_VALMIN||'#'||T1.PV06_VALMAX  
                        WHEN T1.PV06_DESCTOMAX > 0 THEN '#'||T1.PV06_DESCTOMIN||'#'||T1.PV06_DESCTOMAX END 
 HAVING COUNT(1) > 1 AND COUNT(DISTINCT T2.DB_CPO_TAGATRIB) = 1 AND COUNT(DISTINCT T1.PV06_POLITICA) = 1  */

/*SELECT PV06_SEQ, 
       PV06_POLITICA, 
       PV06_IDENT, 
       PV06_IDREGRA, 
       DB_CPO_TAGATRIB, 
       DB_CPO_VALORINF
  FROM MERCANET_PRD.MPV06, 
       MERCANET_PRD.DB_CPO_ATRIB
 WHERE PV06_IDENT||CASE WHEN PV06_PRAZOMAX > 0 THEN '#'||PV06_PRAZOMIN||'#'||PV06_PRAZOMAX
                        WHEN PV06_QTDEMAX > 0 THEN  '#'||PV06_QTDEMIN||'#'||PV06_QTDEMAX
                        WHEN PV06_VALMAX > 0 THEN '#'||PV06_VALMIN||'#'||PV06_VALMAX  
                        WHEN PV06_DESCTOMAX > 0 THEN '#'||PV06_DESCTOMIN||'#'||PV06_DESCTOMAX END 
      = '324713#506#AA'
 AND PV06_POLITICA = DB_CPO_CODIGO
 AND PV06_IDREGRA = DB_CPO_RES_PAI*/
                          


