SELECT EDILD.DB_EDILD_NOMEARQ  AS "ARQ IMPORTADO",
       EDIP.DB_EDIP_LOTE       AS "LOTE MERCANET",
       EDIP.DB_EDIP_PEDMERC    AS "PEDIDO MERCANET",
       PED.DB_PED_NRO_ORIG     AS "PEDIDO JDE",
       PED.DB_PED_CLIENTE      AS "COD CLIENTE",
       EDIP.DB_EDIP_COMPRADOR  AS "CNPJ CLIENTE",
       CLI.DB_CLI_NOME         AS "RAZAO SOCIAL",
       PEDI.DB_PEDI_PRODUTO    AS "COD PRODUTO",
       EDII.DB_EDII_PRODUTO    AS "EAN PRODUTO",
       PEDI.DB_PEDI_QTDE_SOLIC AS "QTDE SOLICITADA",
       PEDI.DB_PEDI_QTDE_ATEND AS "QTDE ATENDIDA",
       PEDI.DB_PEDI_QTDE_CANC  AS "QTDE NÃO ATENDIDA",
       EDIP.DB_EDIP_PROJETO    AS "CODIGO PROJETO",
       LAB.DB_LAB_DESCRICAO    AS "FORNECEDOR",
       EMP.DB_TBEMP_NOME       AS "FILIAL DE VENDA"
  FROM DB_EDI_LOTE_DISTR  EDILD,
       DB_EDI_PEDIDO      EDIP,
       DB_EDI_PEDPROD     EDII,
       DB_PEDIDO_DISTR    PEDT,
       DB_PEDIDO_DISTR_IT PDIT,
       DB_PEDIDO          PED,
       DB_PEDIDO_PROD     PEDI,
       DB_CLIENTE         CLI,
       DB_LABORATORIO     LAB,
       DB_TB_EMPRESA      EMP
 WHERE EDILD.DB_EDILD_SEQ      = EDIP.DB_EDIP_LOTE
   AND EDILD.DB_EDILD_DISTR    = EDIP.DB_EDIP_VAN
   AND EDIP.DB_EDIP_PEDMERC    = PEDT.DB_PEDT_PEDIDO
   AND PEDT.DB_PEDT_PEDIDO     = PED.DB_PED_NRO
   AND EDIP.DB_EDIP_PEDMERC    = PED.DB_PED_NRO
   AND EDIP.DB_EDIP_COMPRADOR  = EDII.DB_EDII_COMPRADOR
   AND EDIP.DB_EDIP_NRO        = EDII.DB_EDII_NRO
   AND PEDT.DB_PEDT_PEDIDO     = PDIT.DB_PDIT_PEDIDO
   AND EDII.DB_EDII_PEDMERC    = PDIT.DB_PDIT_PEDIDO
   AND EDII.DB_EDII_SEQ        = PDIT.DB_PDIT_EDII_SEQ
   AND PED.DB_PED_NRO          = PEDI.DB_PEDI_PEDIDO
   AND PDIT.DB_PDIT_PEDIDO     = PEDI.DB_PEDI_PEDIDO
   AND PDIT.DB_PDIT_PRODUTO    = PEDI.DB_PEDI_PRODUTO
   AND PED.DB_PED_CLIENTE      = CLI.DB_CLI_CODIGO
   AND EDIP.DB_EDIP_LABCOD     = LAB.DB_LAB_CODIGO
   AND PED.DB_PED_SITUACAO     IN (0, 2)
   AND PED.DB_PED_SITCORP      IN (0, 3, 4)
   AND PEDI.DB_PEDI_QTDE_ATEND > 0 
   AND PED.DB_PED_EMPRESA      = EMP.DB_TBEMP_CODIGO
   AND NOT EXISTS
 (SELECT *
          FROM DB_NOTA_FISCAL NF
         WHERE PED.DB_PED_NRO_ORIG = NF.DB_NOTA_PED_ORIG
           AND PED.DB_PED_NRO      = NF.DB_NOTA_PED_MERC
           AND PED.DB_PED_CLIENTE  = NF.DB_NOTA_CLIENTE)
   AND EDIP.DB_EDIP_VAN      = 508   -- CRIAR FILTRO DE VAN
-- AND EDIP.DB_EDIP_PEDMERC    =     -- CRIAR FILTRO DE PEDIDO
   AND EDIP.DB_EDIP_LOTE       = 84101 --> 84075
-- AND EDIP.DB_EDIP_OBS1       =     -- CRIAR FILTRO DE LOTE SEVEN
-- AND EDIP.DB_EDIP_CLIENTE    =     -- CRIAR FILTRO DE CNPJ DE CLIENTE
-- AND EDIP.DB_PED_CLIENTE     =     -- CRIAR FILTRO DE CODIGO DO CLIENTE
-- AND EDII.DB_EDII_PRODUTO    =     -- CRIAR FILTRO DE CODIGO DE BARRAS DO PRODUTO
-- AND PEDI.DB_PEDI_PRODUTO    =     -- CRIAR FILTRO DE CODIGO DO PRODUTO 
   AND DB_EDILD_DATA BETWEEN TO_DATE('24/05/2012 00:00:00', 'DD/MM/YYYY HH24:MI:SS') AND -- CRIAR FILTRO DE DATA DA IMPORTAÇÃO DO ARQUIVO 
                             TO_DATE('05/06/2012 23:59:59', 'DD/MM/YYYY HH24:MI:SS')                          

 ORDER BY EDIP.DB_EDIP_LOTE, EDIP.DB_EDIP_PEDMERC
