-- DEVE-SE ESTAR NO AMBIENTE QA PARA FAZER AS ATUALIZAÇÕES



-- PRIMEIRA PARTE : APAGAR OS DADOS DAS TABELAS DE PD 



DELETE FROM MERCANET_PRD.DB_EDI_LARQUIVO WHERE DB_EDIA_CODIGO LIKE '%SEVEN%';


DELETE FROM MERCANET_PRD.DB_EDI_LREGISTRO WHERE DB_EDIR_CODIGO LIKE '%SEVEN%'; 


DELETE FROM MERCANET_PRD.DB_EDI_LREGSAI WHERE DB_EDIS_CODIGO LIKE '%SEVEN%';


DELETE FROM MERCANET_PRD.MEM01  WHERE EM01_CODIGO = '508';


DELETE FROM MERCANET_PRD.MEM03 WHERE EM03_DISTR = '508'; 


DELETE FROM MERCANET_PRD.MEM04 WHERE EM04_DISTR = '508';


DELETE FROM MERCANET_PRD.MEM05 WHERE EM05_DISTR = '508';


DELETE FROM MERCANET_PRD.MEM06 WHERE EM06_DISTR = '508'; 


DELETE FROM MERCANET_PRD.MEM07 WHERE EM07_DISTR = '508'; 


DELETE FROM MERCANET_PRD.MEM08 WHERE EM08_DISTR = '508'; -- SOMENTE PARA A SEVEN PDV 
 

DELETE FROM MERCANET_PRD.DB_TB_REPRES WHERE DB_TBREP_CODIGO  = 508;

--COMMIT ; 



-- SEGUNDA PARTE : INSERIR OS DADOS DE QA EM PD

INSERT INTO MERCANET_PRD.DB_EDI_LARQUIVO
  SELECT * FROM DB_EDI_LARQUIVO WHERE DB_EDIA_CODIGO LIKE '%SEVEN%';
  
  
INSERT INTO MERCANET_PRD.DB_EDI_LREGISTRO
  SELECT * FROM DB_EDI_LREGISTRO  WHERE DB_EDIR_CODIGO LIKE '%SEVEN%'; 


INSERT INTO MERCANET_PRD.DB_EDI_LREGSAI
  SELECT * FROM DB_EDI_LREGSAI  WHERE DB_EDIS_CODIGO LIKE '%SEVEN%';


INSERT INTO MERCANET_PRD.MEM01
  SELECT * FROM MEM01 WHERE EM01_CODIGO = '508'; 


INSERT INTO MERCANET_PRD.MEM03
  SELECT * FROM MEM03 WHERE EM03_DISTR = '508'; 


INSERT INTO MERCANET_PRD.MEM04
  SELECT * FROM MEM04 WHERE EM04_DISTR = '508'; 


INSERT INTO MERCANET_PRD.MEM05
  SELECT * FROM MEM05 WHERE EM05_DISTR = '508'; 


INSERT INTO MERCANET_PRD.MEM06
  SELECT * FROM MEM06  WHERE EM06_DISTR = '508';  
  
  
INSERT INTO MERCANET_PRD.MEM07
  SELECT * FROM MEM07 WHERE EM07_DISTR = '508';   


INSERT INTO MERCANET_PRD.MEM08
  SELECT * FROM MEM08  WHERE EM08_DISTR = '508'; 

  
INSERT INTO MERCANET_PRD.DB_TB_REPRES
  SELECT * FROM DB_TB_REPRES  WHERE DB_TBREP_CODIGO  = 508;
  
  
-- TERCEIRA PARTE: Inserir campos novos (que não existem em PD)

insert into mercanet_prd.db_edi_lcposai
  select *
    from db_edi_lcposai
   where db_edic_codigo not in
         (select db_edic_codigo from mercanet_prd.db_edi_lcposai)
         
         
-- QUARTA PARTE : ENTRAR NA APLICAÇÃO PARA CONFERIR SE AS ATUALIZAÇÕES FORAM FEITAS CORRETAMENTE
   Alterar Cadastro de Operador Logistico, Aba "Diretório" apontando para a máquina de PD


-- Caso necessario: Compara o tipo e a expressao em QA e PD. 

select qa.db_edic_codigo    Campo,
       qa.db_edic_tipo      QATipo,
       pd.db_edic_tipo      PDTipo,
       qa.db_edic_expressao QAExpressao,
       pd.db_edic_expressao PDExpressao
  from mercanet_qa.db_edi_lcposai qa, mercanet_prd.db_edi_lcposai pd
 where qa.db_edic_codigo = pd.db_edic_codigo
   and (qa.db_edic_tipo != pd.db_edic_tipo or
       qa.db_edic_expressao != pd.db_edic_expressao)
  
  
  
