SELECT '''' ||TRIM(SBLITM) ||''',', IBITM ||',' ,SBLITM,   SAOORN , IBVEND  , ABALPH , IVCITM 
  FROM PRODDTA.F5547011 A, PRODDTA.F5547012 B , PRODDTA.F4102 C , PRODDTA.F0101 D , PRODDTA.F4104 E 
 WHERE SAOORN IN ('27', '23', '24', '28', '30', '31', '33')
   AND SAUPMJ > 112001
   AND SAUKID = SBUKID
   AND SBLITM IS NOT NULL
   AND SBLITM != '                         ' 
   AND SBLITM  = IBLITM 
   AND IBVEND = ABAN8
   AND IVITM   = IBITM 
   AND IVXRT = 'VN'
   AND IVAN8 = IBVEND 
GROUP BY SBLITM,IBITM, SAOORN , IBVEND , ABALPH, IVCITM
 
 