select db_edip_nro,
       
       (select db_edild_data
          from mercanet_prd.db_edi_lote_distr
         where db_edild_seq = db_edip_LOTE) "DATA/HORA CAPTAÇÃO",
       to_date((select TO_CHAR(substr(SUB.DB_EDILD_CONTEUDO_REG4,
                                     instr(SUB.DB_EDILD_CONTEUDO_REG4,
                                           ';',
                                           1,
                                           3) + 1,
                                     (instr(SUB.DB_EDILD_CONTEUDO_REG4,
                                            ';',
                                            1,
                                            2)) -
                                     (instr(SUB.DB_EDILD_CONTEUDO_REG4,
                                            ';',
                                            1,
                                            1) + 2))) DATAHORA
                 from (select substr(DB_EDILD_CONTEUDO,
                                     instr(DB_EDILD_CONTEUDO,
                                           chr(10) || '1',
                                           1,
                                           1) + 1,
                                     (instr(DB_EDILD_CONTEUDO,
                                            chr(10),
                                            instr(DB_EDILD_CONTEUDO,
                                                  chr(10) || '1',
                                                  1,
                                                  1) + 1,
                                            1) - 1) -
                                     (instr(DB_EDILD_CONTEUDO,
                                            chr(10) || '1',
                                            1,
                                            1) + 1)) DB_EDILD_CONTEUDO_REG4,
                              DB_EDILD_SEQ
                         from mercanet_prd.DB_EDI_LOTE_DISTR) SUB
                where DB_EDIP_LOTE = SUB.DB_EDILD_SEQ),
               'dd/mm/yyyy hh24:mi') "DATA/HORA VENCIMENTO",
       db_edip_dtenvio "DATA/HORA RESPOSTA",
       case
         when to_date((select TO_CHAR(substr(SUB.DB_EDILD_CONTEUDO_REG4,
                                            instr(SUB.DB_EDILD_CONTEUDO_REG4,
                                                  ';',
                                                  1,
                                                  3) + 1,
                                            (instr(SUB.DB_EDILD_CONTEUDO_REG4,
                                                   ';',
                                                   1,
                                                   2)) -
                                            (instr(SUB.DB_EDILD_CONTEUDO_REG4,
                                                   ';',
                                                   1,
                                                   1) + 2))) DATAHORA
                        from (select substr(DB_EDILD_CONTEUDO,
                                            instr(DB_EDILD_CONTEUDO,
                                                  chr(10) || '1',
                                                  1,
                                                  1) + 1,
                                            (instr(DB_EDILD_CONTEUDO,
                                                   chr(10),
                                                   instr(DB_EDILD_CONTEUDO,
                                                         chr(10) || '1',
                                                         1,
                                                         1) + 1,
                                                   1) - 1) -
                                            (instr(DB_EDILD_CONTEUDO,
                                                   chr(10) || '1',
                                                   1,
                                                   1) + 1)) DB_EDILD_CONTEUDO_REG4,
                                     DB_EDILD_SEQ
                                from mercanet_prd.DB_EDI_LOTE_DISTR) SUB
                       where DB_EDIP_LOTE = SUB.DB_EDILD_SEQ),
                      'dd/mm/yyyy hh24:mi') < db_edip_dtenvio then
          'ATRASO NO RETORNO'
         else
          case
            when to_date((select TO_CHAR(substr(SUB.DB_EDILD_CONTEUDO_REG4,
                                               instr(SUB.DB_EDILD_CONTEUDO_REG4,
                                                     ';',
                                                     1,
                                                     3) + 1,
                                               (instr(SUB.DB_EDILD_CONTEUDO_REG4,
                                                      ';',
                                                      1,
                                                      2)) -
                                               (instr(SUB.DB_EDILD_CONTEUDO_REG4,
                                                      ';',
                                                      1,
                                                      1) + 2))) DATAHORA
                           from (select substr(DB_EDILD_CONTEUDO,
                                               instr(DB_EDILD_CONTEUDO,
                                                     chr(10) || '1',
                                                     1,
                                                     1) + 1,
                                               (instr(DB_EDILD_CONTEUDO,
                                                      chr(10),
                                                      instr(DB_EDILD_CONTEUDO,
                                                            chr(10) || '1',
                                                            1,
                                                            1) + 1,
                                                      1) - 1) -
                                               (instr(DB_EDILD_CONTEUDO,
                                                      chr(10) || '1',
                                                      1,
                                                      1) + 1)) DB_EDILD_CONTEUDO_REG4,
                                        DB_EDILD_SEQ
                                   from mercanet_prd.DB_EDI_LOTE_DISTR) SUB
                          where DB_EDIP_LOTE = SUB.DB_EDILD_SEQ),
                         'dd/mm/yyyy hh24:mi') IS NULL then
             'NÃO RESPONDIDO'
            else
             'RESPOSTA OK'
          end
       end "ANALISE"

  from mercanet_prd.db_edi_pedido
 where db_edip_nro in ('41025',
                       '41033',
                       '41058',
                       '41072',
                       '41103',
                       '41107',
                       '41124',
                       '41126',
                       '41129',
                       '41134',
                       '41138',
                       '41142',
                       '41198',
                       '41204',
                       '41235',
                       '41279',
                       '41281',
                       '41296',
                       '41318',
                       '41323',
                       '41332',
                       '41335',
                       '41336',
                       '41356',
                       '41372',
                       '41431',
                       '41469',
                       '41471',
                       '41473',
                       '41474',
                       '41475',
                       '41477',
                       '41478',
                       '41481',
                       '41482',
                       '41485',
                       '41487',
                       '41489',
                       '41491',
                       '41492',
                       '41494',
                       '41495',
                       '41499',
                       '41503',
                       '41505',
                       '41567',
                       '41602',
                       '41605',
                       '41611',
                       '41637',
                       '41696',
                       '41703',
                       '41715',
                       '41721',
                       '41764',
                       '41769',
                       '41786',
                       '41803',
                       '41845',
                       '41885',
                       '41924',
                       '41932')
