SELECT ELD.DB_EDILD_DISTR     "VAN",
       ELD.DB_EDILD_NOMEARQ   "NOME DO ARQUIVO",
       PED.DB_PED_NRO         "NºPEDIDO MERCANET",
       EPED.DB_EDIP_COMPRADOR "CNPJ DO CLIENTE",
       PED.DB_PED_CLIENTE     "CODIGO DO CLIENTE",
       CLIA.DB_CLIA_VALOR     "COND.ESPEC.PERF",
       EPED.DB_EDIP_CLIENTE   "ORIGEM",
       CLI.DB_CLI_ESTADO      "DESTINO"
  FROM DB_EDI_LOTE_DISTR ELD,
       DB_EDI_PEDIDO     EPED,
       DB_PEDIDO         PED,
       DB_TB_EMPRESA     EMP,
       DB_CLIENTE        CLI,
       DB_CLIENTE_ATRIB  CLIA
 WHERE EPED.DB_EDIP_LOTE      = ELD.DB_EDILD_SEQ
   AND PED.DB_PED_NRO         = EPED.DB_EDIP_PEDMERC
   AND PED.DB_PED_EMPRESA     = EMP.DB_TBEMP_CODIGO
   AND PED.DB_PED_CLIENTE     = CLI.DB_CLI_CODIGO
   AND EPED.DB_EDIP_COMPRADOR = CLI.DB_CLI_CGCMF
   AND CLI.DB_CLI_CODIGO      = CLIA.DB_CLIA_CODIGO
   AND CLIA.DB_CLIA_ATRIB     = 1015
   AND CLIA.DB_CLIA_VALOR     != 'ANN'
   AND ELD.DB_EDILD_DATA      > '&"A PARTIR DA DATA"'
   AND NOT EXISTS
 (SELECT *
          FROM MERCANET_QA.DB_EDI_LOTE_DISTR QAELD
         WHERE ELD.DB_EDILD_NOMEARQ = QAELD.DB_EDILD_NOMEARQ)