SELECT ABAN8,ABALPH,ABAT1,ABSIC,AIAC16,AIHOLD,AIAC15,AIAC04,AIAC12,AIAC18,AIAC20,AIAC10,AIAC29

  FROM PRODDTA.F0101 A, PRODDTA.F03012 B
 WHERE A.ABAN8 = B.AIAN8
   AND B.AIHOLD = ' '
   AND A.ABAT1 = 'C'
   AND A.ABSIC = 'DIF'
   AND B.AIAC16 = 'SP' -- E TAMBEM -->>, 'GO' , 'MG', 'RJ'
   --AND B.AIAC15 <>'ANN' -- E TAMBEM = 'ANN'
   --AND B.AIAC04 <>'AA' -- E TAMBEM = 'AA'
  --AND B.AIAC12 = '007' -- E TAMBEM = 'AA'
   --AND B.AIAC18 ='AA'-- E TAMBEM  ,    = 'PEF' 'PSI'
   --AND B.AIAC20 = 'DP1' -- E TAMBEM = 'AA'
   --AND B.AIAC10 = 'AA'-- E TAMBEM = 'EF4'
   AND B.AIAC29 = 'DL'  -- E TAMBEM  ,= 'AA''DI'