SELECT DISTINCT A.DB_EDILD_DISTR    "VAN",
                A.DB_EDILD_NOMEARQ  "NOME DO ARQUIVO",
                D.DB_PED_NRO        "NºPEDIDO MERCANET",
                B.DB_EDIP_COMPRADOR "CNPJ DO CLIENTE",
                D.DB_PED_CLIENTE    "CODIGO DO CLIENTE",
                B.DB_EDIP_CLIENTE   "ORIGEM",
                G.DB_CLI_ESTADO     "DESTINO",
                E.DB_PRDEMB_PRODUTO "CODIGO PRODUTO",
                F.DB_PRODA_VALOR    "TIPO DE PRODUTO"
  FROM DB_EDI_LOTE_DISTR A,
       DB_EDI_PEDIDO     B,
       DB_EDI_PEDPROD    C,
       DB_PEDIDO         D,
       DB_PRODUTO_EMBAL  E,
       DB_PRODUTO_ATRIB  F,
       DB_CLIENTE        G
 WHERE A.DB_EDILD_SEQ        = B.DB_EDIP_LOTE
   AND B.DB_EDIP_COMPRADOR   = C.DB_EDII_COMPRADOR
   AND B.DB_EDIP_NRO         = C.DB_EDII_NRO
   AND B.DB_EDIP_PEDMERC     = D.DB_PED_NRO
   AND E.DB_PRDEMB_CODBARRA  = C.DB_EDII_PRODUTO
   AND E.DB_PRDEMB_PRODUTO   = F.DB_PRODA_CODIGO
   AND F.DB_PRODA_ATRIB      = 2014
   AND F.DB_PRODA_VALOR      = 'MGN'
   AND G.DB_CLI_CGCMF        = B.DB_EDIP_COMPRADOR
   AND A.DB_EDILD_DATA       > '&"A PARTIR DA DATA"'
   AND NOT EXISTS
 (SELECT *
          FROM MERCANET_QA.DB_EDI_LOTE_DISTR QAELD
         WHERE A.DB_EDILD_NOMEARQ = QAELD.DB_EDILD_NOMEARQ)