SELECT TRIM(REPLACE(REPLACE(REPLACE(DM03_DESCRICAO,'IMPORT FTP - ',''),'-',''),'  ',' ')) AS DESCRICAO,
        SUBSTR(DM03_CONFIGSTRING,15,INSTR(DM03_CONFIGSTRING,'' ,1,1)-15) AS HOST, 
       SUBSTR(DM03_CONFIGSTRING,INSTR(DM03_CONFIGSTRING,'' ,1,1)+1,INSTR(DM03_CONFIGSTRING,'' ,1,2)-INSTR(DM03_CONFIGSTRING,'' ,1,1)-1) AS USUARIO, 
       SUBSTR(DM03_CONFIGSTRING,INSTR(DM03_CONFIGSTRING,'' ,1,2)+1,INSTR(DM03_CONFIGSTRING,'' ,1,3)-INSTR(DM03_CONFIGSTRING,'' ,1,2)-1) AS SENHA,
       SUBSTR(DM03_CONFIGSTRING,INSTR(DM03_CONFIGSTRING,'' ,1,3)+1,INSTR(DM03_CONFIGSTRING,'' ,1,4)-INSTR(DM03_CONFIGSTRING,'' ,1,3)-1) AS PASTA_REMOTA,
       SUBSTR(DM03_CONFIGSTRING,INSTR(DM03_CONFIGSTRING,'' ,1,4)+1,INSTR(DM03_CONFIGSTRING,'' ,1,5)-INSTR(DM03_CONFIGSTRING,'' ,1,4)-1) AS PASTA_LOCAL,

       DM03_CONFIGSTRING
       /*'#'||'['
       ||TRIM(REPLACE(REPLACE(REPLACE(DM03_DESCRICAO,'IMPORT FTP - ',''),'-',''),'  ',' '))
       ||']'
       ||CHR(13)
       ||'HOST='
       ||SUBSTR(DM03_CONFIGSTRING,15,INSTR(DM03_CONFIGSTRING,'' ,1,1)-15)
       ||CHR(13)
       ||'UID='
       ||SUBSTR(DM03_CONFIGSTRING,INSTR(DM03_CONFIGSTRING,'' ,1,1)+1,INSTR(DM03_CONFIGSTRING,'' ,1,2)-INSTR(DM03_CONFIGSTRING,'' ,1,1)-1)
       ||CHR(13)
       ||'PWD='
       --||SUBSTR(DM03_CONFIGSTRING,INSTR(DM03_CONFIGSTRING,'' ,1,2)+1,INSTR(DM03_CONFIGSTRING,'' ,1,3)-INSTR(DM03_CONFIGSTRING,'' ,1,2)-1)
       ||CHR(13)
       ||'PASVMODE=0'
       ||CHR(13)
       ||'TIMEOFFSET=0'||'#'*/
 
 FROM MERCANET_PRD.MDM03 
WHERE DM03_GRUPO LIKE '%ESTOQUE%'
--AND DM03_DESCRICAO LIKE '%IMPO%'
