SELECT DB_EDIP_COMPRADOR, 
       DB_EDIP_NRO, 
       DB_EDIP_PEDMERC, 
       DB_EDILE_EDIA_CODI,
       DB_EDILE_ID,
       DB_EDIP_DTENVIO,
       DB_EDILE_ARQUIVO, 
       DB_EDILE_CONTEUDO
  FROM MERCANET_PRD.DB_EDI_PEDIDO, MERCANET_PRD.DB_EDI_LOG_EXP
 WHERE DB_EDIP_COMPRADOR = DB_EDILE_EDIP_COMP
   AND DB_EDIP_NRO = DB_EDILE_EDIP_NRO
   AND DB_EDIP_NRO IN ('0000003644')
   --AND DB_EDILE_EDIA_CODI = 'FIDELIZE_PED'
 ORDER BY DB_EDIP_COMPRADOR ,DB_EDIP_NRO , DB_EDILE_EDIA_CODI
