--LEVANTAMENTO SEVEN PDV
SELECT
'DE 26/JUNHO a 19/JULHO(15:00)' AS "DATA",
'ANTES DA MUDANÇA DE QUEBRA DE PEDIDOS' AS "CENARIO",
 (SELECT COUNT(DISTINCT DB_EDILD_NOMEARQ)
    FROM MERCANET_PRD.DB_EDI_PEDIDO,
         MERCANET_PRD.DB_EDI_PEDPROD,
         MERCANET_PRD.DB_EDI_LOTE_DISTR
   WHERE DB_EDIP_VAN = EDILD.DB_EDILD_SEQ
     AND DB_EDILD_SEQ = DB_EDIP_LOTE
     AND DB_EDILD_DATA BETWEEN
         TO_DATE('26/06/2012 00:00:00', 'DD/MM/YYYY HH24:MI:SS') AND
         TO_DATE('19/07/2012 15:00:00', 'DD/MM/YYYY HH24:MI:SS')
     AND DB_EDIP_NRO = DB_EDII_NRO
     AND DB_EDIP_COMPRADOR = DB_EDII_COMPRADOR) "NºARQs IMPORT ANTES da MUDANÇA" ,
     
 (SELECT COUNT(1)
    FROM MERCANET_PRD.DB_EDI_PEDIDO,
         MERCANET_PRD.DB_EDI_PEDPROD,
         MERCANET_PRD.DB_EDI_LOTE_DISTR
   WHERE DB_EDIP_VAN = EDILD.DB_EDILD_SEQ
     AND DB_EDILD_SEQ = DB_EDIP_LOTE
     AND DB_EDILD_DATA BETWEEN
         TO_DATE('26/06/2012 00:00:00', 'DD/MM/YYYY HH24:MI:SS') AND
         TO_DATE('19/07/2012 15:00:00', 'DD/MM/YYYY HH24:MI:SS')
     AND DB_EDIP_NRO = DB_EDII_NRO
     AND DB_EDIP_COMPRADOR = DB_EDII_COMPRADOR)  "Nº DE LINHAS DOS ARQUIVOS",
  
 (SELECT COUNT(DISTINCT DB_EDIP_NRO)
    FROM MERCANET_PRD.DB_EDI_PEDIDO,
         MERCANET_PRD.DB_EDI_LOTE_DISTR
   WHERE DB_EDIP_VAN = EDILD.DB_EDILD_SEQ
     AND DB_EDILD_SEQ = DB_EDIP_LOTE
     AND DB_EDILD_DATA BETWEEN
         TO_DATE('26/06/2012 00:00:00', 'DD/MM/YYYY HH24:MI:SS') AND
         TO_DATE('19/07/2012 15:00:00', 'DD/MM/YYYY HH24:MI:SS')) "Nº DE PEDIDOS GERADOS",
   
  (SELECT COUNT(DISTINCT DB_PED_NRO)
    FROM MERCANET_PRD.DB_EDI_LOTE_DISTR,
         MERCANET_PRD.DB_EDI_PEDIDO,
         MERCANET_PRD.DB_PEDIDO
   WHERE DB_EDIP_VAN = EDILD.DB_EDILD_SEQ
     AND DB_EDILD_SEQ = DB_EDIP_LOTE
     AND DB_EDILD_DATA BETWEEN
         TO_DATE('26/06/2012 00:00:00', 'DD/MM/YYYY HH24:MI:SS') AND
         TO_DATE('19/07/2012 23:00:00', 'DD/MM/YYYY HH24:MI:SS')
    AND DB_EDIP_PEDMERC = DB_PED_NRO
    AND DB_PED_SITUACAO IN (0,2,4)
    AND DB_PED_SITCORP IN ('0','3','4'))  "Nº DE PEDIDOS FATURADOS",
     
  (SELECT COUNT(DISTINCT DB_PED_NRO)
    FROM MERCANET_PRD.DB_EDI_LOTE_DISTR,
         MERCANET_PRD.DB_EDI_PEDIDO,
         MERCANET_PRD.DB_PEDIDO
   WHERE DB_EDIP_VAN = EDILD.DB_EDILD_SEQ
     AND DB_EDILD_SEQ = DB_EDIP_LOTE
     AND DB_EDILD_DATA BETWEEN
         TO_DATE('26/06/2012 00:00:00', 'DD/MM/YYYY HH24:MI:SS') AND
         TO_DATE('19/07/2012 23:00:00', 'DD/MM/YYYY HH24:MI:SS')
    AND DB_EDIP_PEDMERC = DB_PED_NRO
    AND DB_PED_SITCORP = '1') "Nº DE PEDIDOS BLOQ. VAL.MINIMO"          
  
     
FROM MERCANET_PRD.DB_EDI_LOTE_DISTR EDILD
WHERE DB_EDILD_SEQ = 508
UNION
SELECT
'DE 26/JULHO a 19/AGOSTO' AS "DATA",
'APÓS A MUDANÇA DE QUEBRA DE PEDIDOS' AS "CENARIO",
 (SELECT COUNT(DISTINCT DB_EDILD_NOMEARQ)
    FROM MERCANET_PRD.DB_EDI_PEDIDO,
         MERCANET_PRD.DB_EDI_PEDPROD,
         MERCANET_PRD.DB_EDI_LOTE_DISTR
   WHERE DB_EDIP_VAN = EDILD.DB_EDILD_SEQ
     AND DB_EDILD_SEQ = DB_EDIP_LOTE
     AND DB_EDILD_DATA BETWEEN
         TO_DATE('26/07/2012 00:00:00', 'DD/MM/YYYY HH24:MI:SS') AND
         TO_DATE('19/08/2012 23:00:00', 'DD/MM/YYYY HH24:MI:SS')
     AND DB_EDIP_NRO = DB_EDII_NRO
     AND DB_EDIP_COMPRADOR = DB_EDII_COMPRADOR) "NºARQs IMPORT ANTES da MUDANÇA" ,
     
 (SELECT COUNT(1)
    FROM MERCANET_PRD.DB_EDI_PEDIDO,
         MERCANET_PRD.DB_EDI_PEDPROD,
         MERCANET_PRD.DB_EDI_LOTE_DISTR
   WHERE DB_EDIP_VAN = EDILD.DB_EDILD_SEQ
     AND DB_EDILD_SEQ = DB_EDIP_LOTE
     AND DB_EDILD_DATA BETWEEN
         TO_DATE('26/07/2012 00:00:00', 'DD/MM/YYYY HH24:MI:SS') AND
         TO_DATE('19/08/2012 23:00:00', 'DD/MM/YYYY HH24:MI:SS')
     AND DB_EDIP_NRO = DB_EDII_NRO
     AND DB_EDIP_COMPRADOR = DB_EDII_COMPRADOR) "Nº DE LINHAS DOS ARQUIVOS",
  
 (SELECT COUNT(DISTINCT DB_EDIP_NRO)
    FROM MERCANET_PRD.DB_EDI_PEDIDO,
         MERCANET_PRD.DB_EDI_LOTE_DISTR
   WHERE DB_EDIP_VAN = EDILD.DB_EDILD_SEQ
     AND DB_EDILD_SEQ = DB_EDIP_LOTE
     AND DB_EDILD_DATA BETWEEN
          TO_DATE('26/07/2012 00:00:00', 'DD/MM/YYYY HH24:MI:SS') AND
         TO_DATE('19/08/2012 23:00:00', 'DD/MM/YYYY HH24:MI:SS')) "Nº DE PEDIDOS GERADOS",
         
  
  (SELECT COUNT(DISTINCT DB_PED_NRO)
    FROM MERCANET_PRD.DB_EDI_LOTE_DISTR,
         MERCANET_PRD.DB_EDI_PEDIDO,
         MERCANET_PRD.DB_PEDIDO
   WHERE DB_EDIP_VAN = EDILD.DB_EDILD_SEQ
     AND DB_EDILD_SEQ = DB_EDIP_LOTE
     AND DB_EDILD_DATA BETWEEN
          TO_DATE('26/07/2012 00:00:00', 'DD/MM/YYYY HH24:MI:SS') AND
         TO_DATE('19/08/2012 23:00:00', 'DD/MM/YYYY HH24:MI:SS')
    AND DB_EDIP_PEDMERC = DB_PED_NRO
    AND DB_PED_SITUACAO IN (0,2,4)
    AND DB_PED_SITCORP IN ('0','3','4')) "Nº DE PEDIDOS FATURADOS",
     
  (SELECT COUNT(DISTINCT DB_PED_NRO)
    FROM MERCANET_PRD.DB_EDI_LOTE_DISTR,
         MERCANET_PRD.DB_EDI_PEDIDO,
         MERCANET_PRD.DB_PEDIDO 
   WHERE DB_EDIP_VAN = EDILD.DB_EDILD_SEQ
     AND DB_EDILD_SEQ = DB_EDIP_LOTE
     AND DB_EDILD_DATA BETWEEN
         TO_DATE('26/07/2012 00:00:00', 'DD/MM/YYYY HH24:MI:SS') AND
         TO_DATE('19/08/2012 23:00:00', 'DD/MM/YYYY HH24:MI:SS')
    AND DB_EDIP_PEDMERC = DB_PED_NRO
    AND DB_PED_SITCORP = '1') "Nº DE PEDIDOS BLOQ. VAL.MINIMO" 
           
FROM MERCANET_PRD.DB_EDI_LOTE_DISTR EDILD
WHERE DB_EDILD_SEQ = 508
