SELECT 'COTAÇÃO' AS " ",
       CLICOT.DB_CLI_CODIGO "Cod Cliente",
       CLICOT.DB_CLI_CGCMF "CNPJ",
       CLICOT.DB_CLI_NOME "Razão Social",
       EDIPCOT.DB_EDIP_NRO "Nro Cotacao",
       EDIPCOT.DB_EDIP_PEDMERC "Ped Mercanet",
       PEDCOT.DB_PED_NRO_ORIG "Ped JDE",
       PEDCOT.DB_PED_COND_PGTO "Cond Pgto",
       (SELECT sum(PEDICOT.DB_PEDI_PRECO_LIQ * PEDICOT.DB_PEDI_QTDE_ATEND)
          FROM MERCANET_PRD.DB_PEDIDO_PROD@DC09 PEDICOT
         WHERE PEDCOT.DB_PED_NRO = PEDICOT.DB_PEDI_PEDIDO) "Valor Cotado",
       
       'EFETIVAÇÃO' " ",
       CLIEFE.DB_CLI_CODIGO "Cod Cliente",
       CLIEFE.DB_CLI_CGCMF "CNPJ",
       CLIEFE.DB_CLI_NOME "Razão Social",
       EDIPEFE.DB_EDIP_NRO "Nro Efetivacao",
       EDIPEFE.DB_EDIP_PEDMERC "Ped Mercanet",
       PEDEFE.DB_PED_NRO_ORIG "Ped JDE",
       PEDEFE.DB_PED_COND_PGTO "Cond Pgto",
       (SELECT sum(PEDIEFE.DB_PEDI_PRECO_LIQ * PEDIEFE.DB_PEDI_QTDE_ATEND)
          FROM MERCANET_PRD.DB_PEDIDO_PROD@DC09 PEDIEFE
         WHERE PEDEFE.DB_PED_NRO = PEDIEFE.DB_PEDI_PEDIDO) "Valor Efetivado"

  FROM MERCANET_PRD.DB_EDI_PEDIDO@DC09 EDIPCOT,
       MERCANET_PRD.DB_EDI_PEDIDO@DC09 EDIPEFE,
       MERCANET_PRD.DB_PEDIDO@DC09     PEDCOT,
       MERCANET_PRD.DB_PEDIDO@DC09     PEDEFE,
       MERCANET_PRD.DB_CLIENTE@DC09    CLICOT,
       MERCANET_PRD.DB_CLIENTE@DC09    CLIEFE
 WHERE EDIPCOT.DB_EDIP_OBS1 = EDIPEFE.DB_EDIP_OBS1(+)
   AND EDIPCOT.DB_EDIP_VAN = 529
   AND EDIPEFE.DB_EDIP_VAN(+) = 530
   AND EDIPCOT.DB_EDIP_PEDMERC = PEDCOT.DB_PED_NRO(+)
   AND EDIPEFE.DB_EDIP_PEDMERC = PEDEFE.DB_PED_NRO(+)
   AND EDIPCOT.DB_EDIP_COMPRADOR = CLICOT.DB_CLI_CGCMF
   AND EDIPEFE.DB_EDIP_COMPRADOR = CLIEFE.DB_CLI_CGCMF(+)
   AND EDIPCOT.DB_EDIP_DT_EMISSAO BETWEEN
       TO_DATE('24/01/2013 00:00:00', 'DD/MM/YYYY HH24:MI:SS') AND
       TO_DATE('24/01/2013 23:59:59', 'DD/MM/YYYY HH24:MI:SS')
-- AND EDIPCOT.DB_EDIP_OBS1 IN ('40270','39991') -- digite o numero das cotações

