----ENVIO DE PEDIDOS PARA INTEGRAÇÃO DO CANAL AUTORIZADOR E GSK-OIT
-------EXECUTAR CADA PASSO DE MANEIRA DISTINTA

--PASSO 1 : DROPAR A TABELA_INTEGRACAO

--DROPAR A TABELA_INTEGRAÇÃO ANTES DE COMEÇAR O PROCESSO.

--DROP TABLE TABELA_INTEGRACAO;

--PASSO 2 : CRIAR A TABELA COM DADOS PARA INTEGRAÇÃO 
--OBS: CASO A TABLESPACE DO USUÁRIO FIQUE CHEIA, SOLICITAR AO DBA QUE AUMENTE O ESPAÇO DE SEU USUÁRIO.

CREATE TABLE TABELA_INTEGRACAO AS 
SELECT 
SDROUT AS CHAC01,
SDAN8 
     AS AN8,
NEBBRCD AS BBRCD,
(SELECT MAX(TRIM(SQ2.ABTAX))
     FROM PRODDTA.F0006 SQ1, 
          PRODDTA.F0101 SQ2
    WHERE T2.SDEMCU = SQ1.MCMCU
      AND T2.SDDOCO = T1.CCDOCO 
      AND SQ1.MCAN8 = SQ2.ABAN8) AS BCGF,
(SELECT MAX(TRIM(SQ1.ABTAX)) 
     FROM PRODDTA.F0101  SQ1
    WHERE T2.SDDOCO = T1.CCDOCO
      AND T2.SDAN8  = SQ1.ABAN8) AS BCGT,
T3.FDBNNF AS BNNF,
T3.FDBSER AS BSER,
'NS' AS DCT,
T1.CCDCTO AS DCTO,
T1.CCDOCO AS DOCO,
'P' AS EV01,
CASE WHEN T1.CCGS1A = 'GSK-OIT' 
   THEN 'P' 
  ELSE ' '
    END AS EV02,
CASE WHEN T1.CCGS1A = 'GSK-OIT' 
   THEN 'N' 
  ELSE 'S'
    END AS EV12,    
TRIM(T1.CCGS1A) AS GS1A,
T3.FDISSU AS ISSU,
T1.CCKCOO AS KCOO,
T3.FDN001 AS N001,
1 AS IHRUKID,
SDTRDJ AS TRDJ,
0 AS UKID,
(SELECT COUNT(1) 
     FROM PRODDTA.F5542099 SQ1,
          PRODDTA.F7611B   SQ2
    WHERE T1.CCDOCO = SQ1.CCDOCO
      AND T1.CCDCTO = SQ1.CCDCTO
      AND T1.CCKCOO = SQ1.CCKCOO
      AND T1.CCGS1A = SQ1.CCGS1A
      AND T1.CCFDA2 = SQ1.CCFDA2
      AND SQ1.CCDOCO = SQ2.FDDOCO
      AND SQ1.CCLITM = SQ2.FDLITM
 GROUP BY T1.CCDOCO, T1.CCDCTO, T1.CCKCOO, T1.CCGS1A, T1.CCFDA2) AS UOR2,

 -------------
 'ITENS' AS SEPARADOR,
 -------------
 SDLITM,
 (SELECT IVCITM
   FROM PRODDTA.F4104 SQ1
  WHERE SQ1.IVITM = T2.SDITM
    AND SQ1.IVXRT = 'VN'
    AND SQ1.IVDSC2 = 'E'
    AND ROWNUM = 1) AS CITM,
SUM(T2.SDUORG) AS UORG,
T3.FDLITM AS LITM,
SUM(T2.SDSOQS) AS SOQS,
SUM(T3.FDAEXP) AS AEXP,
T3.FDUPRC AS UPRC,
CASE  WHEN T1.CCCW01/100 < 0 THEN  T1.CCCW01/100 ELSE
CASE  WHEN T1.CCCW03/100 < 0 THEN  T1.CCCW03/100 ELSE
CASE  WHEN T1.CCCW05/100 < 0 THEN  T1.CCCW05/100 ELSE  0 
END END END AS "PERCENT", 
CCAN01 AS AN01,
T3.FDBIST AS BIST,
DECODE(T2.SDSRP3,'NEG','N','POS','P','0') AS FLAG, 
T2.SDPTC AS PTC,
(SELECT SQ1.CIAA10
   FROM PRODDTA.F5542095 SQ1
  WHERE SQ1.CIUKID = T1.CCUKID
    AND SQ1.CIPUKID = T1.CCPUKID
    AND SQ1.CIVEND = T2.SDVEND) AS AA10,
(SELECT DECODE(TRIM(IBSRP8), 'C', 'M', 'P', 'L', IBSRP8) 
   FROM PRODDTA.F4102 
  WHERE IBLITM = T2.SDLITM 
   AND ROWNUM = 1) AS SRP8,
'P' AS DEV01,
 CASE WHEN T1.CCGS1A = 'GSK-OIT' 
   THEN 'P' 
  ELSE ' '
    END AS DEV02,
2 AS CDUK05,
CCUKID AS CDUK06,
(SELECT PNNDTP 
  FROM PRODDTA.F0014
WHERE PNPTC = T2.SDPTC) AS NDTP ,
CCFDA2 AS AA05, 
CCUK02 AS UK07,
CCLNID AS LNID,
CASE WHEN CCCW02 < 0 THEN CCCW02 ELSE
CASE WHEN CCCW04 < 0 THEN CCCW04 ELSE
CASE WHEN CCCW06 < 0 THEN CCCW06 ELSE 0
END END END AS DCPC
  
FROM PRODDTA.F5542099 T1, 
     PRODDTA.F42119 T2,
     PRODDTA.F7611B T3,
     PRODDTA.F55NFE03 T4
 WHERE TO_DATE(TO_CHAR(T1.CCUPMJ + 1900000), 'YYYYDDD') > SYSDATE - 10
   AND T1.CCEV03 = 'S'
   AND T1.CCDOCO = T2.SDDOCO 
   AND T1.CCSEC = '0'
   AND TRUNC(T1.CCLNID/1000) = TRUNC(T2.SDLNID/1000)   
   AND T2.SDLTTR <=620
   AND T2.SDLNTY = 'BS'
   AND T2.SDDOCO = T3.FDDOCO
   AND T2.SDLNID = T3.FDLNID
   AND T3.FDBNNF = T4.NEBNNF
   AND T3.FDBSER = T4.NEBSER
   AND T3.FDN001 = T4.NEN001
   AND T3.FDDCT = T4.NEDCT
   AND T4.NEBBRCD NOT IN ('                                            ')
 GROUP BY T1.CCDOCO,T1.CCDCTO,T1.CCKCOO,T1.CCGS1A,T1.CCFDA2,T1.CCCW01,T1.CCCW02,T1.CCCW03,T1.CCCW04,T1.CCCW05,T1.CCCW06,T1.CCAN01,
         T1.CCPUKID,T1.CCUKID,T2.SDVEND,T1.CCUK02,T1.CCLNID,T2.SDDOCO,T2.SDROUT,T2.SDAN8,T2.SDEMCU,T2.SDTRDJ,T2.SDLITM,T2.SDITM,
         T2.SDSRP3,T2.SDPTC ,T3.FDBNNF,T3.FDBSER,T3.FDISSU,T3.FDN001,T3.FDBIST,T3.FDLITM,T3.FDUPRC,T4.NEBBRCD
ORDER BY T1.CCDOCO, T1.CCDCTO, T1.CCKCOO, T1.CCGS1A, T1.CCFDA2,T1.CCLNID;

--PASSO 3 : ATUALIZA A TABELA COM O UKID 
------------------------------------------------------------------------------------------

DECLARE 
V_UKID NUMBER := 0; 
V_COUNT NUMBER :=0;
LAST_KEY VARCHAR2(100):= ' ';

BEGIN 
  
SELECT UKUKID INTO V_UKID FROM PRODDTA.F00022 WHERE UKOBNM = 'F554201C';
  
FOR PEDIDOS IN (SELECT * FROM TABELA_INTEGRACAO) LOOP 
  
    IF LAST_KEY = PEDIDOS.DOCO||PEDIDOS.DCTO||PEDIDOS.KCOO||PEDIDOS.GS1A||PEDIDOS.AA05 THEN 

       UPDATE TABELA_INTEGRACAO
          SET UKID = V_UKID 
        WHERE DOCO = PEDIDOS.DOCO 
          AND DCTO = PEDIDOS.DCTO 
          AND GS1A = PEDIDOS.GS1A
          AND AA05 = PEDIDOS.AA05; 
      ELSE 
        
        V_UKID:= V_UKID+1;

       UPDATE TABELA_INTEGRACAO 
          SET UKID = V_UKID
        WHERE DOCO = PEDIDOS.DOCO 
          AND DCTO = PEDIDOS.DCTO 
          AND GS1A = PEDIDOS.GS1A
          AND AA05 = PEDIDOS.AA05;
     END IF;            
         COMMIT;

       LAST_KEY:= PEDIDOS.DOCO||PEDIDOS.DCTO||PEDIDOS.KCOO||PEDIDOS.GS1A||PEDIDOS.AA05;
       
END LOOP;
END;


--PASSO 4 : CRIAÇÃO DOS COMANDOS DE INSERT DOS DADOS NAS TABELAS DE INTEGRAÇÃO.


--COMANDOS DE INSERT NAS TABELAS DE CABEÇALHO

SELECT DISTINCT 
UKID,
'INSERT INTO PRODDTA.F554201C (
CHAC01,CHAN8,CHBBRCD,CHBCGF,CHBCGT,CHBNNF,CHBSER,CHDCT,CHDCTO,CHDOCO,CHEV01,CHEV02,CHEV12,CHGS1A,CHISSU,CHKCOO,CHN001,CHTRDJ,CHUKID,CHUOR2
) VALUES (' 
||T1.CHAC01           ||','
||T1.AN8              ||','
||''''||T1.BBRCD||''''||','
||''''||T1.BCGF||'''' ||',' 
||''''||T1.BCGT||'''' ||','
||T1.BNNF             ||','
||''''||T1.BSER||'''' ||','
||''''||T1.DCT||''''  ||','
||''''||T1.DCTO||'''' ||','
||T1.DOCO             ||','
||''''||T1.EV01||'''' ||','
||''''||T1.EV02||'''' ||','
||''''||T1.EV12||'''' ||','
||''''||T1.GS1A||'''' ||','
||T1.ISSU             ||','
||''''||T1.KCOO||'''' ||','
||T1.N001             ||','
||T1.TRDJ             ||','
||T1.UKID             ||','
||T1.UOR2             ||');'
|| CHR(10) AS INSERT_F554201C,

'INSERT INTO PRODDTA.F554201I (
IHAN8,IHBBRCD,IHBCGF,IHBCGT,IHBNNF,IHBSER,IHDCT,IHDCTO,IHDOCO,IHEV01,IHEV02,IHEV12,IHGS1A,IHISSU,IHKCOO,IHN001,IHRUKID,IHTRDJ,IHUKID,IHUOR2
) VALUES (' 
||T1.AN8              ||','
||''''||T1.BBRCD||''''||','
||''''||T1.BCGF||'''' ||',' 
||''''||T1.BCGT||'''' ||','
||T1.BNNF             ||','
||''''||T1.BSER||'''' ||','
||''''||T1.DCT||''''  ||','
||''''||T1.DCTO||'''' ||','
||T1.DOCO             ||','
||''''||T1.EV01||'''' ||','
||''''||T1.EV02||'''' ||','
||''''||T1.EV12||'''' ||','
||''''||T1.GS1A||'''' ||','
||T1.ISSU             ||','
||''''||T1.KCOO||'''' ||','
||T1.N001             ||','
||T1.IHRUKID          ||','
||T1.TRDJ             ||','
||T1.UKID             ||','
||T1.UOR2             ||');'
|| CHR(10)  AS INSERT_F554201I
FROM TABELA_INTEGRACAO T1
ORDER BY T1.UKID;


--COMANDOS DE INSERT NAS TABELAS DE DETALHE

SELECT 
DISTINCT 
UKID, LNID,
'INSERT INTO PRODDTA.F554211C (
CDUKID,CDKCOO,CDDOCO,CDDCTO,CDLNID,CDCITM,CDUORG,CDLITM,CDSOQS,CDAEXP,CDUPRC,CDPERCENT,CDAN01,CDBIST,CDFLAG,CDPTC,CDAA10,CDSRP8,CDEV01,
CDEV02,CDUK05,CDUK06,CDNDTP,CDAA05,CDUK07,CDDCPC) VALUES (' 
||T1.UKID                   ||','
||''''||T1.KCOO||''''       ||','
||T1.DOCO                   ||','
||''''||T1.DCTO||''''       ||','
||T1.LNID                   ||','
||''''||T1.CITM||''''       ||','
||T1.UORG                   ||','
||''''||T1.LITM||''''       ||','
||T1.SOQS                   ||','
||T1.AEXP                   ||','
||T1.UPRC                   ||','
||T1.PERCENT                ||','
||T1.AN01                   ||','
||''''||T1.BIST||''''       ||','
||''''||T1.FLAG||''''       ||','
||''''||T1.PTC||''''        ||','
||''''||T1.AA10||''''       ||','
||''''||T1.SRP8||''''       ||','
||''''||T1.DEV01||''''      ||','
||''''||T1.DEV02||''''      ||','
||T1.CDUK05                 ||','
||T1.CDUK06                 ||','
||T1.NDTP                   ||','
||''''||TRIM(T1.AA05)||'''' ||','
||T1.UK07                   ||','
||T1.DCPC                   ||');'
|| CHR(10) AS INSERT_F554211C,

'INSERT INTO PRODDTA.F554211I (
IDUKID,IDKCOO,IDDOCO,IDDCTO,IDLNID,IDCITM,IDUORG,IDLITM,IDSOQS,IDAEXP,IDUPRC,IDPERCENT,IDAN01,IDBIST,IDFLAG,IDPTC,IDAA10,IDSRP8,IDEV01,
IDEV02,IDNDTP,IDAA05,IDUK07,IDDCPC) VALUES (' 
||T1.UKID                    ||','
||''''||T1.KCOO||''''        ||','
||T1.DOCO                    ||','
||''''||T1.DCTO||''''        ||','
||T1.LNID                    ||','
||''''||T1.CITM||''''        ||','
||T1.UORG                    ||','
||''''||T1.LITM||''''        ||','
||T1.SOQS                    ||','
||T1.AEXP                    ||','
||T1.UPRC                    ||','
||T1.PERCENT                 ||','
||T1.AN01                    ||','
||''''||T1.BIST||''''        ||','
||''''||T1.FLAG||''''        ||','
||''''||T1.PTC||''''         ||','
||''''||T1.AA10||''''        ||','
||''''||T1.SRP8||''''        ||','
||''''||T1.DEV01||''''       ||','
||''''||T1.DEV02||''''       ||','
||T1.NDTP                    ||','
||''''||TRIM(T1.AA05)||''''  ||','
||T1.UK07                    ||','
||T1.DCPC                    ||');'
|| CHR(10)||CHR(10)
||'UPDATE PRODDTA.F5542099 SET CCSEC = ''1'' 
WHERE CCDOCO = ' ||T1.DOCO 
||' AND CCLNID = '||T1.LNID
||';'
|| CHR(10) AS INSERT_F554211I

FROM TABELA_INTEGRACAO T1
ORDER BY UKID, LNID;






