WITH CONSULTA_CADASTRO_REGRAS AS
 (
  --PESQUISA POR ATRIBUIÇÃO DE ESPAÇOS NO CAMPO "VALOR INFORMADO" DA ATRIBUIÇÃO
  SELECT *
    FROM (SELECT A.PV06_POLITICA   "NUMERO REGRA",
                  C.DB_RES_DESC     "DESCRICAO",
                  A.PV06_IDENT      "STRING DE FILTROS",
                  B.DB_CPO_VALORINF "VALOR ATRIBUIDO",
                  B.DB_CPO_TAGATRIB "CAMPO"
             FROM MERCANET_PRD.MPV06        A,
                  MERCANET_PRD.DB_CPO_ATRIB B,
                  MERCANET_PRD.DB_RESTRICAO C
            WHERE A.PV06_TIPO = 'A'
              AND A.PV06_IDREGRA = B.DB_CPO_RES_PAI
              AND A.PV06_POLITICA = C.DB_RES_CODIGO
              AND C.DB_RES_DTFIM > SYSDATE
              AND A.PV06_POLITICA = C.DB_RES_CODIGO
            ORDER BY PV06_POLITICA, PV06_IDENT)
   WHERE "VALOR ATRIBUIDO" LIKE '% %'
  UNION
  SELECT *
    FROM (SELECT A.PV06_POLITICA   "NUMERO REGRA",
                 C.DB_RES_DESC     "DESCRICAO",
                 A.PV06_IDENT      "STRING DE FILTROS",
                 B.DB_CPO_VALORINF "VALOR ATRIBUIDO",
                 B.DB_CPO_TAGATRIB "CAMPO"
            FROM MERCANET_PRD.MPV06        A,
                 MERCANET_PRD.DB_CPO_ATRIB B,
                 MERCANET_PRD.DB_RESTRICAO C
           WHERE A.PV06_TIPO = 'A'
             AND A.PV06_IDREGRA = B.DB_CPO_RES_PAI
             AND A.PV06_POLITICA = C.DB_RES_CODIGO
             AND C.DB_RES_DTFIM > SYSDATE
             AND A.PV06_POLITICA = C.DB_RES_CODIGO
           ORDER BY PV06_POLITICA, PV06_IDENT)
   WHERE "VALOR ATRIBUIDO" IS NULL
  UNION
  --PESQUISA POR ATRIBUIÇÃO DE ESPAÇOS NO CAMPO "VALOR INFORMADO" DA ATRIBUIÇÃO
  SELECT *
    FROM (SELECT A.PV06_POLITICA   "NUMERO REGRA",
                 C.DB_RES_DESC     "DESCRICAO",
                 A.PV06_IDENT      "STRING DE FILTROS",
                 B.DB_CPO_VALORINF "VALOR ATRIBUIDO",
                 B.DB_CPO_TAGATRIB "CAMPO"
            FROM MERCANET_PRD.MPV06        A,
                 MERCANET_PRD.DB_CPO_ATRIB B,
                 MERCANET_PRD.DB_RESTRICAO C
           WHERE A.PV06_TIPO = 'A'
             AND A.PV06_IDREGRA = B.DB_CPO_RES_PAI
             AND A.PV06_POLITICA = C.DB_RES_CODIGO
             AND C.DB_RES_DTFIM > SYSDATE
             AND A.PV06_POLITICA = C.DB_RES_CODIGO
           ORDER BY PV06_POLITICA, PV06_IDENT)
   WHERE "VALOR ATRIBUIDO" LIKE '0'
  UNION
  --PESQUISA DE FILTROS NÃO ADICIONADOS NA STRING DE FILTROS
  SELECT *
    FROM (SELECT A.PV06_POLITICA   "NUMERO REGRA",
                 C.DB_RES_DESC     "DESCRICAO",
                 A.PV06_IDENT      "STRING DE FILTROS",
                 B.DB_CPO_VALORINF "VALOR ATRIBUIDO",
                 B.DB_CPO_TAGATRIB "CAMPO"
            FROM MERCANET_PRD.MPV06        A,
                 MERCANET_PRD.DB_CPO_ATRIB B,
                 MERCANET_PRD.DB_RESTRICAO C
           WHERE A.PV06_TIPO = 'A'
             AND A.PV06_IDREGRA = B.DB_CPO_RES_PAI
             AND A.PV06_POLITICA = C.DB_RES_CODIGO
             AND C.DB_RES_DTFIM > SYSDATE
             AND A.PV06_POLITICA = C.DB_RES_CODIGO
           ORDER BY PV06_POLITICA, PV06_IDENT)
   WHERE "STRING DE FILTROS" LIKE '%# #%'
  UNION
  --PESQUISA DE VALORES NÃO PRESENTES NO FILTRO
  SELECT *
    FROM (SELECT A.PV06_POLITICA   "NUMERO REGRA",
                 C.DB_RES_DESC     "DESCRICAO",
                 A.PV06_IDENT      "STRING DE FILTROS",
                 B.DB_CPO_VALORINF "VALOR ATRIBUIDO",
                 B.DB_CPO_TAGATRIB "CAMPO"
            FROM MERCANET_PRD.MPV06        A,
                 MERCANET_PRD.DB_CPO_ATRIB B,
                 MERCANET_PRD.DB_RESTRICAO C
           WHERE A.PV06_TIPO = 'A'
             AND A.PV06_IDREGRA = B.DB_CPO_RES_PAI
             AND A.PV06_POLITICA = C.DB_RES_CODIGO
             AND C.DB_RES_DTFIM > SYSDATE
             AND A.PV06_POLITICA = C.DB_RES_CODIGO
           ORDER BY PV06_POLITICA, PV06_IDENT)
   WHERE "STRING DE FILTROS" LIKE '#%'
  UNION
  --PESQUISA DE VALORES NULOS NA HASH
  SELECT *
    FROM (SELECT A.PV06_POLITICA   "NUMERO REGRA",
                 C.DB_RES_DESC     "DESCRICAO",
                 A.PV06_IDENT      "STRING DE FILTROS",
                 B.DB_CPO_VALORINF "VALOR ATRIBUIDO",
                 B.DB_CPO_TAGATRIB "CAMPO"
            FROM MERCANET_PRD.MPV06        A,
                 MERCANET_PRD.DB_CPO_ATRIB B,
                 MERCANET_PRD.DB_RESTRICAO C
           WHERE A.PV06_TIPO = 'A'
             AND A.PV06_IDREGRA = B.DB_CPO_RES_PAI
             AND A.PV06_POLITICA = C.DB_RES_CODIGO
             AND C.DB_RES_DTFIM > SYSDATE
             AND A.PV06_POLITICA = C.DB_RES_CODIGO
           ORDER BY PV06_POLITICA, PV06_IDENT)
   WHERE "STRING DE FILTROS" IS NULL
  UNION
  --PESQUISA ERROS NA TELA PARAMETRIZAÇÃO DA GUIA FILTROS DA TELA DE RESTRIÇÕES E ATRIBUIÇÕES
  SELECT TO_CHAR(D.DB_RESR_CODIGO) "NUMERO REGRA",
         E.DB_RES_DESC "DESCRICAO",
         D.DB_RESR_VALOR "STRING DE FILTROS",
         ' ' "VALOR ATRIBUIDO",
         NULL "CAMPO"
    FROM MERCANET_PRD.DB_RESTR_REGRAS D, MERCANET_PRD.DB_RESTRICAO E
   WHERE D.DB_RESR_VALOR LIKE '%,'
     AND D.DB_RESR_CODIGO = E.DB_RES_CODIGO
     AND E.DB_RES_DTFIM > SYSDATE
  UNION
  SELECT TO_CHAR(D.DB_RESR_CODIGO) "NUMERO REGRA",
         E.DB_RES_DESC "DESCRICAO",
         D.DB_RESR_VALOR "STRING DE FILTROS",
         ' ' "VALOR ATRIBUIDO",
         NULL "CAMPO"
    FROM MERCANET_PRD.DB_RESTR_REGRAS D, MERCANET_PRD.DB_RESTRICAO E
   WHERE D.DB_RESR_VALOR LIKE '%,,%'
     AND D.DB_RESR_CODIGO = E.DB_RES_CODIGO
     AND E.DB_RES_DTFIM > SYSDATE)
SELECT COUNT(1) "TOTAL_ERROS_ENCONTRADOS" FROM CONSULTA_CADASTRO_REGRAS

 
 
 
 
