SELECT DB_EDIP_LOTE,
       SAVR01,
       SDOORN,
       SDDOCO,
       SDDOC,
       SDLTTR,
       SDNXTR,
       SDEMCU,
       SDMCU,
       SDZON,
       SDDCTO,
       SDLITM,
       SDLOCN,
       SDLOTN,
       SDLNTY,
       SDAN8,
       SDURAT,
       SDURAB,
       SHHOLD,
       SDUPMJ
  FROM QADTA.F5547011@DC07,
       QADTA.F4211@DC07,
       QADTA.F4201@DC07,
       MERCANET_QA.DB_EDI_PEDIDO@DC09
 WHERE EXISTS (SELECT DISTINCT DB_EDIP_PEDMERC
          FROM MERCANET_QA.DB_EDI_PEDIDO@DC09, MERCANET_QA.DB_PEDIDO@DC09
         WHERE DB_EDIP_VAN = '508'
           AND DB_EDIP_LOTE > 84358 
           AND DB_EDIP_LOTE < 84372
           AND DB_PED_NRO = DB_EDIP_PEDMERC
           AND TRIM(TO_CHAR(DB_PED_NRO)) = TRIM(TO_CHAR(SAVR01)))
   AND SDDOCO = SADOCO
   AND SDDOCO = SHDOCO
   AND SAVR01 = SDOORN
   AND SHHOLD = ' '
   AND SDLTTR NOT IN ('980', '982')
   AND SDLNTY = 'BS'
   AND TO_CHAR(DB_EDIP_PEDMERC) = TRIM(SAVR01)
 ORDER BY SDEMCU, SDNXTR
