INSERT INTO PRODUTOS_TESTE_ST  
SELECT '5' AS ID_TESTE, PRODUTOS.*, ESTOQUE.*
FROM
  (SELECT 'PROD_C_MRF_POS_NAC' AS TIPO_PRODUTO,
          DB_PROD_CODIGO,
          DB_PROD_DESCRICAO,(DB_PRDEMB_CODBARRA)
   FROM MERCANET_PRD.DB_PRODUTO SQ1,
        MERCANET_PRD.DB_PRODUTO_EMBAL SQ2,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ3,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ4,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ5,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ6
   WHERE SQ1.DB_PROD_CODIGO = SQ2.DB_PRDEMB_PRODUTO
     AND EXISTS
       (SELECT 1
        FROM MERCANET_QA.DB_PRODUTO@DC12 SSQ1
        WHERE SSQ1.DB_PROD_CODIGO = SQ1.DB_PROD_CODIGO
          AND SSQ1.DB_PROD_SITUACAO = 'A')
     AND SQ2.DB_PRDEMB_PRODUTO = SQ3.DB_PRODA_CODIGO
     AND SQ3.DB_PRODA_CODIGO = SQ4.DB_PRODA_CODIGO
     AND SQ4.DB_PRODA_CODIGO = SQ5.DB_PRODA_CODIGO
     AND SQ5.DB_PRODA_CODIGO = SQ6.DB_PRODA_CODIGO
     AND ROWNUM < 4 AND NOT EXISTS (SELECT * FROM DSALES.PRODUTOS_TESTE_ST T1 WHERE SQ2.DB_PRDEMB_PRODUTO = T1.DB_PROD_CODIGO)
     AND DB_PRDEMB_CODEMB = 1
     AND SQ3.DB_PRODA_ATRIB = 2008
     AND SQ4.DB_PRODA_ATRIB = 2014
     AND SQ5.DB_PRODA_ATRIB = 2017
     AND SQ6.DB_PRODA_ATRIB = 2018
     AND SQ3.DB_PRODA_VALOR = 'C'
     AND SQ4.DB_PRODA_VALOR = 'MRF'
     AND SQ5.DB_PRODA_VALOR = 'POS'
     AND SQ6.DB_PRODA_VALOR = 'NAC'
   UNION SELECT 'PROD_C_MRF_POS_IMP' AS TIPO_PRODUTO,
                DB_PROD_CODIGO,
                DB_PROD_DESCRICAO,
                DB_PRDEMB_CODBARRA
   FROM MERCANET_PRD.DB_PRODUTO SQ1,
        MERCANET_PRD.DB_PRODUTO_EMBAL SQ2,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ3,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ4,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ5,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ6
   WHERE SQ1.DB_PROD_CODIGO = SQ2.DB_PRDEMB_PRODUTO
     AND EXISTS
       (SELECT 1
        FROM MERCANET_QA.DB_PRODUTO@DC12 SSQ1
        WHERE SSQ1.DB_PROD_CODIGO = SQ1.DB_PROD_CODIGO
          AND SSQ1.DB_PROD_SITUACAO = 'A')
     AND SQ2.DB_PRDEMB_PRODUTO = SQ3.DB_PRODA_CODIGO
     AND SQ3.DB_PRODA_CODIGO = SQ4.DB_PRODA_CODIGO
     AND SQ4.DB_PRODA_CODIGO = SQ5.DB_PRODA_CODIGO
     AND SQ5.DB_PRODA_CODIGO = SQ6.DB_PRODA_CODIGO
     AND ROWNUM < 4 AND NOT EXISTS (SELECT * FROM DSALES.PRODUTOS_TESTE_ST T1 WHERE SQ2.DB_PRDEMB_PRODUTO = T1.DB_PROD_CODIGO)
     AND DB_PRDEMB_CODEMB = 1
     AND SQ3.DB_PRODA_ATRIB = 2008
     AND SQ4.DB_PRODA_ATRIB = 2014
     AND SQ5.DB_PRODA_ATRIB = 2017
     AND SQ6.DB_PRODA_ATRIB = 2018
     AND SQ3.DB_PRODA_VALOR = 'C'
     AND SQ4.DB_PRODA_VALOR = 'MRF'
     AND SQ5.DB_PRODA_VALOR = 'POS'
     AND SQ6.DB_PRODA_VALOR = 'IMP'
   UNION SELECT 'PROD_C_MRF_NEG_NAC' AS TIPO_PRODUTO,
                DB_PROD_CODIGO,
                DB_PROD_DESCRICAO,
                DB_PRDEMB_CODBARRA
   FROM MERCANET_PRD.DB_PRODUTO SQ1,
        MERCANET_PRD.DB_PRODUTO_EMBAL SQ2,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ3,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ4,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ5,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ6
   WHERE SQ1.DB_PROD_CODIGO = SQ2.DB_PRDEMB_PRODUTO
     AND EXISTS
       (SELECT 1
        FROM MERCANET_QA.DB_PRODUTO@DC12 SSQ1
        WHERE SSQ1.DB_PROD_CODIGO = SQ1.DB_PROD_CODIGO
          AND SSQ1.DB_PROD_SITUACAO = 'A')
     AND SQ2.DB_PRDEMB_PRODUTO = SQ3.DB_PRODA_CODIGO
     AND SQ3.DB_PRODA_CODIGO = SQ4.DB_PRODA_CODIGO
     AND SQ4.DB_PRODA_CODIGO = SQ5.DB_PRODA_CODIGO
     AND SQ5.DB_PRODA_CODIGO = SQ6.DB_PRODA_CODIGO
     AND ROWNUM < 4 AND NOT EXISTS (SELECT * FROM DSALES.PRODUTOS_TESTE_ST T1 WHERE SQ2.DB_PRDEMB_PRODUTO = T1.DB_PROD_CODIGO)
     AND DB_PRDEMB_CODEMB = 1
     AND SQ3.DB_PRODA_ATRIB = 2008
     AND SQ4.DB_PRODA_ATRIB = 2014
     AND SQ5.DB_PRODA_ATRIB = 2017
     AND SQ6.DB_PRODA_ATRIB = 2018
     AND SQ3.DB_PRODA_VALOR = 'C'
     AND SQ4.DB_PRODA_VALOR = 'MRF'
     AND SQ5.DB_PRODA_VALOR = 'NEG'
     AND SQ6.DB_PRODA_VALOR = 'NAC'
   UNION SELECT 'PROD_C_MRF_NEG_IMP' AS TIPO_PRODUTO,
                DB_PROD_CODIGO,
                DB_PROD_DESCRICAO,
                DB_PRDEMB_CODBARRA
   FROM MERCANET_PRD.DB_PRODUTO SQ1,
        MERCANET_PRD.DB_PRODUTO_EMBAL SQ2,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ3,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ4,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ5,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ6
   WHERE SQ1.DB_PROD_CODIGO = SQ2.DB_PRDEMB_PRODUTO
     AND EXISTS
       (SELECT 1
        FROM MERCANET_QA.DB_PRODUTO@DC12 SSQ1
        WHERE SSQ1.DB_PROD_CODIGO = SQ1.DB_PROD_CODIGO
          AND SSQ1.DB_PROD_SITUACAO = 'A')
     AND SQ2.DB_PRDEMB_PRODUTO = SQ3.DB_PRODA_CODIGO
     AND SQ3.DB_PRODA_CODIGO = SQ4.DB_PRODA_CODIGO
     AND SQ4.DB_PRODA_CODIGO = SQ5.DB_PRODA_CODIGO
     AND SQ5.DB_PRODA_CODIGO = SQ6.DB_PRODA_CODIGO
     AND ROWNUM < 4 AND NOT EXISTS (SELECT * FROM DSALES.PRODUTOS_TESTE_ST T1 WHERE SQ2.DB_PRDEMB_PRODUTO = T1.DB_PROD_CODIGO)
     AND DB_PRDEMB_CODEMB = 1
     AND SQ3.DB_PRODA_ATRIB = 2008
     AND SQ4.DB_PRODA_ATRIB = 2014
     AND SQ5.DB_PRODA_ATRIB = 2017
     AND SQ6.DB_PRODA_ATRIB = 2018
     AND SQ3.DB_PRODA_VALOR = 'C'
     AND SQ4.DB_PRODA_VALOR = 'MRF'
     AND SQ5.DB_PRODA_VALOR = 'NEG'
     AND SQ6.DB_PRODA_VALOR = 'IMP'
   UNION SELECT 'PROD_C_MRF_NEU_NAC' AS TIPO_PRODUTO,
                DB_PROD_CODIGO,
                DB_PROD_DESCRICAO,
                DB_PRDEMB_CODBARRA
   FROM MERCANET_PRD.DB_PRODUTO SQ1,
        MERCANET_PRD.DB_PRODUTO_EMBAL SQ2,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ3,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ4,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ5,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ6
   WHERE SQ1.DB_PROD_CODIGO = SQ2.DB_PRDEMB_PRODUTO
     AND EXISTS
       (SELECT 1
        FROM MERCANET_QA.DB_PRODUTO@DC12 SSQ1
        WHERE SSQ1.DB_PROD_CODIGO = SQ1.DB_PROD_CODIGO
          AND SSQ1.DB_PROD_SITUACAO = 'A')
     AND SQ2.DB_PRDEMB_PRODUTO = SQ3.DB_PRODA_CODIGO
     AND SQ3.DB_PRODA_CODIGO = SQ4.DB_PRODA_CODIGO
     AND SQ4.DB_PRODA_CODIGO = SQ5.DB_PRODA_CODIGO
     AND SQ5.DB_PRODA_CODIGO = SQ6.DB_PRODA_CODIGO
     AND ROWNUM < 4 AND NOT EXISTS (SELECT * FROM DSALES.PRODUTOS_TESTE_ST T1 WHERE SQ2.DB_PRDEMB_PRODUTO = T1.DB_PROD_CODIGO)
     AND DB_PRDEMB_CODEMB = 1
     AND SQ3.DB_PRODA_ATRIB = 2008
     AND SQ4.DB_PRODA_ATRIB = 2014
     AND SQ5.DB_PRODA_ATRIB = 2017
     AND SQ6.DB_PRODA_ATRIB = 2018
     AND SQ3.DB_PRODA_VALOR = 'C'
     AND SQ4.DB_PRODA_VALOR = 'MRF'
     AND SQ5.DB_PRODA_VALOR = 'NEU'
     AND SQ6.DB_PRODA_VALOR = 'NAC'
   UNION SELECT 'PROD_C_MRF_NEU_IMP' AS TIPO_PRODUTO,
                DB_PROD_CODIGO,
                DB_PROD_DESCRICAO,
                DB_PRDEMB_CODBARRA
   FROM MERCANET_PRD.DB_PRODUTO SQ1,
        MERCANET_PRD.DB_PRODUTO_EMBAL SQ2,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ3,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ4,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ5,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ6
   WHERE SQ1.DB_PROD_CODIGO = SQ2.DB_PRDEMB_PRODUTO
     AND EXISTS
       (SELECT 1
        FROM MERCANET_QA.DB_PRODUTO@DC12 SSQ1
        WHERE SSQ1.DB_PROD_CODIGO = SQ1.DB_PROD_CODIGO
          AND SSQ1.DB_PROD_SITUACAO = 'A')
     AND SQ2.DB_PRDEMB_PRODUTO = SQ3.DB_PRODA_CODIGO
     AND SQ3.DB_PRODA_CODIGO = SQ4.DB_PRODA_CODIGO
     AND SQ4.DB_PRODA_CODIGO = SQ5.DB_PRODA_CODIGO
     AND SQ5.DB_PRODA_CODIGO = SQ6.DB_PRODA_CODIGO
     AND ROWNUM < 4 AND NOT EXISTS (SELECT * FROM DSALES.PRODUTOS_TESTE_ST T1 WHERE SQ2.DB_PRDEMB_PRODUTO = T1.DB_PROD_CODIGO)
     AND DB_PRDEMB_CODEMB = 1
     AND SQ3.DB_PRODA_ATRIB = 2008
     AND SQ4.DB_PRODA_ATRIB = 2014
     AND SQ5.DB_PRODA_ATRIB = 2017
     AND SQ6.DB_PRODA_ATRIB = 2018
     AND SQ3.DB_PRODA_VALOR = 'C'
     AND SQ4.DB_PRODA_VALOR = 'MRF'
     AND SQ5.DB_PRODA_VALOR = 'NEU'
     AND SQ6.DB_PRODA_VALOR = 'IMP'
   UNION ------MED
 SELECT 'PROD_C_MED_POS_NAC' AS TIPO_PRODUTO,
        DB_PROD_CODIGO,
        DB_PROD_DESCRICAO,
        DB_PRDEMB_CODBARRA
   FROM MERCANET_PRD.DB_PRODUTO SQ1,
        MERCANET_PRD.DB_PRODUTO_EMBAL SQ2,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ3,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ4,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ5,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ6
   WHERE SQ1.DB_PROD_CODIGO = SQ2.DB_PRDEMB_PRODUTO
     AND EXISTS
       (SELECT 1
        FROM MERCANET_QA.DB_PRODUTO@DC12 SSQ1
        WHERE SSQ1.DB_PROD_CODIGO = SQ1.DB_PROD_CODIGO
          AND SSQ1.DB_PROD_SITUACAO = 'A')
     AND SQ2.DB_PRDEMB_PRODUTO = SQ3.DB_PRODA_CODIGO
     AND SQ3.DB_PRODA_CODIGO = SQ4.DB_PRODA_CODIGO
     AND SQ4.DB_PRODA_CODIGO = SQ5.DB_PRODA_CODIGO
     AND SQ5.DB_PRODA_CODIGO = SQ6.DB_PRODA_CODIGO
     AND ROWNUM < 4 AND NOT EXISTS (SELECT * FROM DSALES.PRODUTOS_TESTE_ST T1 WHERE SQ2.DB_PRDEMB_PRODUTO = T1.DB_PROD_CODIGO)
     AND DB_PRDEMB_CODEMB = 1
     AND SQ3.DB_PRODA_ATRIB = 2008
     AND SQ4.DB_PRODA_ATRIB = 2014
     AND SQ5.DB_PRODA_ATRIB = 2017
     AND SQ6.DB_PRODA_ATRIB = 2018
     AND SQ3.DB_PRODA_VALOR = 'C'
     AND SQ4.DB_PRODA_VALOR = 'MED'
     AND SQ5.DB_PRODA_VALOR = 'POS'
     AND SQ6.DB_PRODA_VALOR = 'NAC'
   UNION SELECT 'PROD_C_MED_POS_IMP' AS TIPO_PRODUTO,
                DB_PROD_CODIGO,
                DB_PROD_DESCRICAO,
                DB_PRDEMB_CODBARRA
   FROM MERCANET_PRD.DB_PRODUTO SQ1,
        MERCANET_PRD.DB_PRODUTO_EMBAL SQ2,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ3,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ4,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ5,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ6
   WHERE SQ1.DB_PROD_CODIGO = SQ2.DB_PRDEMB_PRODUTO
     AND EXISTS
       (SELECT 1
        FROM MERCANET_QA.DB_PRODUTO@DC12 SSQ1
        WHERE SSQ1.DB_PROD_CODIGO = SQ1.DB_PROD_CODIGO
          AND SSQ1.DB_PROD_SITUACAO = 'A')
     AND SQ2.DB_PRDEMB_PRODUTO = SQ3.DB_PRODA_CODIGO
     AND SQ3.DB_PRODA_CODIGO = SQ4.DB_PRODA_CODIGO
     AND SQ4.DB_PRODA_CODIGO = SQ5.DB_PRODA_CODIGO
     AND SQ5.DB_PRODA_CODIGO = SQ6.DB_PRODA_CODIGO
     AND ROWNUM < 4 AND NOT EXISTS (SELECT * FROM DSALES.PRODUTOS_TESTE_ST T1 WHERE SQ2.DB_PRDEMB_PRODUTO = T1.DB_PROD_CODIGO)
     AND DB_PRDEMB_CODEMB = 1
     AND SQ3.DB_PRODA_ATRIB = 2008
     AND SQ4.DB_PRODA_ATRIB = 2014
     AND SQ5.DB_PRODA_ATRIB = 2017
     AND SQ6.DB_PRODA_ATRIB = 2018
     AND SQ3.DB_PRODA_VALOR = 'C'
     AND SQ4.DB_PRODA_VALOR = 'MED'
     AND SQ5.DB_PRODA_VALOR = 'POS'
     AND SQ6.DB_PRODA_VALOR = 'IMP'
   UNION SELECT 'PROD_C_MED_NEG_NAC' AS TIPO_PRODUTO,
                DB_PROD_CODIGO,
                DB_PROD_DESCRICAO,
                DB_PRDEMB_CODBARRA
   FROM MERCANET_PRD.DB_PRODUTO SQ1,
        MERCANET_PRD.DB_PRODUTO_EMBAL SQ2,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ3,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ4,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ5,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ6
   WHERE SQ1.DB_PROD_CODIGO = SQ2.DB_PRDEMB_PRODUTO
     AND EXISTS
       (SELECT 1
        FROM MERCANET_QA.DB_PRODUTO@DC12 SSQ1
        WHERE SSQ1.DB_PROD_CODIGO = SQ1.DB_PROD_CODIGO
          AND SSQ1.DB_PROD_SITUACAO = 'A')
     AND SQ2.DB_PRDEMB_PRODUTO = SQ3.DB_PRODA_CODIGO
     AND SQ3.DB_PRODA_CODIGO = SQ4.DB_PRODA_CODIGO
     AND SQ4.DB_PRODA_CODIGO = SQ5.DB_PRODA_CODIGO
     AND SQ5.DB_PRODA_CODIGO = SQ6.DB_PRODA_CODIGO
     AND ROWNUM < 4 AND NOT EXISTS (SELECT * FROM DSALES.PRODUTOS_TESTE_ST T1 WHERE SQ2.DB_PRDEMB_PRODUTO = T1.DB_PROD_CODIGO)
     AND DB_PRDEMB_CODEMB = 1
     AND SQ3.DB_PRODA_ATRIB = 2008
     AND SQ4.DB_PRODA_ATRIB = 2014
     AND SQ5.DB_PRODA_ATRIB = 2017
     AND SQ6.DB_PRODA_ATRIB = 2018
     AND SQ3.DB_PRODA_VALOR = 'C'
     AND SQ4.DB_PRODA_VALOR = 'MED'
     AND SQ5.DB_PRODA_VALOR = 'NEG'
     AND SQ6.DB_PRODA_VALOR = 'NAC'
   UNION SELECT 'PROD_C_MED_NEG_IMP' AS TIPO_PRODUTO,
                DB_PROD_CODIGO,
                DB_PROD_DESCRICAO,
                DB_PRDEMB_CODBARRA
   FROM MERCANET_PRD.DB_PRODUTO SQ1,
        MERCANET_PRD.DB_PRODUTO_EMBAL SQ2,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ3,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ4,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ5,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ6
   WHERE SQ1.DB_PROD_CODIGO = SQ2.DB_PRDEMB_PRODUTO
     AND EXISTS
       (SELECT 1
        FROM MERCANET_QA.DB_PRODUTO@DC12 SSQ1
        WHERE SSQ1.DB_PROD_CODIGO = SQ1.DB_PROD_CODIGO
          AND SSQ1.DB_PROD_SITUACAO = 'A')
     AND SQ2.DB_PRDEMB_PRODUTO = SQ3.DB_PRODA_CODIGO
     AND SQ3.DB_PRODA_CODIGO = SQ4.DB_PRODA_CODIGO
     AND SQ4.DB_PRODA_CODIGO = SQ5.DB_PRODA_CODIGO
     AND SQ5.DB_PRODA_CODIGO = SQ6.DB_PRODA_CODIGO
     AND ROWNUM < 4 AND NOT EXISTS (SELECT * FROM DSALES.PRODUTOS_TESTE_ST T1 WHERE SQ2.DB_PRDEMB_PRODUTO = T1.DB_PROD_CODIGO)
     AND DB_PRDEMB_CODEMB = 1
     AND SQ3.DB_PRODA_ATRIB = 2008
     AND SQ4.DB_PRODA_ATRIB = 2014
     AND SQ5.DB_PRODA_ATRIB = 2017
     AND SQ6.DB_PRODA_ATRIB = 2018
     AND SQ3.DB_PRODA_VALOR = 'C'
     AND SQ4.DB_PRODA_VALOR = 'MED'
     AND SQ5.DB_PRODA_VALOR = 'NEG'
     AND SQ6.DB_PRODA_VALOR = 'IMP'
   UNION SELECT 'PROD_C_MED_NEU_NAC' AS TIPO_PRODUTO,
                DB_PROD_CODIGO,
                DB_PROD_DESCRICAO,
                DB_PRDEMB_CODBARRA
   FROM MERCANET_PRD.DB_PRODUTO SQ1,
        MERCANET_PRD.DB_PRODUTO_EMBAL SQ2,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ3,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ4,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ5,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ6
   WHERE SQ1.DB_PROD_CODIGO = SQ2.DB_PRDEMB_PRODUTO
     AND EXISTS
       (SELECT 1
        FROM MERCANET_QA.DB_PRODUTO@DC12 SSQ1
        WHERE SSQ1.DB_PROD_CODIGO = SQ1.DB_PROD_CODIGO
          AND SSQ1.DB_PROD_SITUACAO = 'A')
     AND SQ2.DB_PRDEMB_PRODUTO = SQ3.DB_PRODA_CODIGO
     AND SQ3.DB_PRODA_CODIGO = SQ4.DB_PRODA_CODIGO
     AND SQ4.DB_PRODA_CODIGO = SQ5.DB_PRODA_CODIGO
     AND SQ5.DB_PRODA_CODIGO = SQ6.DB_PRODA_CODIGO
     AND ROWNUM < 4 AND NOT EXISTS (SELECT * FROM DSALES.PRODUTOS_TESTE_ST T1 WHERE SQ2.DB_PRDEMB_PRODUTO = T1.DB_PROD_CODIGO)
     AND DB_PRDEMB_CODEMB = 1
     AND SQ3.DB_PRODA_ATRIB = 2008
     AND SQ4.DB_PRODA_ATRIB = 2014
     AND SQ5.DB_PRODA_ATRIB = 2017
     AND SQ6.DB_PRODA_ATRIB = 2018
     AND SQ3.DB_PRODA_VALOR = 'C'
     AND SQ4.DB_PRODA_VALOR = 'MED'
     AND SQ5.DB_PRODA_VALOR = 'NEU'
     AND SQ6.DB_PRODA_VALOR = 'NAC'
   UNION SELECT 'PROD_C_MED_NEU_IMP' AS TIPO_PRODUTO,
                DB_PROD_CODIGO,
                DB_PROD_DESCRICAO,
                DB_PRDEMB_CODBARRA
   FROM MERCANET_PRD.DB_PRODUTO SQ1,
        MERCANET_PRD.DB_PRODUTO_EMBAL SQ2,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ3,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ4,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ5,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ6
   WHERE SQ1.DB_PROD_CODIGO = SQ2.DB_PRDEMB_PRODUTO
     AND EXISTS
       (SELECT 1
        FROM MERCANET_QA.DB_PRODUTO@DC12 SSQ1
        WHERE SSQ1.DB_PROD_CODIGO = SQ1.DB_PROD_CODIGO
          AND SSQ1.DB_PROD_SITUACAO = 'A')
     AND SQ2.DB_PRDEMB_PRODUTO = SQ3.DB_PRODA_CODIGO
     AND SQ3.DB_PRODA_CODIGO = SQ4.DB_PRODA_CODIGO
     AND SQ4.DB_PRODA_CODIGO = SQ5.DB_PRODA_CODIGO
     AND SQ5.DB_PRODA_CODIGO = SQ6.DB_PRODA_CODIGO
     AND ROWNUM < 4 AND NOT EXISTS (SELECT * FROM DSALES.PRODUTOS_TESTE_ST T1 WHERE SQ2.DB_PRDEMB_PRODUTO = T1.DB_PROD_CODIGO)
     AND DB_PRDEMB_CODEMB = 1
     AND SQ3.DB_PRODA_ATRIB = 2008
     AND SQ4.DB_PRODA_ATRIB = 2014
     AND SQ5.DB_PRODA_ATRIB = 2017
     AND SQ6.DB_PRODA_ATRIB = 2018
     AND SQ3.DB_PRODA_VALOR = 'C'
     AND SQ4.DB_PRODA_VALOR = 'MED'
     AND SQ5.DB_PRODA_VALOR = 'NEU'
     AND SQ6.DB_PRODA_VALOR = 'IMP'
   UNION ---------MSM
 SELECT 'PROD_C_MSM_POS_NAC' AS TIPO_PRODUTO,
        DB_PROD_CODIGO,
        DB_PROD_DESCRICAO,
        DB_PRDEMB_CODBARRA
   FROM MERCANET_PRD.DB_PRODUTO SQ1,
        MERCANET_PRD.DB_PRODUTO_EMBAL SQ2,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ3,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ4,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ5,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ6
   WHERE SQ1.DB_PROD_CODIGO = SQ2.DB_PRDEMB_PRODUTO
     AND EXISTS
       (SELECT 1
        FROM MERCANET_QA.DB_PRODUTO@DC12 SSQ1
        WHERE SSQ1.DB_PROD_CODIGO = SQ1.DB_PROD_CODIGO
          AND SSQ1.DB_PROD_SITUACAO = 'A')
     AND SQ2.DB_PRDEMB_PRODUTO = SQ3.DB_PRODA_CODIGO
     AND SQ3.DB_PRODA_CODIGO = SQ4.DB_PRODA_CODIGO
     AND SQ4.DB_PRODA_CODIGO = SQ5.DB_PRODA_CODIGO
     AND SQ5.DB_PRODA_CODIGO = SQ6.DB_PRODA_CODIGO
     AND ROWNUM < 4 AND NOT EXISTS (SELECT * FROM DSALES.PRODUTOS_TESTE_ST T1 WHERE SQ2.DB_PRDEMB_PRODUTO = T1.DB_PROD_CODIGO)
     AND DB_PRDEMB_CODEMB = 1
     AND SQ3.DB_PRODA_ATRIB = 2008
     AND SQ4.DB_PRODA_ATRIB = 2014
     AND SQ5.DB_PRODA_ATRIB = 2017
     AND SQ6.DB_PRODA_ATRIB = 2018
     AND SQ3.DB_PRODA_VALOR = 'C'
     AND SQ4.DB_PRODA_VALOR = 'MSM'
     AND SQ5.DB_PRODA_VALOR = 'POS'
     AND SQ6.DB_PRODA_VALOR = 'NAC'
   UNION SELECT 'PROD_C_MSM_POS_IMP' AS TIPO_PRODUTO,
                DB_PROD_CODIGO,
                DB_PROD_DESCRICAO,
                DB_PRDEMB_CODBARRA
   FROM MERCANET_PRD.DB_PRODUTO SQ1,
        MERCANET_PRD.DB_PRODUTO_EMBAL SQ2,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ3,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ4,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ5,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ6
   WHERE SQ1.DB_PROD_CODIGO = SQ2.DB_PRDEMB_PRODUTO
     AND EXISTS
       (SELECT 1
        FROM MERCANET_QA.DB_PRODUTO@DC12 SSQ1
        WHERE SSQ1.DB_PROD_CODIGO = SQ1.DB_PROD_CODIGO
          AND SSQ1.DB_PROD_SITUACAO = 'A')
     AND SQ2.DB_PRDEMB_PRODUTO = SQ3.DB_PRODA_CODIGO
     AND SQ3.DB_PRODA_CODIGO = SQ4.DB_PRODA_CODIGO
     AND SQ4.DB_PRODA_CODIGO = SQ5.DB_PRODA_CODIGO
     AND SQ5.DB_PRODA_CODIGO = SQ6.DB_PRODA_CODIGO
     AND ROWNUM < 4 AND NOT EXISTS (SELECT * FROM DSALES.PRODUTOS_TESTE_ST T1 WHERE SQ2.DB_PRDEMB_PRODUTO = T1.DB_PROD_CODIGO)
     AND DB_PRDEMB_CODEMB = 1
     AND SQ3.DB_PRODA_ATRIB = 2008
     AND SQ4.DB_PRODA_ATRIB = 2014
     AND SQ5.DB_PRODA_ATRIB = 2017
     AND SQ6.DB_PRODA_ATRIB = 2018
     AND SQ3.DB_PRODA_VALOR = 'C'
     AND SQ4.DB_PRODA_VALOR = 'MSM'
     AND SQ5.DB_PRODA_VALOR = 'POS'
     AND SQ6.DB_PRODA_VALOR = 'IMP'
   UNION SELECT 'PROD_C_MSM_NEG_NAC' AS TIPO_PRODUTO,
                DB_PROD_CODIGO,
                DB_PROD_DESCRICAO,
                DB_PRDEMB_CODBARRA
   FROM MERCANET_PRD.DB_PRODUTO SQ1,
        MERCANET_PRD.DB_PRODUTO_EMBAL SQ2,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ3,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ4,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ5,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ6
   WHERE SQ1.DB_PROD_CODIGO = SQ2.DB_PRDEMB_PRODUTO
     AND EXISTS
       (SELECT 1
        FROM MERCANET_QA.DB_PRODUTO@DC12 SSQ1
        WHERE SSQ1.DB_PROD_CODIGO = SQ1.DB_PROD_CODIGO
          AND SSQ1.DB_PROD_SITUACAO = 'A')
     AND SQ2.DB_PRDEMB_PRODUTO = SQ3.DB_PRODA_CODIGO
     AND SQ3.DB_PRODA_CODIGO = SQ4.DB_PRODA_CODIGO
     AND SQ4.DB_PRODA_CODIGO = SQ5.DB_PRODA_CODIGO
     AND SQ5.DB_PRODA_CODIGO = SQ6.DB_PRODA_CODIGO
     AND ROWNUM < 4 AND NOT EXISTS (SELECT * FROM DSALES.PRODUTOS_TESTE_ST T1 WHERE SQ2.DB_PRDEMB_PRODUTO = T1.DB_PROD_CODIGO)
     AND DB_PRDEMB_CODEMB = 1
     AND SQ3.DB_PRODA_ATRIB = 2008
     AND SQ4.DB_PRODA_ATRIB = 2014
     AND SQ5.DB_PRODA_ATRIB = 2017
     AND SQ6.DB_PRODA_ATRIB = 2018
     AND SQ3.DB_PRODA_VALOR = 'C'
     AND SQ4.DB_PRODA_VALOR = 'MSM'
     AND SQ5.DB_PRODA_VALOR = 'NEG'
     AND SQ6.DB_PRODA_VALOR = 'NAC'
   UNION SELECT 'PROD_C_MSM_NEG_IMP' AS TIPO_PRODUTO,
                DB_PROD_CODIGO,
                DB_PROD_DESCRICAO,
                DB_PRDEMB_CODBARRA
   FROM MERCANET_PRD.DB_PRODUTO SQ1,
        MERCANET_PRD.DB_PRODUTO_EMBAL SQ2,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ3,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ4,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ5,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ6
   WHERE SQ1.DB_PROD_CODIGO = SQ2.DB_PRDEMB_PRODUTO
     AND EXISTS
       (SELECT 1
        FROM MERCANET_QA.DB_PRODUTO@DC12 SSQ1
        WHERE SSQ1.DB_PROD_CODIGO = SQ1.DB_PROD_CODIGO
          AND SSQ1.DB_PROD_SITUACAO = 'A')
     AND SQ2.DB_PRDEMB_PRODUTO = SQ3.DB_PRODA_CODIGO
     AND SQ3.DB_PRODA_CODIGO = SQ4.DB_PRODA_CODIGO
     AND SQ4.DB_PRODA_CODIGO = SQ5.DB_PRODA_CODIGO
     AND SQ5.DB_PRODA_CODIGO = SQ6.DB_PRODA_CODIGO
     AND ROWNUM < 4 AND NOT EXISTS (SELECT * FROM DSALES.PRODUTOS_TESTE_ST T1 WHERE SQ2.DB_PRDEMB_PRODUTO = T1.DB_PROD_CODIGO)
     AND DB_PRDEMB_CODEMB = 1
     AND SQ3.DB_PRODA_ATRIB = 2008
     AND SQ4.DB_PRODA_ATRIB = 2014
     AND SQ5.DB_PRODA_ATRIB = 2017
     AND SQ6.DB_PRODA_ATRIB = 2018
     AND SQ3.DB_PRODA_VALOR = 'C'
     AND SQ4.DB_PRODA_VALOR = 'MSM'
     AND SQ5.DB_PRODA_VALOR = 'NEG'
     AND SQ6.DB_PRODA_VALOR = 'IMP'
   UNION SELECT 'PROD_C_MSM_NEU_NAC' AS TIPO_PRODUTO,
                DB_PROD_CODIGO,
                DB_PROD_DESCRICAO,
                DB_PRDEMB_CODBARRA
   FROM MERCANET_PRD.DB_PRODUTO SQ1,
        MERCANET_PRD.DB_PRODUTO_EMBAL SQ2,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ3,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ4,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ5,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ6
   WHERE SQ1.DB_PROD_CODIGO = SQ2.DB_PRDEMB_PRODUTO
     AND EXISTS
       (SELECT 1
        FROM MERCANET_QA.DB_PRODUTO@DC12 SSQ1
        WHERE SSQ1.DB_PROD_CODIGO = SQ1.DB_PROD_CODIGO
          AND SSQ1.DB_PROD_SITUACAO = 'A')
     AND SQ2.DB_PRDEMB_PRODUTO = SQ3.DB_PRODA_CODIGO
     AND SQ3.DB_PRODA_CODIGO = SQ4.DB_PRODA_CODIGO
     AND SQ4.DB_PRODA_CODIGO = SQ5.DB_PRODA_CODIGO
     AND SQ5.DB_PRODA_CODIGO = SQ6.DB_PRODA_CODIGO
     AND ROWNUM < 4 AND NOT EXISTS (SELECT * FROM DSALES.PRODUTOS_TESTE_ST T1 WHERE SQ2.DB_PRDEMB_PRODUTO = T1.DB_PROD_CODIGO)
     AND DB_PRDEMB_CODEMB = 1
     AND SQ3.DB_PRODA_ATRIB = 2008
     AND SQ4.DB_PRODA_ATRIB = 2014
     AND SQ5.DB_PRODA_ATRIB = 2017
     AND SQ6.DB_PRODA_ATRIB = 2018
     AND SQ3.DB_PRODA_VALOR = 'C'
     AND SQ4.DB_PRODA_VALOR = 'MSM'
     AND SQ5.DB_PRODA_VALOR = 'NEU'
     AND SQ6.DB_PRODA_VALOR = 'NAC'
   UNION SELECT 'PROD_C_MSM_NEU_IMP' AS TIPO_PRODUTO,
                DB_PROD_CODIGO,
                DB_PROD_DESCRICAO,
                DB_PRDEMB_CODBARRA
   FROM MERCANET_PRD.DB_PRODUTO SQ1,
        MERCANET_PRD.DB_PRODUTO_EMBAL SQ2,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ3,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ4,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ5,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ6
   WHERE SQ1.DB_PROD_CODIGO = SQ2.DB_PRDEMB_PRODUTO
     AND EXISTS
       (SELECT 1
        FROM MERCANET_QA.DB_PRODUTO@DC12 SSQ1
        WHERE SSQ1.DB_PROD_CODIGO = SQ1.DB_PROD_CODIGO
          AND SSQ1.DB_PROD_SITUACAO = 'A')
     AND SQ2.DB_PRDEMB_PRODUTO = SQ3.DB_PRODA_CODIGO
     AND SQ3.DB_PRODA_CODIGO = SQ4.DB_PRODA_CODIGO
     AND SQ4.DB_PRODA_CODIGO = SQ5.DB_PRODA_CODIGO
     AND SQ5.DB_PRODA_CODIGO = SQ6.DB_PRODA_CODIGO
     AND ROWNUM < 4 AND NOT EXISTS (SELECT * FROM DSALES.PRODUTOS_TESTE_ST T1 WHERE SQ2.DB_PRDEMB_PRODUTO = T1.DB_PROD_CODIGO)
     AND DB_PRDEMB_CODEMB = 1
     AND SQ3.DB_PRODA_ATRIB = 2008
     AND SQ4.DB_PRODA_ATRIB = 2014
     AND SQ5.DB_PRODA_ATRIB = 2017
     AND SQ6.DB_PRODA_ATRIB = 2018
     AND SQ3.DB_PRODA_VALOR = 'C'
     AND SQ4.DB_PRODA_VALOR = 'MSM'
     AND SQ5.DB_PRODA_VALOR = 'NEU'
     AND SQ6.DB_PRODA_VALOR = 'IMP'
   UNION ---------MGN
 SELECT 'PROD_C_MGN_POS_NAC' AS TIPO_PRODUTO,
        DB_PROD_CODIGO,
        DB_PROD_DESCRICAO,
        DB_PRDEMB_CODBARRA
   FROM MERCANET_PRD.DB_PRODUTO SQ1,
        MERCANET_PRD.DB_PRODUTO_EMBAL SQ2,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ3,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ4,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ5,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ6
   WHERE SQ1.DB_PROD_CODIGO = SQ2.DB_PRDEMB_PRODUTO
     AND EXISTS
       (SELECT 1
        FROM MERCANET_QA.DB_PRODUTO@DC12 SSQ1
        WHERE SSQ1.DB_PROD_CODIGO = SQ1.DB_PROD_CODIGO
          AND SSQ1.DB_PROD_SITUACAO = 'A')
     AND SQ2.DB_PRDEMB_PRODUTO = SQ3.DB_PRODA_CODIGO
     AND SQ3.DB_PRODA_CODIGO = SQ4.DB_PRODA_CODIGO
     AND SQ4.DB_PRODA_CODIGO = SQ5.DB_PRODA_CODIGO
     AND SQ5.DB_PRODA_CODIGO = SQ6.DB_PRODA_CODIGO
     AND ROWNUM < 4 AND NOT EXISTS (SELECT * FROM DSALES.PRODUTOS_TESTE_ST T1 WHERE SQ2.DB_PRDEMB_PRODUTO = T1.DB_PROD_CODIGO)
     AND DB_PRDEMB_CODEMB = 1
     AND SQ3.DB_PRODA_ATRIB = 2008
     AND SQ4.DB_PRODA_ATRIB = 2014
     AND SQ5.DB_PRODA_ATRIB = 2017
     AND SQ6.DB_PRODA_ATRIB = 2018
     AND SQ3.DB_PRODA_VALOR = 'C'
     AND SQ4.DB_PRODA_VALOR = 'MGN'
     AND SQ5.DB_PRODA_VALOR = 'POS'
     AND SQ6.DB_PRODA_VALOR = 'NAC'
   UNION SELECT 'PROD_C_MGN_POS_IMP' AS TIPO_PRODUTO,
                DB_PROD_CODIGO,
                DB_PROD_DESCRICAO,
                DB_PRDEMB_CODBARRA
   FROM MERCANET_PRD.DB_PRODUTO SQ1,
        MERCANET_PRD.DB_PRODUTO_EMBAL SQ2,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ3,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ4,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ5,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ6
   WHERE SQ1.DB_PROD_CODIGO = SQ2.DB_PRDEMB_PRODUTO
     AND EXISTS
       (SELECT 1
        FROM MERCANET_QA.DB_PRODUTO@DC12 SSQ1
        WHERE SSQ1.DB_PROD_CODIGO = SQ1.DB_PROD_CODIGO
          AND SSQ1.DB_PROD_SITUACAO = 'A')
     AND SQ2.DB_PRDEMB_PRODUTO = SQ3.DB_PRODA_CODIGO
     AND SQ3.DB_PRODA_CODIGO = SQ4.DB_PRODA_CODIGO
     AND SQ4.DB_PRODA_CODIGO = SQ5.DB_PRODA_CODIGO
     AND SQ5.DB_PRODA_CODIGO = SQ6.DB_PRODA_CODIGO
     AND ROWNUM < 4 AND NOT EXISTS (SELECT * FROM DSALES.PRODUTOS_TESTE_ST T1 WHERE SQ2.DB_PRDEMB_PRODUTO = T1.DB_PROD_CODIGO)
     AND DB_PRDEMB_CODEMB = 1
     AND SQ3.DB_PRODA_ATRIB = 2008
     AND SQ4.DB_PRODA_ATRIB = 2014
     AND SQ5.DB_PRODA_ATRIB = 2017
     AND SQ6.DB_PRODA_ATRIB = 2018
     AND SQ3.DB_PRODA_VALOR = 'C'
     AND SQ4.DB_PRODA_VALOR = 'MGN'
     AND SQ5.DB_PRODA_VALOR = 'POS'
     AND SQ6.DB_PRODA_VALOR = 'IMP'
   UNION SELECT 'PROD_C_MGN_NEG_NAC' AS TIPO_PRODUTO,
                DB_PROD_CODIGO,
                DB_PROD_DESCRICAO,
                DB_PRDEMB_CODBARRA
   FROM MERCANET_PRD.DB_PRODUTO SQ1,
        MERCANET_PRD.DB_PRODUTO_EMBAL SQ2,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ3,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ4,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ5,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ6
   WHERE SQ1.DB_PROD_CODIGO = SQ2.DB_PRDEMB_PRODUTO
     AND EXISTS
       (SELECT 1
        FROM MERCANET_QA.DB_PRODUTO@DC12 SSQ1
        WHERE SSQ1.DB_PROD_CODIGO = SQ1.DB_PROD_CODIGO
          AND SSQ1.DB_PROD_SITUACAO = 'A')
     AND SQ2.DB_PRDEMB_PRODUTO = SQ3.DB_PRODA_CODIGO
     AND SQ3.DB_PRODA_CODIGO = SQ4.DB_PRODA_CODIGO
     AND SQ4.DB_PRODA_CODIGO = SQ5.DB_PRODA_CODIGO
     AND SQ5.DB_PRODA_CODIGO = SQ6.DB_PRODA_CODIGO
     AND ROWNUM < 4 AND NOT EXISTS (SELECT * FROM DSALES.PRODUTOS_TESTE_ST T1 WHERE SQ2.DB_PRDEMB_PRODUTO = T1.DB_PROD_CODIGO)
     AND DB_PRDEMB_CODEMB = 1
     AND SQ3.DB_PRODA_ATRIB = 2008
     AND SQ4.DB_PRODA_ATRIB = 2014
     AND SQ5.DB_PRODA_ATRIB = 2017
     AND SQ6.DB_PRODA_ATRIB = 2018
     AND SQ3.DB_PRODA_VALOR = 'C'
     AND SQ4.DB_PRODA_VALOR = 'MGN'
     AND SQ5.DB_PRODA_VALOR = 'NEG'
     AND SQ6.DB_PRODA_VALOR = 'NAC'
   UNION SELECT 'PROD_C_MGN_NEG_IMP' AS TIPO_PRODUTO,
                DB_PROD_CODIGO,
                DB_PROD_DESCRICAO,
                DB_PRDEMB_CODBARRA
   FROM MERCANET_PRD.DB_PRODUTO SQ1,
        MERCANET_PRD.DB_PRODUTO_EMBAL SQ2,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ3,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ4,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ5,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ6
   WHERE SQ1.DB_PROD_CODIGO = SQ2.DB_PRDEMB_PRODUTO
     AND EXISTS
       (SELECT 1
        FROM MERCANET_QA.DB_PRODUTO@DC12 SSQ1
        WHERE SSQ1.DB_PROD_CODIGO = SQ1.DB_PROD_CODIGO
          AND SSQ1.DB_PROD_SITUACAO = 'A')
     AND SQ2.DB_PRDEMB_PRODUTO = SQ3.DB_PRODA_CODIGO
     AND SQ3.DB_PRODA_CODIGO = SQ4.DB_PRODA_CODIGO
     AND SQ4.DB_PRODA_CODIGO = SQ5.DB_PRODA_CODIGO
     AND SQ5.DB_PRODA_CODIGO = SQ6.DB_PRODA_CODIGO
     AND ROWNUM < 4 AND NOT EXISTS (SELECT * FROM DSALES.PRODUTOS_TESTE_ST T1 WHERE SQ2.DB_PRDEMB_PRODUTO = T1.DB_PROD_CODIGO)
     AND DB_PRDEMB_CODEMB = 1
     AND SQ3.DB_PRODA_ATRIB = 2008
     AND SQ4.DB_PRODA_ATRIB = 2014
     AND SQ5.DB_PRODA_ATRIB = 2017
     AND SQ6.DB_PRODA_ATRIB = 2018
     AND SQ3.DB_PRODA_VALOR = 'C'
     AND SQ4.DB_PRODA_VALOR = 'MGN'
     AND SQ5.DB_PRODA_VALOR = 'NEG'
     AND SQ6.DB_PRODA_VALOR = 'IMP'
   UNION SELECT 'PROD_C_MGN_NEU_NAC' AS TIPO_PRODUTO,
                DB_PROD_CODIGO,
                DB_PROD_DESCRICAO,
                DB_PRDEMB_CODBARRA
   FROM MERCANET_PRD.DB_PRODUTO SQ1,
        MERCANET_PRD.DB_PRODUTO_EMBAL SQ2,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ3,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ4,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ5,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ6
   WHERE SQ1.DB_PROD_CODIGO = SQ2.DB_PRDEMB_PRODUTO
     AND EXISTS
       (SELECT 1
        FROM MERCANET_QA.DB_PRODUTO@DC12 SSQ1
        WHERE SSQ1.DB_PROD_CODIGO = SQ1.DB_PROD_CODIGO
          AND SSQ1.DB_PROD_SITUACAO = 'A')
     AND SQ2.DB_PRDEMB_PRODUTO = SQ3.DB_PRODA_CODIGO
     AND SQ3.DB_PRODA_CODIGO = SQ4.DB_PRODA_CODIGO
     AND SQ4.DB_PRODA_CODIGO = SQ5.DB_PRODA_CODIGO
     AND SQ5.DB_PRODA_CODIGO = SQ6.DB_PRODA_CODIGO
     AND ROWNUM < 4 AND NOT EXISTS (SELECT * FROM DSALES.PRODUTOS_TESTE_ST T1 WHERE SQ2.DB_PRDEMB_PRODUTO = T1.DB_PROD_CODIGO)
     AND DB_PRDEMB_CODEMB = 1
     AND SQ3.DB_PRODA_ATRIB = 2008
     AND SQ4.DB_PRODA_ATRIB = 2014
     AND SQ5.DB_PRODA_ATRIB = 2017
     AND SQ6.DB_PRODA_ATRIB = 2018
     AND SQ3.DB_PRODA_VALOR = 'C'
     AND SQ4.DB_PRODA_VALOR = 'MGN'
     AND SQ5.DB_PRODA_VALOR = 'NEU'
     AND SQ6.DB_PRODA_VALOR = 'NAC'
   UNION SELECT 'PROD_C_MGN_NEU_IMP' AS TIPO_PRODUTO,
                DB_PROD_CODIGO,
                DB_PROD_DESCRICAO,
                DB_PRDEMB_CODBARRA
   FROM MERCANET_PRD.DB_PRODUTO SQ1,
        MERCANET_PRD.DB_PRODUTO_EMBAL SQ2,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ3,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ4,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ5,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ6
   WHERE SQ1.DB_PROD_CODIGO = SQ2.DB_PRDEMB_PRODUTO
     AND EXISTS
       (SELECT 1
        FROM MERCANET_QA.DB_PRODUTO@DC12 SSQ1
        WHERE SSQ1.DB_PROD_CODIGO = SQ1.DB_PROD_CODIGO
          AND SSQ1.DB_PROD_SITUACAO = 'A')
     AND SQ2.DB_PRDEMB_PRODUTO = SQ3.DB_PRODA_CODIGO
     AND SQ3.DB_PRODA_CODIGO = SQ4.DB_PRODA_CODIGO
     AND SQ4.DB_PRODA_CODIGO = SQ5.DB_PRODA_CODIGO
     AND SQ5.DB_PRODA_CODIGO = SQ6.DB_PRODA_CODIGO
     AND ROWNUM < 4 AND NOT EXISTS (SELECT * FROM DSALES.PRODUTOS_TESTE_ST T1 WHERE SQ2.DB_PRDEMB_PRODUTO = T1.DB_PROD_CODIGO)
     AND DB_PRDEMB_CODEMB = 1
     AND SQ3.DB_PRODA_ATRIB = 2008
     AND SQ4.DB_PRODA_ATRIB = 2014
     AND SQ5.DB_PRODA_ATRIB = 2017
     AND SQ6.DB_PRODA_ATRIB = 2018
     AND SQ3.DB_PRODA_VALOR = 'C'
     AND SQ4.DB_PRODA_VALOR = 'MGN'
     AND SQ5.DB_PRODA_VALOR = 'NEU'
     AND SQ6.DB_PRODA_VALOR = 'IMP'
   UNION SELECT 'PROD_L' AS TIPO_PRODUTO,
                DB_PROD_CODIGO,
                DB_PROD_DESCRICAO,
                DB_PRDEMB_CODBARRA
   FROM MERCANET_PRD.DB_PRODUTO SQ1,
        MERCANET_PRD.DB_PRODUTO_EMBAL SQ2,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ3
   WHERE SQ1.DB_PROD_CODIGO = SQ2.DB_PRDEMB_PRODUTO
     AND EXISTS
       (SELECT 1
        FROM MERCANET_QA.DB_PRODUTO@DC12 SSQ1
        WHERE SSQ1.DB_PROD_CODIGO = SQ1.DB_PROD_CODIGO
          AND SSQ1.DB_PROD_SITUACAO = 'A')
     AND SQ2.DB_PRDEMB_PRODUTO = SQ3.DB_PRODA_CODIGO
     AND ROWNUM < 4 AND NOT EXISTS (SELECT * FROM DSALES.PRODUTOS_TESTE_ST T1 WHERE SQ2.DB_PRDEMB_PRODUTO = T1.DB_PROD_CODIGO) 
     AND DB_PRDEMB_CODEMB = 1
     AND SQ3.DB_PRODA_ATRIB = 2008
     AND SQ3.DB_PRODA_VALOR = 'L'
   UNION SELECT 'PROD_HPC' AS TIPO_PRODUTO,
                DB_PROD_CODIGO,
                DB_PROD_DESCRICAO,
                DB_PRDEMB_CODBARRA
   FROM MERCANET_PRD.DB_PRODUTO SQ1,
        MERCANET_PRD.DB_PRODUTO_EMBAL SQ2,
        MERCANET_PRD.DB_PRODUTO_ATRIB SQ3
   WHERE SQ1.DB_PROD_CODIGO = SQ2.DB_PRDEMB_PRODUTO
     AND EXISTS
       (SELECT 1
        FROM MERCANET_QA.DB_PRODUTO@DC12 SSQ1
        WHERE SSQ1.DB_PROD_CODIGO = SQ1.DB_PROD_CODIGO
          AND SSQ1.DB_PROD_SITUACAO = 'A')
     AND SQ2.DB_PRDEMB_PRODUTO = SQ3.DB_PRODA_CODIGO
     AND ROWNUM < 4 AND NOT EXISTS (SELECT * FROM DSALES.PRODUTOS_TESTE_ST T1 WHERE SQ2.DB_PRDEMB_PRODUTO = T1.DB_PROD_CODIGO)
     AND DB_PRDEMB_CODEMB = 1
     AND SQ3.DB_PRODA_ATRIB = 2009
     AND SQ3.DB_PRODA_VALOR = 'DEPHPC') PRODUTOS ,
  (SELECT *
   FROM
     (SELECT TRIM(IBLITM) PRODUTO,
             (SUM(LIPQOH - (LIPCOM + LIHCOM))) - MAX(IBSAFE) DISPONIBILIDADE
      FROM QADTA.F4101@DC10,
        (SELECT *
         FROM
           (SELECT *
            FROM QADTA.f4102@DC10,
                 QADTA.f41021@DC10
            WHERE ibmcu = '    DIFARCAT'
              AND liitm = ibitm
              AND lilocn NOT IN ('ENTRADA',
                                 'VENCIDO',
                                 'DEVOL')
              AND ibstkt != 'O'
            UNION SELECT *
            FROM QADTA.f4102@DC10,
                 QADTA.f41021@DC10
            WHERE ibmcu = '    DIFARCAT'
              AND liitm = ibitm
              AND lilocn = 'ENTRADA'
              AND ibstkt != 'O'
              AND lilotn = ' '
            UNION SELECT *
            FROM QADTA.f4102@DC10,
                 QADTA.f41021@DC10
            WHERE ibmcu = '     DIFARES'
              AND ibshcn = 'ES'
              AND liitm = ibitm
              AND lilocn NOT IN ('ENTRADA',
                                 'VENCIDO',
                                 'DEVOL')
              AND ibstkt != 'O'
            UNION SELECT *
            FROM QADTA.f4102@DC10,
                 QADTA.f41021@DC10
            WHERE ibmcu = '     DIFARES'
              AND ibshcn = 'ES'
              AND liitm = ibitm
              AND lilocn = 'ENTRADA'
              AND ibstkt != 'O'
              AND lilotn = ' '
            UNION SELECT *
            FROM QADTA.f4102@DC10,
                 QADTA.f41021@DC10
            WHERE ibmcu = '     DIFARMA'
              AND ibshcn = 'COL'
              AND liitm = ibitm
              AND lilocn NOT IN ('ENTRADA',
                                 'VENCIDO',
                                 'DEVOL')
              AND ibstkt != 'O'
            UNION SELECT *
            FROM QADTA.f4102@DC10,
                 QADTA.f41021@DC10
            WHERE ibmcu = '     DIFARMA'
              AND ibshcn = 'COL'
              AND liitm = ibitm
              AND lilocn = 'ENTRADA'
              AND ibstkt != 'O'
              AND lilotn = ' ')
         WHERE IBITM IN
             (SELECT imitm
              FROM qadta.f4101@DC10
              WHERE imshcn NOT IN ('ES',
                                   'COL')))
      WHERE IMITM = IBITM
      GROUP BY IBLITM)
   WHERE DISPONIBILIDADE > 10) ESTOQUE
WHERE PRODUTO = DB_PROD_CODIGO
ORDER BY TIPO_PRODUTO,
         DB_PROD_CODIGO




