--Rodar no DC01
SELECT PDVEN_D.SDDOCO AS PEDIDO_DROGACENTER,
       PDVEN_D.SDEUSE AS COD_ORIGEM_PED,
       SAAA25 AS PED_EFETIVACAO,
       TO_DATE(NFVEN_D.FDISSU + 1900000, 'YYYYDDD') AS DATA_EMISSAO_NF,
       NFVEN_H.FHBNNF AS NOTA_VENDA,
       NFVEN_H.FHBSER AS SERIE,
       ROUND(NFVEN_H.FHBVTN / 100, 2) AS VALOR_TOTAL_NOTA_VENDA,
       NFDEV_D.FDDOCO AS PEDIDO_DEVOLUCAO,
       TO_DATE(NFDEV_H.FHADDJ + 1900000, 'YYYYDDD') AS DATA_ENTRADA_DEVOLUCAO,
       TO_DATE(NFDEV_D.FDISSU + 1900000, 'YYYYDDD') AS DATA_EMISSAO_NOTA_DEVOLUCAO,
       NFDEV_H.FHBNNF AS NOTA_DEVOLUCAO,
       NFDEV_H.FHBSER AS SERIE,
       NFDEV_H.FHN001 AS SEQUENCIA,
       NFDEV_H.FHDCT AS TIPO_NOTA_DEVOLUCAO,
       ROUND(NFDEV_H.FHBVTN / 100, 2) AS VALOR_TOTAL_NOTA_DEVOLUCAO,
       SUM(ROUND(((CASE
                   WHEN NFVEN_D.FDBVIS = 0 THEN
                    (SELECT ROUND(EDM010 / 100, 2)
                       FROM PRODDTA.F555511
                      WHERE NFVEN_D.FDBNNF = EDBNNF
                        AND NFVEN_D.FDBSER = EDBSER
                        AND NFVEN_D.FDN001 = EDN001
                        AND NFVEN_D.FDLNID = EDLNID)
                   ELSE
                    NFVEN_D.FDBVIS / 100
                 END / NFVEN_D.FDUORG) * NFDEV_D.FDUORG),
                 2)) as VALOR_TOTAL_ST_DEVOLUCAO,
       (ROUND(NFDEV_H.FHBVTN / 100, 2) -
       SUM(ROUND(((CASE
                    WHEN NFVEN_D.FDBVIS = 0 THEN
                     (SELECT ROUND(EDM010 / 100, 2)
                        FROM PRODDTA.F555511
                       WHERE NFVEN_D.FDBNNF = EDBNNF
                         AND NFVEN_D.FDBSER = EDBSER
                         AND NFVEN_D.FDN001 = EDN001
                         AND NFVEN_D.FDLNID = EDLNID)
                    ELSE
                     NFVEN_D.FDBVIS / 100
                  END / NFVEN_D.FDUORG) * NFDEV_D.FDUORG),
                  2))) AS TOTAL_DEVOLUCAO_SEM_TRIBUTACAO,
       /*CASE
         WHEN PDVEN_D.SDPA8 IN (35132, 633933) THEN
          0.3
         ELSE
          0.5
       END*/
       0.3 AS "FATOR_%_PAGAMENTO"

  FROM PRODDTA.F7601B   NFVEN_H,
       PRODDTA.F7611B   NFVEN_D,
       PRODDTA.F42119   PDVEN_D,
       PRODDTA.F42119   PDDEV_D,
       PRODDTA.F42199   VINC,
       PRODDTA.F7601B   NFDEV_H,
       PRODDTA.F7611B   NFDEV_D,
       PRODDTA.F5547011
 WHERE
-- NFVEN_H (F7601B) X NFVEN_D (F7611B)
 NFVEN_H.FHBNNF = NFVEN_D.FDBNNF
 AND NFVEN_H.FHBSER = NFVEN_D.FDBSER
 AND NFVEN_H.FHN001 = NFVEN_D.FDN001
 AND NFVEN_H.FHDCT = NFVEN_D.FDDCT
-- NFDEV_H (F7601B) X NFDEV_D (F7611B)
 AND NFDEV_H.FHBNNF = NFDEV_D.FDBNNF
 AND NFDEV_H.FHBSER = NFDEV_D.FDBSER
 AND NFDEV_H.FHN001 = NFDEV_D.FDN001
 AND NFDEV_H.FHDCT = NFDEV_D.FDDCT
-- NFVEN_D (F7611B) X PDVEN_D (F42119)
 AND NFVEN_D.FDKCOO = PDVEN_D.SDKCOO
 AND NFVEN_D.FDDOCO = PDVEN_D.SDDOCO
 AND NFVEN_D.FDPDCT = PDVEN_D.SDDCTO
 AND NFVEN_D.FDLNID = PDVEN_D.SDLNID
 AND NFVEN_D.FDLITM = PDVEN_D.SDLITM
-- PDVEN_D (F42119) X PDDEV_D (F42119)
 AND PDVEN_D.SDDOC = PDDEV_D.SDODOC
 AND TRIM(PDVEN_D.SDDCT) = TRIM(PDDEV_D.SDODCT)
 AND TRIM(PDVEN_D.SDITM) = PDDEV_D.SDITM
 AND PDDEV_D.SDLTTR NOT BETWEEN '980' AND '989'
-- VINC (F42199) X PDDEV_D (F42119)
 AND VINC.SLKCOO = PDDEV_D.SDOKCO
 AND VINC.SLDOCO = NVL(TRIM(PDDEV_D.SDOORN), 0)
 AND VINC.SLDCTO = PDDEV_D.SDOCTO
 AND VINC.SLLNID = PDDEV_D.SDOGNO
-- VINC (F42199) X NFVEN_D (F7611B)
 AND VINC.SLRKCO = NFVEN_D.FDKCOO
 AND NVL(TRIM(VINC.SLRORN), 0) = NFVEN_D.FDDOCO
 AND VINC.SLRCTO = NFVEN_D.FDPDCT
 AND VINC.SLRLLN = NFVEN_D.FDLNID
 AND VINC.SLITM = NFVEN_D.FDITM
-- NFDEV_D (F7611B) X PDDEV_D (F42119)
 AND NFDEV_D.FDKCOO = PDDEV_D.SDKCOO
 AND NFDEV_D.FDDOCO = PDDEV_D.SDDOCO
 AND NFDEV_D.FDPDCT = PDDEV_D.SDDCTO
 AND NFDEV_D.FDLNID = PDDEV_D.SDLNID
 AND NFDEV_D.FDLITM = PDDEV_D.SDLITM
--
 AND NFDEV_H.FHADDJ BETWEEN 117091 AND 117120 --Colocar o Mes corrente da Conciliacao do pagamento Cotefácil
 AND PDVEN_D.SDEUSE = 'PTC'
 AND PDVEN_D.SDDOCO = SADOCO
--AND PDVEN_D.SDTRDJ > 115181 --Aqui esta 1 de Julho 2015 -- Data em que começou-se a rodar o relatorio de pagamento da Cotefácil
 GROUP BY PDVEN_D.SDDOCO,
          SAAA25,
          NFVEN_D.FDISSU,
          NFVEN_H.FHBNNF,
          NFVEN_H.FHBSER,
          NFVEN_H.FHBVTN,
          PDVEN_D.SDEUSE,
          NFDEV_D.FDDOCO,
          NFDEV_H.FHADDJ,
          NFDEV_D.FDISSU,
          NFDEV_H.FHBNNF,
          NFDEV_H.FHBSER,
          NFDEV_H.FHN001,
          NFDEV_H.FHDCT,
          NFDEV_H.FHBVTN,
          PDVEN_D.SDPA8
