--LEVANTAMENTO SEVEN PDV  - ASTRAZENECA

--SELECT CNPJ PDV, NOTA_FISCAL, EAN, DATA_NOTA e QTDE_FATUR
SELECT * FROM 
(
SELECT DB_EDIP_OBS1 AS NRO_ARQUIVO,
       DB_EDII_COMPRADOR AS CNPJ_PDV,
       DB_NOTA_NRO AS NOTA_FISCAL,
       DB_EDII_PRODUTO AS EAN,
       DB_NOTA_DT_EMISSAO AS DATA_NOTA,
       DB_NOTAP_QTDE AS QUANTIDADE_FATURADA,
       DB_EDILE_ARQUIVO AS NOME_ARQUIVO_RPDAT
  FROM MERCANET_PRD.DB_EDI_PEDIDO,
       MERCANET_PRD.DB_EDI_PEDPROD,
       MERCANET_PRD.DB_PEDIDO_DISTR_IT,
       MERCANET_PRD.DB_PEDIDO_PROD,
       MERCANET_PRD.DB_NOTA_FISCAL,
       MERCANET_PRD.DB_NOTA_PROD,
       (SELECT *
          FROM (SELECT *
                  FROM MERCANET_PRD.DB_EDI_LOG_EXP
                UNION ALL
                SELECT * FROM MERCANET_PRD.DB_EDI_LOG_EXP_HIST))
 WHERE DB_EDIP_COMPRADOR = DB_EDII_COMPRADOR
   AND DB_EDIP_NRO = DB_EDII_NRO
   AND DB_EDIP_VAN = 508
   AND DB_EDIP_PROJETO = 42
   AND DB_EDIP_DT_EMISSAO BETWEEN '01/11/2015' AND '31/01/2016'
   AND DB_EDII_PEDMERC = DB_PDIT_PEDIDO
   AND DB_EDII_SEQ = DB_PDIT_EDII_SEQ
   AND DB_PDIT_PEDIDO = DB_PEDI_PEDIDO
   AND DB_PDIT_PEDI_SEQ = DB_PEDI_SEQUENCIA
   AND DB_EDII_MOTIVORET IN ('100', '000')
   AND DB_NOTA_NRO = DB_NOTAP_NRO
   AND DB_NOTA_SERIE = DB_NOTAP_SERIE
   AND DB_NOTA_EMPRESA = DB_NOTAP_EMPRESA
   AND DB_PEDI_PEDIDO = DB_NOTA_PED_MERC
   AND DB_PEDI_PRODUTO = DB_NOTAP_PRODUTO
   AND DB_NOTA_FATUR <> 3
   AND DB_EDIP_COMPRADOR = DB_EDILE_EDIP_COMP
   AND DB_EDIP_NRO = DB_EDILE_EDIP_NRO
   AND DB_EDILE_EDIA_CODI = 'SEVENPDV_NOT'
   AND INSTR(DB_EDILE_CONTEUDO, DB_NOTA_NRO) > 0
   AND INSTR(DB_EDILE_CONTEUDO, DB_EDIP_COMPRADOR) > 0
   AND INSTR(DB_EDILE_CONTEUDO, DB_EDII_PRODUTO) > 0
   AND INSTR(DB_EDILE_CONTEUDO, DB_EDIP_OBS1) > 0
   UNION 
   SELECT DB_EDIP_OBS1 AS NRO_ARQUIVO,
       DB_EDII_COMPRADOR AS CNPJ_PDV,
       TO_NUMBER(TO_CHAR(SUBSTR(DB_PEDI_ATD_DCTO,1,6))) AS NOTA_FISCAL,
       DB_EDII_PRODUTO AS EAN,
       TO_DATE(TO_CHAR(SUBSTR(DB_EDILE_CONTEUDO,57,8)),'YYYYMMDD') AS DATA_NOTA,
       TO_NUMBER(TO_CHAR(SUBSTR(DB_EDILE_CONTEUDO,38,4))) AS QUANTIDADE_FATURADA,
       DB_EDILE_ARQUIVO AS NOME_ARQUIVO_RPDAT
  FROM MERCANET_PRD.DB_EDI_PEDIDO,
       MERCANET_PRD.DB_EDI_PEDPROD,
       MERCANET_PRD.DB_PEDIDO_DISTR_IT,
       MERCANET_PRD.DB_PEDIDO_PROD,
       (SELECT *
          FROM (SELECT *
                  FROM MERCANET_PRD.DB_EDI_LOG_EXP
                UNION ALL
                SELECT * FROM MERCANET_PRD.DB_EDI_LOG_EXP_HIST))
 WHERE DB_EDIP_COMPRADOR = DB_EDII_COMPRADOR
   AND DB_EDIP_NRO = DB_EDII_NRO
   AND DB_EDIP_VAN = 508
   AND DB_EDIP_PROJETO = 42
   AND DB_EDIP_DT_EMISSAO BETWEEN '01/11/2015' AND '31/01/2016'
   AND DB_EDII_MOTIVORET IN ('100', '000')
   AND DB_EDII_PEDMERC = DB_PDIT_PEDIDO
   AND DB_EDII_SEQ = DB_PDIT_EDII_SEQ
   AND DB_PDIT_PEDIDO = DB_PEDI_PEDIDO
   AND DB_PDIT_PEDI_SEQ = DB_PEDI_SEQUENCIA
   AND DB_EDIP_COMPRADOR = DB_EDILE_EDIP_COMP
   AND DB_EDIP_NRO = DB_EDILE_EDIP_NRO
   AND DB_EDILE_EDIA_CODI = 'SEVENPDV_NOT'
   AND INSTR(DB_EDILE_CONTEUDO, SUBSTR(DB_PEDI_ATD_DCTO,1,6)) > 0
   AND INSTR(DB_EDILE_CONTEUDO, DB_EDIP_COMPRADOR) > 0
   AND INSTR(DB_EDILE_CONTEUDO, DB_EDII_PRODUTO) > 0
   AND INSTR(DB_EDILE_CONTEUDO, DB_EDIP_OBS1) > 0
   AND NOT EXISTS (SELECT * 
                     FROM MERCANET_PRD.DB_NOTA_FISCAL,
                          MERCANET_PRD.DB_NOTA_PROD
                    WHERE DB_NOTA_NRO = DB_NOTAP_NRO
                      AND DB_NOTA_SERIE = DB_NOTAP_SERIE
                      AND DB_NOTA_EMPRESA = DB_NOTAP_EMPRESA
                      AND DB_PEDI_PEDIDO = DB_NOTA_PED_MERC
                      AND DB_PEDI_PRODUTO = DB_NOTAP_PRODUTO
                      AND DB_NOTA_FATUR <> 3 ))

