--exemplo 1

select  , RTRIM(XMLAGG(XMLELEMENT(e, A.POLITICA || ' # ' )).extract('//text()'),',') as "TAG_POLIT._AGRUPADAS"
  from MERCANET_PRD.DB_PEDIDO_DESCONTO, MERCANET_PRD.D
GROUP BY A.POLITICA;

--exemplo 2 
SELECT SUBSTR(RTRIM(XMLAGG(XMLELEMENT(e, ' + ' || DB_PEDD_CODPOL || ' = ' ||ROUND(DB_PEDD_DESCONTO, 2)||'%') ORDER BY DB_PEDD_SEQAPLIQ)
             .extract('//text()'),
             ','),4,100) as "TAG_POLIT._AGRUPADAS"
  FROM MERCANET_QA.DB_PEDIDO_DESCONTO, MERCANET_QA.DB_PEDIDO_PROD
 WHERE DB_PEDD_NRO = DB_PEDI_PEDIDO
   AND DB_PEDD_SEQIT = DB_PEDI_SEQUENCIA
   AND DB_PEDI_PEDIDO = 80483317
 GROUP BY DB_PEDI_PEDIDO, DB_PEDI_PRODUTO

--CONCATENAR TAG DOS FILTROS

DECLARE
  V_FILTROS       VARCHAR2(200) := '';
  V_TOTAL_FILTROS NUMBER := 0;

BEGIN

  FOR REGRAS IN (SELECT PV06_POLITICA AS POLITICA,
                        PV05_CONTROLE AS CONTROLE,
                        MAX(PV05_SEQ) AS TOTAL_FILTROS
                   FROM MERCANET_QA.MPV05, MERCANET_QA.MPV06
                  WHERE PV05_CONTROLE = PV06_CONTROLE
                    AND PV06_TIPO = 'A'
                  GROUP BY PV06_POLITICA, PV05_CONTROLE
                  ORDER BY PV06_POLITICA) LOOP
    FOR X IN (SELECT *
                FROM MERCANET_QA.MPV05 TB_FILTROS
               WHERE REGRAS.CONTROLE = TB_FILTROS.PV05_CONTROLE) LOOP
      V_FILTROS := V_FILTROS || X.PV05_TAGFILTRO || CASE
                     WHEN X.PV05_SEQ < REGRAS.TOTAL_FILTROS THEN
                      ' # '
                     ELSE
                      ''
                   END;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('POLITICA: ' || REGRAS.POLITICA || ': ' ||
                         'FILTROS UTILIZADOS: ' || V_FILTROS);
  
    V_FILTROS := '';
  END LOOP;
END;

