SELECT DB_PED_NRO,DB_PED_CLIENTE,DB_PED_DT_EMISSAO,DB_PED_SITUACAO,DB_PED_NRO_ORIG,
       DB_PED_EMPRESA,DB_PED_TIPO,DB_PED_SITCORP,DB_EDIP_COMPRADOR,DB_EDIP_NRO,DB_EDIP_LOTE,
       DB_EDIP_VAN,DB_EDIP_PROJETO
  FROM MERCANET_PRD.DB_PEDIDO T1, MERCANET_PRD.DB_PEDIDO_DISTR T2, MERCANET_PRD.DB_EDI_PEDIDO T3
 WHERE T1.DB_PED_NRO = T2.DB_PEDT_PEDIDO
   AND T2.DB_PEDT_DTDISP IS NOT NULL
   AND T1.DB_PED_SITCORP IN ('3', '4', '0')
   AND T1.DB_PED_SITUACAO IN ('0', '2', '3', '4')
   AND t3.db_edip_dt_emissao > to_date('13/07/2014 00:00:00','dd/mm/yyyy hh24:mi:ss')
   AND t3.db_edip_dt_emissao < to_date('18/07/2014 00:00:00','dd/mm/yyyy hh24:mi:ss')
   AND T2.DB_PEDT_PEDIDO = T3.DB_EDIP_PEDMERC
/*   AND EXISTS (SELECT * FROM MERCANET_PRD.MEM01 P1
                WHERE P1.EM01_CODIGO = T3.DB_EDIP_VAN
                  AND P1.EM01_LARQNF IS NOT NULL)*/
   AND NOT EXISTS
 (SELECT *
          FROM MERCANET_PRD.DB_NOTA_FISCAL NF
         WHERE T1.DB_PED_NRO_ORIG = NF.DB_NOTA_PED_ORIG
           AND T1.DB_PED_NRO = NF.DB_NOTA_PED_MERC
           AND T1.DB_PED_CLIENTE = NF.DB_NOTA_CLIENTE
           AND DECODE(T1.DB_PED_EMPRESA, 104, 103, T1.DB_PED_EMPRESA) =
               NF.DB_NOTA_EMPRESA)
