SELECT * FROM MEM01  WHERE EM01_CODIGO = 505;

SELECT * FROM MEM03  WHERE EM03_DISTR = 505;

SELECT * FROM MEM04  WHERE EM04_DISTR = 505 ORDER BY EM04_TAG;

SELECT * FROM MEM05  WHERE EM05_DISTR = 505;

SELECT * FROM MEM06 WHERE EM06_DISTR = 505 ORDER BY EM06_ID;

SELECT * FROM MEM07  WHERE EM07_DISTR = 505;

SELECT *
  FROM DB_EDI_LARQUIVO 
 WHERE DB_EDIA_CODIGO LIKE ('ENT%')
 ORDER BY DB_EDIA_CODIGO;

SELECT *
  FROM DB_EDI_LREGISTRO
 WHERE DB_EDIR_CODIGO LIKE ('ENT%')
 ORDER BY DB_EDIR_CODIGO, DB_EDIR_TIPO, DB_EDIR_SEQ;

SELECT *
  FROM DB_EDI_LREGSAI 
 WHERE DB_EDIS_CODIGO LIKE ('ENT%')
 ORDER BY DB_EDIS_CODIGO, DB_EDIS_SREG, DB_EDIS_SEQ;

SELECT DB_EDIS_CODIGO,
       DB_EDIC_CODIGO,
       DB_EDIC_DESCR,
       DB_EDIC_TIPO,
       DB_EDIC_EXPRESSAO
  FROM DB_EDI_LCPOSAI, DB_EDI_LREGSAI
 WHERE DB_EDIS_CODIGO LIKE ('ENT%')
   AND DB_EDIS_CAMPO = DB_EDIC_CODIGO

 ORDER BY DB_EDIS_CODIGO ASC