/*SELECT DB_EDIP_COMPRADOR,
       DB_EDIP_NRO,
       DB_EDIP_PROJETO,
       DB_EDII_COMPRADOR,
       DB_EDII_NRO,
       DB_EDII_PROJETO
  FROM MERCANET_PRD.DB_EDI_PEDIDO, MERCANET_PRD.DB_EDI_PEDPROD
 WHERE DB_EDIP_COMPRADOR = DB_EDII_COMPRADOR
   AND DB_EDIP_NRO = DB_EDII_NRO
   AND DB_EDIP_LOTE = 386157; 
   */

SELECT 'UPDATE MERCANET_PRD.DB_EDI_PEDPROD SET DB_EDII_PROJETO = '|| ''''||DB_EDIP_PROJETO||'''' || 
       '  WHERE DB_EDII_COMPRADOR = '|| ''''||DB_EDII_COMPRADOR||''''||
       ' AND DB_EDII_NRO = '|| ''''||DB_EDII_NRO||''''||';'
  FROM MERCANET_PRD.DB_EDI_PEDIDO, MERCANET_PRD.DB_EDI_PEDPROD, MERCANET_PRD.DB_EDI_LOTE_DISTR
 WHERE DB_EDIP_COMPRADOR = DB_EDII_COMPRADOR
   AND DB_EDIP_NRO = DB_EDII_NRO
   AND DB_EDIP_LOTE = DB_EDILD_SEQ
   AND DB_EDIP_VAN = 508
   AND DB_EDILD_DATA BETWEEN TO_DATE('17/07/2012 00:00:00','DD/MM/YYYY HH24:MI:SS')
                         AND TO_DATE('19/07/2012 10:00:00','DD/MM/YYYY HH24:MI:SS')

------

SELECT B.*
  FROM MERCANET_PRD.DB_EDI_PEDIDO A, MERCANET_PRD.DB_EDI_PEDPROD B, MERCANET_PRD.DB_EDI_LOTE_DISTR C
 WHERE DB_EDIP_COMPRADOR = DB_EDII_COMPRADOR
   AND DB_EDIP_NRO = DB_EDII_NRO
   AND DB_EDIP_LOTE = DB_EDILD_SEQ
   AND DB_EDIP_VAN = 508
   AND DB_EDILD_DATA BETWEEN TO_DATE('19/07/2012 11:00:00','DD/MM/YYYY HH24:MI:SS')
                         AND TO_DATE('19/07/2012 17:00:00','DD/MM/YYYY HH24:MI:SS')
 
 
 
 
