SELECT A.DB_EDILD_NOMEARQ AS "ARQUIVO",
       A.DB_EDILD_DATA AS "DATA/HORA PROCESSAMENTO",
       B.DB_EDIP_TXT1 AS "Nº DA COTACAO",
       B.DB_EDIP_TXT2 AS "Nº DO PEDIDO COTEFACIL",
       B.DB_EDIP_PEDMERC AS "Nº DO PEDIDO DCENTER",
       B.DB_EDIP_COMPRADOR AS "CNPJ DO CLIENTE",
       C.DB_CLI_NOME AS "DESCRICAO DO CLIENTE",
       D.DB_CLIA_VALOR || ' - ' ||
       (SELECT AT03_DESCRICAO
          FROM MERCANET_PRD.MAT03
         WHERE AT03_ATRIB = D.DB_CLIA_ATRIB
           AND AT03_CODIGO = D.DB_CLIA_VALOR) AS "REGIAO_COMERCIAL",
       B.DB_EDIP_CLIENTE AS "CNPJ DA FILIAL",
       E.DB_NOTA_NRO AS "NUMERO DA NOTA",
       NVL((SUBSTR(E.DB_NOTA_OBSERV, 45, 2)), '') AS "SERIE",
       NVL((SUBSTR(E.DB_NOTA_OBSERV, 1, 44)), 0) AS "CHAVE DA NOTA FISCAL",
       (DB_NOTA_VLR_TOTAL) AS "VALOR_TOTAL_NOTA",
       NVL((SELECT SUM(Case
                        When NVL(DB_NOTAP_VLR_SUBST, 0) = 0 Then
                         NVL(DB_NOTAP_VLR_DESCT, 0)
                        Else
                         NVL(DB_NOTAP_VLR_SUBST, 0)
                      End)
             FROM MERCANET_PRD.DB_NOTA_PROD   F2,
                  MERCANET_PRD.DB_NOTA_FISCAL E2
            WHERE F2.DB_NOTAP_NRO = E2.DB_NOTA_NRO
              AND F2.DB_NOTAP_SERIE = E2.DB_NOTA_SERIE
              AND F2.DB_NOTAP_EMPRESA = E2.DB_NOTA_EMPRESA
              AND E2.DB_NOTA_PED_MERC = E.DB_NOTA_PED_MERC
              AND E2.DB_NOTA_NRO = E.DB_NOTA_NRO
              AND E2.DB_NOTA_SERIE = E.DB_NOTA_SERIE
              AND E2.DB_NOTA_EMPRESA = E.DB_NOTA_EMPRESA),
           0) AS "VALOR_TOTAL_TRIBUTACAO",
       (DB_NOTA_VLR_TOTAL) -
       NVL((SELECT SUM(Case
                        When NVL(DB_NOTAP_VLR_SUBST, 0) = 0 Then
                         NVL(DB_NOTAP_VLR_DESCT, 0)
                        Else
                         NVL(DB_NOTAP_VLR_SUBST, 0)
                      End)
             FROM MERCANET_PRD.DB_NOTA_PROD   F2,
                  MERCANET_PRD.DB_NOTA_FISCAL E2
            WHERE F2.DB_NOTAP_NRO = E2.DB_NOTA_NRO
              AND F2.DB_NOTAP_SERIE = E2.DB_NOTA_SERIE
              AND F2.DB_NOTAP_EMPRESA = E2.DB_NOTA_EMPRESA
              AND E2.DB_NOTA_PED_MERC = E.DB_NOTA_PED_MERC
              AND E2.DB_NOTA_NRO = E.DB_NOTA_NRO
              AND E2.DB_NOTA_SERIE = E.DB_NOTA_SERIE
              AND E2.DB_NOTA_EMPRESA = E.DB_NOTA_EMPRESA),
           0) AS "TOTAL_NOTA_SEM_TRIBUTACAO",
       /*CASE
         WHEN DB_CLI_VINCULO in (35132, 633933) THEN
          0.3
         ELSE
          0.5
       END*/
       0.3 AS "FATOR_%_PAGAMENTO"

  FROM MERCANET_PRD.DB_EDI_LOTE_DISTR A,
       MERCANET_PRD.DB_EDI_PEDIDO     B,
       MERCANET_PRD.DB_CLIENTE        C,
       MERCANET_PRD.DB_CLIENTE_ATRIB  D,
       MERCANET_PRD.DB_NOTA_FISCAL    E
 WHERE A.DB_EDILD_SEQ = B.DB_EDIP_LOTE
   AND A.DB_EDILD_DISTR = 530
   AND A.DB_EDILD_DATA BETWEEN
       TO_DATE('01/04/2017 00:00:00', 'DD/MM/YYYY HH24:MI:SS') AND --Informar a Data do Inicio e Fim do Mes corrente ao Pagamento
       TO_DATE('30/04/2017 23:59:59', 'DD/MM/YYYY HH24:MI:SS')
   AND B.DB_EDIP_COMPRADOR = C.DB_CLI_CGCMF
   AND C.DB_CLI_CODIGO = D.DB_CLIA_CODIGO
   AND D.DB_CLIA_ATRIB = 1001
   AND B.DB_EDIP_PEDMERC = E.DB_NOTA_PED_MERC
 ORDER BY A.DB_EDILD_DATA, B.DB_EDIP_NRO
