INSERT INTO CRPDTA.F5542525 (SCDOCO,SCDCTO,SCKCOO,SCLNID,SCSEQ,SCALIN,SCUKID,SCLITM,SCCITM,SCUOM,SCSOQS,SCSOBK,SCSOCN,SCMCU,SCLOCN,SCLOTN,SCEDSP)
SELECT SDDOCO  AS SCDOCO,
       SDDCTO  AS SCDCTO,
       SDKCOO  AS SCKCOO,
       SDLNID  AS SCLNID,
       PDSEQ   AS SCSEQ,
       0       AS SCALIN,
       PDUKID  AS SCUKID,
       PDLITM  AS SCLITM,
       PDCITM  AS SCCITM,
       PDUOM   AS SCUOM,
       PDUORG  AS SCSOQS,
       0       AS SCSOBK,
       0       AS SCSOCN,
       PDMCU   AS SCMCU,
       PDLOCN  AS SCLOCN,
       CASE
         WHEN PDLOTN = ' ' THEN
          (SELECT LILOTN
             FROM CRPDTA.F41021
            WHERE LIITM = PDITM
              AND LIMCU = PDMCU
              AND LILOCN = PDLOCN
              AND LILOTN != ' '
              AND (LIPQOH - LIHCOM) > PDUORG
              AND ROWNUM = 1)
         ELSE
          PDLOTN
       END     AS SCLOTN,
       ' '     AS SCEDSP
  FROM CRPDTA.F4211, CRPDTA.F5542522
 WHERE PDDOCO = SDDOCO
   AND PDDCTO = SDDCTO
   AND PDKCOO = SDKCOO
   AND PDLNID = SDLNID
   AND SDNXTR = '560'
   AND SDDOCO = 138609






