SELECT TO_DATE(DB_EDILD_DATA,'DD/MM/YY') AS DATA, 
       to_char(TO_DATE(DB_EDILD_DATA,'DD/MM/YY'),'DAY') AS DIA, 
       DB_EDILD_DISTR AS VAN, 
       COUNT(1) AS QTDE_ARQ/*,
       MAX(SUBSTR(TO_CHAR(DB_EDILD_DATA,'DDMMYYYYHH24MISS'),9,8))  */
 FROM MERCANET_PRD.DB_EDI_LOTE_DISTR
WHERE DB_EDILD_DATA > '26/12/2017'
 AND SUBSTR(TO_CHAR(DB_EDILD_DATA,'DDMMYYYYHH24MISS'),9,8) BETWEEN '0000000' AND '120000'
 AND NOT EXISTS(SELECT 1 FROM MERCANET_PRD.DB_EDI_PEDIDO WHERE DB_EDIP_NRO LIKE '%D' AND DB_EDIP_LOTE = DB_EDILD_SEQ)
 AND DB_EDILD_CONTEUDO IS NOT NULL 
GROUP BY DB_EDILD_DISTR,TO_DATE(DB_EDILD_DATA,'DD/MM/YY')
ORDER BY DB_EDILD_DISTR, TO_DATE(DB_EDILD_DATA,'DD/MM/YY');


