--SOMA DA QUANTIDADE DE LINHAS DOS ARQUIVOS DE NOTAS GERADOS PARA O LOTE
SELECT --COUNT(DB_EDILE_ARQUIVO) "NUMERO DE ARQUIVOS GERADOS",
       SUM(SUBSTR(DB_EDILE_ARQUIVO, 36, 6)) "SOMA DAS LINHAS RETORNADAS"
  FROM (SELECT DISTINCT DB_EDILE_ARQUIVO
          FROM DB_EDI_LOG_EXP
         WHERE EXISTS (SELECT *
                  FROM DB_EDI_PEDIDO
                 WHERE DB_EDIP_NRO = DB_EDILE_EDIP_NRO
                   AND DB_EDIP_COMPRADOR = DB_EDILE_EDIP_COMP
                   AND DB_EDIP_LOTE = 338743)
                   AND DB_EDILE_EDIA_CODI = 'SEVENPDV_NOT')


