SELECT COUNT(*)
  FROM MERCANET_PRD.DB_PEDIDO,
       MERCANET_PRD.DB_EDI_PEDIDO,
       MERCANET_PRD.DB_EDI_LOTE_DISTR,
       MERCANET_PRD.DB_PEDIDO_DISTR
 WHERE DB_PED_NRO = DB_EDIP_PEDMERC
   AND DB_EDIP_LOTE = DB_EDILD_SEQ
   AND DB_EDILD_DATA >
       TO_DATE('15/03/2014 00:00:00', 'DD/MM/YYYY HH24:MI:SS')
   AND DB_PED_NRO = DB_PEDT_PEDIDO
   AND DB_PEDT_DTDISP IS NULL
   AND EXISTS (SELECT *
          FROM MERCANET_PRD.F5547011
         WHERE TO_CHAR(DB_PED_NRO) = TRIM(SAVR01)
           AND SAEDSP = ' '
           AND SAKCOO = '    ')
   AND DB_PED_DATA_ENVIO < SYSDATE - 0.01; -- APROX 15 MINUTOS
