SELECT  DB_CLI_CODIGO as "Codigo_Cliente",
        DB_CLI_NOME as "Razão Social",
        DB_CLI_REGIAOCOM as "Região",
        (SELECT DB_CLIA_VALOR
           FROM MERCANET_PRD.DB_CLIENTE_ATRIB
          WHERE DB_CLIA_CODIGO = DB_CLI_CODIGO
            AND DB_CLIA_ATRIB = 1007) as "Setor",
        DB_CLI_CIDADE AS "Cidade",
        DB_CLI_ESTADO AS "Estado"
 FROM MERCANET_PRD.DB_EDI_PEDIDO, MERCANET_PRD.DB_CLIENTE
WHERE DB_EDIP_COMPRADOR = DB_CLI_CGCMF
 AND DB_EDIP_VAN IN (529,530)
UNION 
SELECT DISTINCT
        DB_CLI_CODIGO as "Codigo_Cliente",
        DB_CLI_NOME as "Razão Social",
        DB_CLI_REGIAOCOM as "Região",
        (SELECT DB_CLIA_VALOR
           FROM MERCANET_PRD.DB_CLIENTE_ATRIB
          WHERE DB_CLIA_CODIGO = DB_CLI_CODIGO
            AND DB_CLIA_ATRIB = 1007) as "Setor",
        DB_CLI_CIDADE AS "Cidade",
        DB_CLI_ESTADO AS "Estado"
 FROM MERCANET_PRD.DB_EDI_PEDIDO, MERCANET_PRD.DB_CLIENTE, MERCANET_PRD.DB_EDI_PED_COMPL
WHERE DB_EDIP_VAN = 529
  AND DB_EDIP_COMPRADOR = DB_EDIPC_COMPRADOR
  AND DB_EDIP_NRO = DB_EDIPC_NRO
  AND DB_EDIPC_TXT1 = DB_CLI_CGCMF
