
 --- POR DATA DE LANÇAMENTO

SELECT A.ILUKID,A.ILTDAY,A.ILMCU FILIAL,A.ILLITM ITEM,A.ILITM ITEM_CURTO,A.ILLOCN LOCAL,A.ILLOTN LOTE,
       A.ILDOC DOC1,A.ILDCT TPDOC1,A.ILDOCO DOC2,A.ILDCTO TPDOC2,
       CASE 
        WHEN    ILTRDJ = 0
         THEN   ' '
         ELSE   TO_CHAR(TO_DATE(A.ILDGL + 1900000, 'YYYYDDD'), 'DD/MM/YYYY')
       END DATA_TRANS,
       CASE 
        WHEN    ILDGL = 0
         THEN   ' '
         ELSE   TO_CHAR(TO_DATE(A.ILDGL + 1900000, 'YYYYDDD'), 'DD/MM/YYYY')
       END DATA_CONTAB,       
       CASE 
        WHEN    ILTRUM = 'UN'
          THEN  ILTRQT
          ELSE  (SELECT ((A.ILTRQT) * (UMCNV1 / 10000000)) ILTRQT 
                  FROM PRODDTA.F41002
                 WHERE UMMCU = A.ILMCU
                   AND UMITM = A.ILITM
                   AND UMUM  = A.ILTRUM)
        END QTDE_EM_UN,
        (A.ILPAID/100) VALOR,
        ILTRQT QTDE_ORIGINAL, ILTRUM UM_ORIGINAL
 FROM PRODDTA.F4111 A
WHERE A.ILMCU         = '    DIFARCAT'
  AND A.ILITM         = &ITEM_CURTO
  AND A.ILIPCD       != 'X'
ORDER BY A.ILUKID