UPDATE DB_NOTA_FISCAL
   SET DB_NOTA_DT_ENVIO = NULL
 WHERE EXISTS (SELECT *
          FROM DB_PEDIDO
         WHERE DB_PED_NRO_ORIG = DB_NOTA_PED_ORIG
           AND EXISTS (SELECT *
                  FROM DB_EDI_PEDIDO
                 WHERE DB_EDIP_PEDMERC = DB_PED_NRO
                   AND DB_EDIP_LOTE = 76132));



DELETE FROM DB_EDI_LOG_EXP
 WHERE EXISTS (SELECT *
          FROM DB_EDI_PEDIDO
         WHERE DB_EDILE_EDIP_NRO = DB_EDIP_NRO
           AND DB_EDILE_EDIP_COMP = DB_EDIP_COMPRADOR
           AND DB_EDIP_LOTE IN (78361,80554))
   AND DB_EDILE_EDIA_CODI = 'SEVENPDV_RET';
   
   

UPDATE DB_EDI_PEDIDO A
   SET DB_EDIP_DTENVIO = NULL,
       A.DB_EDIP_TXT2  = A.DB_EDIP_OBS2,
       A.DB_EDIP_TXT3  = A.DB_EDIP_OBS1
/* SELECT DB_EDIP_LOTE, DB_EDIP_OBS2 FROM DB_EDI_PEDIDO*/
 WHERE DB_EDIP_LOTE in (78361, 80554);
