SELECT SAUKID,SAOORN,SAAN8,SAVR01, SAZ55ORI, SAEDBT, SAEDSP, SADOCO, SAUPMJ, SATDAY, SHDOCO,SHAN8,SHHOLD
  FROM PRODDTA.F42019, PRODDTA.F5547011
 WHERE SHOORN =  SAVR01 
   AND SAEDBT = 'E'
   AND SADOCO = 0
   AND SHHOLD = ' '
   AND SAAN8 = SHAN8
   AND SAOORN = 'MERCANET'
   AND SAUPMJ > 118053
 --AND SDNXTR NOT IN ('980','984')
GROUP BY SAUKID,SAOORN,SAAN8,SAVR01, SAZ55ORI, SAEDBT, SAEDSP, SADOCO, SAUPMJ, SATDAY, SHDOCO,SHAN8,SHHOLD;

