 SELECT 
   UVSLKY, UVSEQ, UCDL01, UCOBNM, UCVER, UCJOBQ, UVRCTT, UCGPTX
FROM 
   qaDTA.F5500V30,
   qaDTA.F5500300
WHERE 
   UCSLKY = UVSLKY
   AND UCSEQ = UVSEQ
   AND UVRCTT > 0
ORDER BY
--   UVRCTT DESC   
  UVSEQ
