 SELECT DISTINCT
    DB_EDILE_EDIA_CODi
 /*   SUBSTR(SPLITVALUE,1,14) CNPJ ,
    SUBSTR(SPLITVALUE,15,13) EAN,
    SUBSTR(SPLITVALUE,28,6) CENTRAL_PROCESSO,
    SUBSTR(SPLITVALUE,34,1) FIXO_A,
    SUBSTR(SPLITVALUE,35,3) MOTIVO_RET,
    SUBSTR(SPLITVALUE,38,4) QUANTIDADE_ATENDIDA,
    SUBSTR(SPLITVALUE,42,15) NRO_NOTAFISCAL,
    SUBSTR(SPLITVALUE,57,8) DATA_NOTAFISCAL,
    SUBSTR(SPLITVALUE,65,5) DESCONTO,
    SUBSTR(SPLITVALUE,70,2) CODIGO_PROJETO,
    SUBSTR(SPLITVALUE,72,15) ORDEM_COMPRA*/
    FROM  DB_EDI_LOG_EXP,
          TABLE(FNC_SPLIT(DB_EDILE_CONTEUDO,CHR(10))) T,
          DB_EDI_PEDIDO 
    WHERE DB_EDILE_EDIP_NRO = DB_EDIP_NRO
      AND DB_EDILE_EDIP_COMP = DB_EDIP_COMPRADOR 
      AND SUBSTR(SPLITVALUE,1,14) = DB_EDIP_COMPRADOR 
      AND DB_EDIP_LOTE  = 83963