WITH TAB1 AS 
(SELECT /*+ MATERIALIZE */ PV05_CONTROLE,
      rtrim(xmlagg(xmlelement(e,
      trim(pv05_tagfiltro) || '#') ORDER BY
 PV05_SEQ) .extract('//text()'),
      ',')
      filtros 
FROM MPV05 TB_FILTROS GROUP BY
 PV05_CONTROLE),
      TAB2 AS 
(SELECT /*+ MATERIALIZE */ DISTINCT PV06_POLITICA,
      PV06_CONTROLE,
      PV06_TIPO,
      PV06_IDENT,
      PV06_IDREGRA,
     PV06_DATA_ALTER
FROM MPV06 
WHERE PV06_TIPO = 'A') 
SELECT * FROM 
(SELECT TAB3.DB_ORDP_SEQUENCIA AS "ORDEM DE BUSCA",
      TAB2.PV06_POLITICA AS "POLITICA",
      TAB5.DB_RES_DESC AS "DESCRICAO",
      REPLACE(SUBSTR(TAB1.FILTROS,
      1,
      LENGTH(TAB1.FILTROS) - 1),
      '#',
      ' | ') AS "FILTROS UTILIZADOS",
      REPLACE(TAB2.PV06_IDENT,
      '#',
      ' | ') AS "VALORES FILTRADOS",
      TAB4.DB_CPO_TAGATRIB AS "CAMPO ATRIBUIDO",
      TAB4.DB_CPO_VALORINF AS "VALOR ATRIBUIDO",
      length(REPLACE(SUBSTR(TAB1.FILTROS,
      1,
      LENGTH(TAB1.FILTROS) - 1),
      '#',
      ' | ')) - length(replace(REPLACE(SUBSTR(TAB1.FILTROS,
      1,
      LENGTH(TAB1.FILTROS) - 1),
      '#',
      ' | '),
      '|',
      null)) + 1 AS "TOTAL DE FILTROS",
      length(REPLACE(TAB2.PV06_IDENT,
      '#',
      ' | ')) - length(replace(REPLACE(TAB2.PV06_IDENT,
      '#',
      ' | '),
      '|',
      null)) + 1 AS "TOTAL DE VALORES FILTRADOS",
      pv06_data_alter AS "DATA ULTIMA ALTERACAO NA REGRA",
      
CASE WHEN TAB5.DB_RES_DTINI < SYSDATE AND TAB5.DB_RES_DTFIM > SYSDATE THEN 'VIGENTE' ELSE 'INATIVA' END AS "STATUS DA REGRA",
'PROBLEMA COM VIRGULAS' AS "TIPO DO PROBLEMA",
'\\SRVDC40\Mercanet\solucoes_regras\solucao1.txt'
AS "SOLUCAO DO PROBLEMA"
FROM TAB1,
     TAB2,
     DB_ORDEM_POLITICAS TAB3,
     DB_CPO_ATRIB TAB4,  
     DB_RESTRICAO TAB5
WHERE TAB2.PV06_POLITICA = TAB5.DB_RES_CODIGO
AND TAB2.PV06_TIPO = 'A' 
AND TAB2.PV06_CONTROLE = TAB1.PV05_CONTROLE 
AND TAB2.PV06_POLITICA = TAB3.DB_ORDP_POLITICA 
AND TAB2.PV06_POLITICA = TAB4.DB_CPO_CODIGO 
AND TAB2.PV06_IDREGRA = TAB4.DB_CPO_RES_PAI 
ORDER BY
 TAB3.DB_ORDP_SEQUENCIA,
 TAB2.PV06_POLITICA,
 TAB2.PV06_CONTROLE,
 TAB2.PV06_IDENT
)
WHERE "TOTAL DE VALORES FILTRADOS" <> "TOTAL DE FILTROS" 
UNION ALL
SELECT * FROM 
(SELECT TAB3.DB_ORDP_SEQUENCIA AS "ORDEM DE BUSCA",
      TAB2.PV06_POLITICA AS "POLITICA",
      TAB5.DB_RES_DESC AS "DESCRICAO",
      REPLACE(SUBSTR(TAB1.FILTROS,
      1,
      LENGTH(TAB1.FILTROS) - 1),
      '#',
      ' | ') AS "FILTROS UTILIZADOS",
      REPLACE(TAB2.PV06_IDENT,
      '#',
      ' | ') AS "VALORES FILTRADOS",
      TAB4.DB_CPO_TAGATRIB AS "CAMPO ATRIBUIDO",
      TAB4.DB_CPO_VALORINF AS "VALOR ATRIBUIDO",
      length(REPLACE(SUBSTR(TAB1.FILTROS,
      1,
      LENGTH(TAB1.FILTROS) - 1),
      '#',
      ' | ')) - length(replace(REPLACE(SUBSTR(TAB1.FILTROS,
      1,
      LENGTH(TAB1.FILTROS) - 1),
      '#',
      ' | '),
      '|',
      null)) + 1 AS "TOTAL DE FILTROS",
      length(REPLACE(TAB2.PV06_IDENT,
      '#',
      ' | ')) - length(replace(REPLACE(TAB2.PV06_IDENT,
      '#',
      ' | '),
      '|',
      null)) + 1 AS "TOTAL DE VALORES FILTRADOS",
      pv06_data_alter AS "DATA ULTIMA ALTERACAO NA REGRA",
      
CASE WHEN TAB5.DB_RES_DTINI < SYSDATE AND TAB5.DB_RES_DTFIM > SYSDATE THEN 'VIGENTE' ELSE 'INATIVA' END AS "STATUS DA REGRA",
'PROBLEMA COM ENTER NAS LINHAS' AS "TIPO DO PROBLEMA",
 '\\SRVDC40\Mercanet\solucoes_regras\solucao2.txt'
       AS "SOLUCAO DO PROBLEMA"
FROM TAB1,
      TAB2,
      DB_ORDEM_POLITICAS TAB3,
      DB_CPO_ATRIB TAB4,  
      DB_RESTRICAO TAB5
WHERE TAB2.PV06_POLITICA = TAB5.DB_RES_CODIGO
AND TAB2.PV06_TIPO = 'A' 
AND TAB2.PV06_CONTROLE = TAB1.PV05_CONTROLE 
AND TAB2.PV06_POLITICA = TAB3.DB_ORDP_POLITICA 
AND TAB2.PV06_POLITICA = TAB4.DB_CPO_CODIGO 
AND TAB2.PV06_IDREGRA = TAB4.DB_CPO_RES_PAI 
AND TAB2.PV06_IDENT LIKE '%
%'
ORDER BY
 TAB3.DB_ORDP_SEQUENCIA,
 TAB2.PV06_POLITICA,
 TAB2.PV06_CONTROLE,
 TAB2.PV06_IDENT
)
UNION ALL
SELECT * FROM 
(SELECT TAB3.DB_ORDP_SEQUENCIA AS "ORDEM DE BUSCA",
      TAB2.PV06_POLITICA AS "POLITICA",
      TAB5.DB_RES_DESC AS "DESCRICAO",
      REPLACE(SUBSTR(TAB1.FILTROS,
      1,
      LENGTH(TAB1.FILTROS) - 1),
      '#',
      ' | ') AS "FILTROS UTILIZADOS",
      REPLACE(TAB2.PV06_IDENT,
      '#',
      ' | ') AS "VALORES FILTRADOS",
      TAB4.DB_CPO_TAGATRIB AS "CAMPO ATRIBUIDO",
      TAB4.DB_CPO_VALORINF AS "VALOR ATRIBUIDO",
      length(REPLACE(SUBSTR(TAB1.FILTROS,
      1,
      LENGTH(TAB1.FILTROS) - 1),
      '#',
      ' | ')) - length(replace(REPLACE(SUBSTR(TAB1.FILTROS,
      1,
      LENGTH(TAB1.FILTROS) - 1),
      '#',
      ' | '),
      '|',
      null)) + 1 AS "TOTAL DE FILTROS",
      length(REPLACE(TAB2.PV06_IDENT,
      '#',
      ' | ')) - length(replace(REPLACE(TAB2.PV06_IDENT,
      '#',
      ' | '),
      '|',
      null)) + 1 AS "TOTAL DE VALORES FILTRADOS",
      pv06_data_alter AS "DATA ULTIMA ALTERACAO NA REGRA",
      
CASE WHEN TAB5.DB_RES_DTINI < SYSDATE AND TAB5.DB_RES_DTFIM > SYSDATE THEN 'VIGENTE' ELSE 'INATIVA' END AS "STATUS DA REGRA",
'LINHA COM CAMPO DE ATRIBUIÇÃO SEM VALOR' AS "TIPO DO PROBLEMA",
 '\\SRVDC40\Mercanet\solucoes_regras\solucao3.txt'
       AS "SOLUCAO DO PROBLEMA"
FROM TAB1,
     TAB2,
     DB_ORDEM_POLITICAS TAB3,
     DB_CPO_ATRIB TAB4,  
     DB_RESTRICAO TAB5,
     (SELECT db_resr_seqpai, rtrim(xmlagg(xmlelement(e,
      trim(db_resr_valor)) ORDER BY
 db_resr_seq) .extract('//text()'),
      ',')
      valores 
 FROM DB_RESTR_REGRAS 
 GROUP BY db_resr_seqpai) TAB6
WHERE TAB2.PV06_POLITICA = TAB5.DB_RES_CODIGO
AND TAB2.PV06_TIPO = 'A' 
AND TAB2.PV06_CONTROLE = TAB1.PV05_CONTROLE 
AND TAB2.PV06_POLITICA = TAB3.DB_ORDP_POLITICA 
AND TAB2.PV06_POLITICA = TAB4.DB_CPO_CODIGO 
AND TAB6.VALORES = REPLACE(TAB2.PV06_IDENT,'#',NULL)
AND TAB6.DB_RESR_SEQPAI = TAB4.DB_CPO_RES_PAI
AND TAB4.DB_CPO_VALORINF IS NULL 
ORDER BY
 TAB3.DB_ORDP_SEQUENCIA,
 TAB2.PV06_POLITICA,
 TAB2.PV06_CONTROLE,
 TAB2.PV06_IDENT
)
