DECLARE
  V_PAROU NUMBER := 0;

BEGIN
  WHILE V_PAROU < 94500 LOOP

    DBMS_OUTPUT.put_line('----------');
    DBMS_OUTPUT.put_line(V_PAROU);

    SELECT TO_NUMBER(TO_CHAR(SYSDATE, 'HH24MISS')) INTO V_PAROU FROM DUAL;

   DBMS_LOCK.sleep(2);

  END LOOP;

END;
