--Condições de Venda:
SELECT * FROM DB_TB_COND_VENDA
SELECT * FROM DB_TB_COND_VENDAAT
SELECT * FROM DB_TB_COND_VPRZ
SELECT * FROM DB_TB_COND_VPRZAT
SELECT * FROM DB_TB_COND_VCVDAIG
SELECT * FROM DB_TB_CONDVENDA_TX


--Promoções de Venda:
SELECT * FROM DB_TB_PROMOCAO
SELECT * FROM DB_TB_PROMOCAO_ATR
SELECT * FROM DB_TB_PROMOCAO_DAT
SELECT * FROM DB_TB_PROMOCAO_DCT
SELECT * FROM DB_TB_PROMOCAO_TX


--Restrições/Atribuições de Venda:
SELECT * FROM DB_RESTRICAO
SELECT * FROM DB_RESTR_FILTROS
SELECT * FROM DB_RESTR_REGRAS
SELECT * FROM DB_RESTR_REGRAS_PAI

 

--Mix de Venda:
SELECT * FROM DB_TB_MIX_VENDA
SELECT * FROM DB_TB_MIX_VENDAP
SELECT * FROM DB_TB_MIX_VENDA_TX

 

--Programação de Ajustes Restrições:
SELECT * FROM DB_PROG_AJUSTE
SELECT * FROM DB_PROGA_CLIENTES
SELECT * FROM DB_PROGA_POLITICAS

 

--Programação de Ajustes Atribuições:
SELECT * FROM DB_ORDEM_POLITICAS

 

--HASH (Indexação das Politicas Comerciais):
SELECT * FROM MPV04
SELECT * FROM MPV05
SELECT * FROM MPV06

 

