
WITH 
VANS AS (
SELECT EM01_CODIGO, EM01_EAN, DB_EDIP_DT_EMISSAO 
  FROM MERCANET_PRD.MEM01,
       (SELECT DISTINCT DB_EDIP_DT_EMISSAO  AS DB_EDIP_DT_EMISSAO
          FROM MERCANET_PRD.DB_EDI_PEDIDO
         WHERE DB_EDIP_DT_EMISSAO >= '01/01/2017'
         --  AND TRIM(TO_CHAR(DB_EDIP_DT_EMISSAO,'DAY')) = 'QUARTA-FEIRA'
         --  AND DB_EDIP_DT_EMISSAO < TO_DATE(SYSDATE,'DD/MM/YY')
         )
WHERE EM01_CODIGO NOT IN (529, 530, 541, 542)
ORDER BY EM01_CODIGO,DB_EDIP_DT_EMISSAO),

PEDIDOS
AS 
(
 SELECT DB_EDIP_VAN, 
        DB_EDIP_DT_EMISSAO,
        DB_EDIP_NRO, 
        DB_EDILD_DATA,
        NVL(SUM(DB_PEDI_PRECO_LIQ * DB_PEDI_QTDE_ATEND), 0) TOTAL_FATURADO
   FROM MERCANET_PRD.DB_EDI_PEDIDO,
        MERCANET_PRD.DB_EDI_LOTE_DISTR,
        MERCANET_PRD.DB_PEDIDO_PROD
  WHERE DB_EDIP_LOTE = DB_EDILD_SEQ(+)
    AND DB_EDIP_PEDMERC = DB_PEDI_PEDIDO(+)
   GROUP BY DB_EDIP_VAN, 
            DB_EDIP_DT_EMISSAO,
            DB_EDIP_NRO, 
            DB_EDILD_DATA,
            DB_EDIP_NRO)
SELECT VANS.EM01_CODIGO AS CODIGO_VAN,
       VANS.EM01_EAN AS NOME_VAN,
       VANS.DB_EDIP_DT_EMISSAO AS DATA_EMISSAO_PEDIDO,
       TO_CHAR(VANS.DB_EDIP_DT_EMISSAO,'DAY') DIA_SEMANA,
       TO_CHAR(VANS.DB_EDIP_DT_EMISSAO,'MONTH') MES,
       COUNT(DISTINCT PEDIDOS.DB_EDIP_NRO) AS QTDE_PEDIDOS,       
       NVL(SUM(PEDIDOS.TOTAL_FATURADO),0) AS VALOR_FATURADO 
  FROM VANS, 
       PEDIDOS
WHERE VANS.EM01_CODIGO = PEDIDOS.DB_EDIP_VAN(+)
AND VANS.DB_EDIP_DT_EMISSAO = PEDIDOS.DB_EDIP_DT_EMISSAO(+)
--AND TO_NUMBER(TO_CHAR(PEDIDOS.DB_EDILD_DATA(+) ,'HH24MISS'))< TO_NUMBER(TO_CHAR(SYSDATE,'HH24MISS'))  --p/ comparar horarios
-- AND VANS.DB_EDIP_DT_EMISSAO >= '02/04/2018'
  GROUP BY VANS.EM01_CODIGO,VANS.EM01_EAN,VANS.DB_EDIP_DT_EMISSAO
  
