SELECT TRUNC(SXXRVF), COUNT(SXXRVT)
  FROM qadta.F4013
WHERE (SXEDF1 = 'S' AND SXXRTC = 'IR')
 AND TRUNC(SXXRVF) = AIAN8
 AND AIHOLD = ' '
 and db_ped_cliente = AIAN8
 GROUP BY TRUNC(SXXRVF)
-- AND TRUNC(SXXRVT) = 
