SELECT DB_EDIP_LOTE, COUNT(1)
  FROM DB_EDI_LOG_EXP, DB_EDI_PEDIDO, DB_EDI_PEDPROD
 WHERE DB_EDILE_EDIP_COMP = DB_EDIP_COMPRADOR
   AND DB_EDILE_EDIP_NRO = DB_EDIP_NRO
   AND DB_EDILE_EDIP_COMP = DB_EDII_COMPRADOR
   AND DB_EDILE_EDIP_NRO = DB_EDII_NRO
   AND DB_EDILE_EDIA_CODI = 'SEVENPDV_RET'
   AND DB_EDIP_LOTE > 84079
 GROUP BY DB_EDIP_LOTE
 ORDER BY DB_EDIP_LOTE
