-- SE O SQL NAO RETORNAR NENHUMA LINHA:--> TODOS OS ITENS FORAM ENVIADOS DO JDE PARA O MERCANET
--SENÃO:--> É MOSTRADO OS ITENS QUE NÃO FORAM ENVIADOS DO JDE


SELECT *
  FROM DB_PEDIDO_PROD A
 WHERE A.DB_PEDI_PEDIDO = '90020062'
   AND NOT EXISTS
                  (SELECT *        
                       FROM INTERFACE_DB_PEDIDO_PROD B
                      WHERE A.DB_PEDI_PEDIDO = B.DB_PEDI_PEDIDO
                        AND A.DB_PEDI_PRODUTO = B.DB_PEDI_PRODUTO)