
SELECT MAX(TO_NUMBER(SUBSTR(DB_EDILD_NOMEARQ, 39, 6))) "TOTAL LINHAS DO ARQUIVO",
       
       SUM(COUNT(*)) "TOTAL DE LINHAS IMPORTADAS",
       
       COUNT(EPD.DB_EDIP_NRO) "TOTAL DE PEDIDOS GERADOS",
       
       CASE WHEN (TO_NUMBER(SUM(COUNT(*))) < MAX(TO_NUMBER(SUBSTR(DB_EDILD_NOMEARQ, 39, 6))) )THEN 'IMPORTAÇÃO NAO FINALIZADA' 
       ELSE CASE WHEN (TO_NUMBER(SUM(COUNT(*))) IS NULL) THEN 'IMPORTAÇÃO NÃO INICIADA' ELSE 'FIM DA IMPORTAÇÃO' END END "OBSERVACAO",
   
             
       '<==ENTRADA DO PEDIDO |||||| RETORNO DO PEDIDO==> ' " ",
       
       MAX((SELECT SUM(TO_NUMBER(SUBSTR(DB_EDILE_ARQUIVO, 36, 6)))
             FROM DB_EDI_LOG_EXP
            WHERE DB_EDIP_COMPRADOR = DB_EDILE_EDIP_COMP
              AND DB_EDIP_NRO = DB_EDILE_EDIP_NRO)) "TOTAL DE LINHAS DO ARQUIVO",
       
       MAX((SELECT COUNT(*)
             FROM DB_EDI_PEDIDO A, DB_EDI_PEDPROD B
            WHERE A.DB_EDIP_COMPRADOR = B.DB_EDII_COMPRADOR
              AND A.DB_EDIP_NRO = B.DB_EDII_NRO
              AND A.DB_EDIP_LOTE = EPD.DB_EDIP_LOTE
              AND A.DB_EDIP_DTENVIO IS NOT NULL
              AND A.DB_EDIP_DTENVIO != '31/12/9999')) "TOTAL DE LINHAS EXPORTADAS"
       
         FROM DB_EDI_LOTE_DISTR ELD, DB_EDI_PEDIDO EPD, DB_EDI_PEDPROD EPP
 WHERE DB_EDIP_VAN = 508
   AND DB_EDIP_LOTE = DB_EDILD_SEQ
   AND DB_EDIP_COMPRADOR = DB_EDII_COMPRADOR
   AND DB_EDIP_NRO = DB_EDII_NRO
  -- AND DB_EDILD_NOMEARQ = 'SP00630905651966000455LGX201205090739_000978.S67'

AND EPD.DB_EDIP_LOTE = 83887 
 GROUP BY ELD.DB_EDILD_NOMEARQ,
          EPD.DB_EDIP_COMPRADOR,
          EPD.DB_EDIP_NRO,
          EPD.DB_EDIP_LOTE