
 SELECT A.DB_EDIP_LOTE       "Nº LOTE",
        A.DB_EDIP_PEDMERC    "Nº PEDIDO MERCANET",
        A.DB_EDIP_NRO        "NºPEDIDO LABORATORIO",
        A.DB_EDIP_COMPRADOR  "CODIGO DO CLIENTE",
        A.DB_EDIP_DT_EMISSAO "DATA DE EMISSAO",
        A.DB_EDIP_EMPRESA    "CODIGO FILIAL DE VENDA",
        A.DB_EDIP_CLIENTE    "CNPJ FILIAL DE VENDA",
        A.DB_EDIP_ORDCOMPRA  "ORDEM DE COMPRA",
        A.DB_EDIP_TIPO_FRE   "TIPO DE FATURAMENTO",
        A.DB_EDIP_FORMAPGTO  "FORMA DE PAGTO",
        A.DB_EDIP_CONDPGTO   "QTD DIAS COND. PAGTO",
        A.DB_EDIP_PRZPAGTO   "PRAZO DE PAGTO ARQ",
        A.DB_EDIP_VAN        "CODIGO DA VAN",
        A.DB_EDIP_LABCOD     "CODIGO LAB NO MERCANET",
        A.DB_EDIP_LAB        "CODIGO DE CONTROLE LAB",
        A.DB_EDIP_PROJETO    "CODIGO DO PROJETO LAB",
        B.DB_EDILD_DATA      "DATA DA IMPORTAÇÃO ARQ",
        A.DB_EDIP_DTENVIO    "DATA DE RETORNO ARQ P/ VAN",
        B.DB_EDILD_NOMEARQ     "NOME DO ARQUIVO IMPORTADO" , 
        C.DB_PED_DATA_ENVIO "DATA DO ENVIO PARA O JDE"
   FROM MERCANET_QA.DB_EDI_PEDIDO A, MERCANET_QA.DB_EDI_LOTE_DISTR B , MERCANET_QA.DB_PEDIDO C
  WHERE A.DB_EDIP_LOTE = B.DB_EDILD_SEQ
    AND B.DB_EDILD_DATA BETWEEN 
        TO_DATE('30/11/2012 00:00:00', 'DD/MM/YYYY HH24:MI:SS')
    AND  TO_DATE('30/11/2012 00:00:00', 'DD/MM/YYYY HH24:MI:SS')
    --INFORMAR O INTERVALO DE DATA DE IMPORTAÇÃO
    AND A.DB_EDIP_PEDMERC = C.DB_PED_NRO
AND  NOT EXISTS(SELECT * FROM MERCANET_QA.F5547011
                 WHERE TO_CHAR(C.DB_PED_NRO) = TRIM(SAVR01)) 
