insert into DSALES.TRACE_MERCANET
            (SQL_TEXT,SQL_ID,SHARABLE_MEM,PERSISTENT_MEM,RUNTIME_MEM,SORTS,LOADED_VERSIONS,OPEN_VERSIONS,USERS_OPENING,
             FETCHES,EXECUTIONS,PX_SERVERS_EXECUTIONS,END_OF_FETCH_COUNT,USERS_EXECUTING,LOADS,FIRST_LOAD_TIME,
             INVALIDATIONS,PARSE_CALLS,DISK_READS,DIRECT_WRITES,BUFFER_GETS,APPLICATION_WAIT_TIME,CONCURRENCY_WAIT_TIME,
             CLUSTER_WAIT_TIME,USER_IO_WAIT_TIME,PLSQL_EXEC_TIME,JAVA_EXEC_TIME,ROWS_PROCESSED,COMMAND_TYPE,OPTIMIZER_MODE,
             OPTIMIZER_COST,OPTIMIZER_ENV,OPTIMIZER_ENV_HASH_VALUE,PARSING_USER_ID,PARSING_SCHEMA_ID,PARSING_SCHEMA_NAME,
             KEPT_VERSIONS,ADDRESS,TYPE_CHK_HEAP,HASH_VALUE,OLD_HASH_VALUE,PLAN_HASH_VALUE,CHILD_NUMBER,SERVICE,SERVICE_HASH,
             MODULE,MODULE_HASH,ACTION,ACTION_HASH,SERIALIZABLE_ABORTS,OUTLINE_CATEGORY,CPU_TIME,ELAPSED_TIME,OUTLINE_SID,
             CHILD_ADDRESS,SQLTYPE,REMOTE,OBJECT_STATUS,LITERAL_HASH_VALUE,LAST_LOAD_TIME,IS_OBSOLETE,CHILD_LATCH,SQL_PROFILE,
             PROGRAM_ID,PROGRAM_LINE#,EXACT_MATCHING_SIGNATURE,FORCE_MATCHING_SIGNATURE,LAST_ACTIVE_TIME,BIND_DATA,TYPECHECK_MEM) 
  SELECT SQL_TEXT,SQL_ID,SHARABLE_MEM,PERSISTENT_MEM,RUNTIME_MEM,SORTS,LOADED_VERSIONS,OPEN_VERSIONS,USERS_OPENING,
     FETCHES,EXECUTIONS,PX_SERVERS_EXECUTIONS,END_OF_FETCH_COUNT,USERS_EXECUTING,LOADS,FIRST_LOAD_TIME,INVALIDATIONS,
     PARSE_CALLS,DISK_READS,DIRECT_WRITES,BUFFER_GETS,APPLICATION_WAIT_TIME,CONCURRENCY_WAIT_TIME,CLUSTER_WAIT_TIME,
     USER_IO_WAIT_TIME,PLSQL_EXEC_TIME,JAVA_EXEC_TIME,ROWS_PROCESSED,COMMAND_TYPE,OPTIMIZER_MODE,OPTIMIZER_COST,
     OPTIMIZER_ENV,OPTIMIZER_ENV_HASH_VALUE,PARSING_USER_ID,PARSING_SCHEMA_ID,PARSING_SCHEMA_NAME,KEPT_VERSIONS,ADDRESS,
     TYPE_CHK_HEAP,HASH_VALUE,OLD_HASH_VALUE,PLAN_HASH_VALUE,CHILD_NUMBER,SERVICE,SERVICE_HASH,MODULE,MODULE_HASH,
     ACTION,ACTION_HASH,SERIALIZABLE_ABORTS,OUTLINE_CATEGORY,CPU_TIME,ELAPSED_TIME,OUTLINE_SID,CHILD_ADDRESS,SQLTYPE,
     REMOTE,OBJECT_STATUS,LITERAL_HASH_VALUE,LAST_LOAD_TIME,IS_OBSOLETE,CHILD_LATCH,SQL_PROFILE,PROGRAM_ID,PROGRAM_LINE#,
     EXACT_MATCHING_SIGNATURE,FORCE_MATCHING_SIGNATURE,LAST_ACTIVE_TIME,BIND_DATA,TYPECHECK_MEM
    FROM V$SQL
   WHERE PARSING_SCHEMA_NAME = 'MERCANET_HML'
    -- AND UPPER(MODULE) NOT IN ('CQOPERLOG.EXE')
  minus
  SELECT SQL_TEXT,SQL_ID,SHARABLE_MEM,PERSISTENT_MEM,RUNTIME_MEM,SORTS,LOADED_VERSIONS,OPEN_VERSIONS,USERS_OPENING,
     FETCHES,EXECUTIONS,PX_SERVERS_EXECUTIONS,END_OF_FETCH_COUNT,USERS_EXECUTING,LOADS,FIRST_LOAD_TIME,INVALIDATIONS,
     PARSE_CALLS,DISK_READS,DIRECT_WRITES,BUFFER_GETS,APPLICATION_WAIT_TIME,CONCURRENCY_WAIT_TIME,CLUSTER_WAIT_TIME,
     USER_IO_WAIT_TIME,PLSQL_EXEC_TIME,JAVA_EXEC_TIME,ROWS_PROCESSED,COMMAND_TYPE,OPTIMIZER_MODE,OPTIMIZER_COST,
     OPTIMIZER_ENV,OPTIMIZER_ENV_HASH_VALUE,PARSING_USER_ID,PARSING_SCHEMA_ID,PARSING_SCHEMA_NAME,KEPT_VERSIONS,ADDRESS,
     TYPE_CHK_HEAP,HASH_VALUE,OLD_HASH_VALUE,PLAN_HASH_VALUE,CHILD_NUMBER,SERVICE,SERVICE_HASH,MODULE,MODULE_HASH,
     ACTION,ACTION_HASH,SERIALIZABLE_ABORTS,OUTLINE_CATEGORY,CPU_TIME,ELAPSED_TIME,OUTLINE_SID,CHILD_ADDRESS,SQLTYPE,
     REMOTE,OBJECT_STATUS,LITERAL_HASH_VALUE,LAST_LOAD_TIME,IS_OBSOLETE,CHILD_LATCH,SQL_PROFILE,PROGRAM_ID,PROGRAM_LINE#,
     EXACT_MATCHING_SIGNATURE,FORCE_MATCHING_SIGNATURE,LAST_ACTIVE_TIME,BIND_DATA,TYPECHECK_MEM
    FROM DSALES.TRACE_MERCANET T2
  minus
  SELECT SQL_TEXT,SQL_ID,SHARABLE_MEM,PERSISTENT_MEM,RUNTIME_MEM,SORTS,LOADED_VERSIONS,OPEN_VERSIONS,USERS_OPENING,
     FETCHES,EXECUTIONS,PX_SERVERS_EXECUTIONS,END_OF_FETCH_COUNT,USERS_EXECUTING,LOADS,FIRST_LOAD_TIME,INVALIDATIONS,
     PARSE_CALLS,DISK_READS,DIRECT_WRITES,BUFFER_GETS,APPLICATION_WAIT_TIME,CONCURRENCY_WAIT_TIME,CLUSTER_WAIT_TIME,
     USER_IO_WAIT_TIME,PLSQL_EXEC_TIME,JAVA_EXEC_TIME,ROWS_PROCESSED,COMMAND_TYPE,OPTIMIZER_MODE,OPTIMIZER_COST,
     OPTIMIZER_ENV,OPTIMIZER_ENV_HASH_VALUE,PARSING_USER_ID,PARSING_SCHEMA_ID,PARSING_SCHEMA_NAME,KEPT_VERSIONS,ADDRESS,
     TYPE_CHK_HEAP,HASH_VALUE,OLD_HASH_VALUE,PLAN_HASH_VALUE,CHILD_NUMBER,SERVICE,SERVICE_HASH,MODULE,MODULE_HASH,
     ACTION,ACTION_HASH,SERIALIZABLE_ABORTS,OUTLINE_CATEGORY,CPU_TIME,ELAPSED_TIME,OUTLINE_SID,CHILD_ADDRESS,SQLTYPE,
     REMOTE,OBJECT_STATUS,LITERAL_HASH_VALUE,LAST_LOAD_TIME,IS_OBSOLETE,CHILD_LATCH,SQL_PROFILE,PROGRAM_ID,PROGRAM_LINE#,
     EXACT_MATCHING_SIGNATURE,FORCE_MATCHING_SIGNATURE,LAST_ACTIVE_TIME,BIND_DATA,TYPECHECK_MEM
 FROM DSALES.TRACE_MERCANET_OLD T2;
--  ORDER BY LAST_LOAD_TIME DESC; 
COMMIT;

/*
TRUNCATE TABLE DSALES.TRACE_MERCANET;

*/

/*

select * from DSALES.TRACE_MERCANET
order by last_load_time desc, last_active_time desc, sql_id desc 

*/

/*
SELECT * FROM V$SQL 
WHERE MODULE = 'Mercador.exe'
AND PARSING_SCHEMA_NAME = 'MERCANET_HML'
ORDER BY LAST_ACTIVE_TIME DESC */

