SELECT DM03_SERVICO AS INSTANCIA,
       DM03_DESCRICAO AS "DESCRICAO DO AGENDAMENTO",
       DM03_GUID AS "CODIGO DO AGENDAMENTO",
       DM03_GRUPO AS "GRUPO",
       MAX(DM05_MSGDATA) AS "ULTIMA EXECUCAO",
       (CASE
         WHEN (UPPER(DM03_DESCRICAO) LIKE UPPER('%PREÇO%') OR
              UPPER(DM03_DESCRICAO) LIKE UPPER('%PRODUTO%') OR
              UPPER(DM03_DESCRICAO) LIKE UPPER('%CONCILIACAO%') OR
              UPPER(DM03_GRUPO) LIKE UPPER('%PREÇO%') OR
              UPPER(DM03_GRUPO) LIKE UPPER('%PRODUTO%') OR
              UPPER(DM03_GRUPO) LIKE UPPER('%CONCILIACAO%')) AND
              MAX(DM05_MSGDATA) < SYSDATE - 1 THEN
          'WARMING'
         ELSE
          CASE
            WHEN UPPER(DM03_DESCRICAO) NOT LIKE UPPER('%PREÇO%') AND
                 UPPER(DM03_DESCRICAO) NOT LIKE UPPER('%PRODUTO%') AND
                 UPPER(DM03_DESCRICAO) NOT LIKE UPPER('%CONCILIACAO%') AND
                 UPPER(DM03_GRUPO) NOT LIKE UPPER('%PREÇO%') AND
                 UPPER(DM03_GRUPO) NOT LIKE UPPER('%PRODUTO%') AND
                 UPPER(DM03_GRUPO) NOT LIKE UPPER('%CONCILIACAO%') AND
                 MAX(DM05_MSGDATA) < SYSDATE - 0.1 THEN
             'WARMING'
            ELSE
             'RODANDO'
          END
       END) STATUS
  FROM MERCANET_PRD.MDM05, MERCANET_PRD.MDM03
 WHERE DM05_GUID = DM03_GUID
   AND DM03_STATUS = 1 
 GROUP BY DM03_SERVICO, DM03_DESCRICAO, DM03_GRUPO, DM03_GUID
 ORDER BY DM03_SERVICO, DM03_GUID; 
